use crate::core::nt_core_bank::{PipelineConfig, ReasoningMemory, L1Memory, SceneBlock, Persona};

pub struct OffloadManager {
    pub base_path: std::path::PathBuf,
    config: PipelineConfig,
    ref_files: Vec<std::path::PathBuf>,
}

impl OffloadManager {
    pub fn new(base_path: &std::path::Path) -> Self {
        let refs_dir = base_path.join("refs");
        let _ = std::fs::create_dir_all(&refs_dir);
        Self { base_path: base_path.to_path_buf(), config: PipelineConfig::default(), ref_files: Vec::new() }
    }

    pub fn offload_memory(&mut self, mem: &ReasoningMemory) -> Result<String, String> {
        let refs_dir = self.base_path.join("refs");
        let filename = format!("ref-{}.md", mem.id.replace('-', "_"));
        let path = refs_dir.join(&filename);
        let content = format!(
            "# {}\n\n- **type**: {:?}\n- **reward**: {:.2}\n- **time**: {}\n- **tier**: {:?}\n\n## Task\n{}\n\n## T3 Views\n{}\n{}\n{}\n\n## Micro-Edits\n",
            mem.id, mem.task_type, mem.reward, mem.timestamp, mem.tier, mem.task_description,
            mem.t3_views.struct_view.as_deref().unwrap_or(""),
            mem.t3_views.semantic_view.as_deref().unwrap_or(""),
            mem.t3_views.reflect_view.as_deref().unwrap_or(""),
        );
        let edits_str: Vec<String> = mem.micro_edits.iter().map(|e| format!("- {}", e.summary())).collect();
        let full = format!("{}\n{}\n", content, edits_str.join("\n"));
        std::fs::write(&path, &full).map_err(|e| format!("Offload write: {}", e))?;
        self.ref_files.push(path);
        while self.ref_files.len() > self.config.max_ref_files {
            let old = self.ref_files.remove(0);
            let _ = std::fs::remove_file(&old);
        }
        Ok(filename)
    }

    pub fn save_l1_extraction(&self, memories: &[L1Memory]) -> Result<String, String> {
        let path = self.base_path.join("l1_atomic.jsonl");
        let mut file = std::fs::OpenOptions::new()
            .create(true).append(true).open(&path)
            .map_err(|e| format!("L1 save: {}", e))?;
        for mem in memories {
            let line = serde_json::to_string(mem).map_err(|e| format!("L1 serialize: {}", e))?;
            use std::io::Write;
            writeln!(file, "{}", line).map_err(|e| format!("L1 write: {}", e))?;
        }
        Ok(path.to_string_lossy().to_string())
    }

    pub fn save_scene(&self, scene: &SceneBlock) -> Result<String, String> {
        let path = self.base_path.join("scenes").join(format!("scene_{}.md", scene.id));
        let parent = path.parent().ok_or_else(|| {
            format!("[offload] scene path has no parent: {}", path.display())
        })?;
        let _ = std::fs::create_dir_all(parent);
        let content = format!(
            "# Scene: {}\n\n**summary**: {}\n**heat**: {}\n**created**: {}\n**updated**: {}\n\n{}\n",
            scene.id, scene.summary, scene.heat, scene.created_at, scene.updated_at,
            scene.content.join("\n\n")
        );
        std::fs::write(&path, &content).map_err(|e| format!("Scene save: {}", e))?;
        Ok(path.to_string_lossy().to_string())
    }

    pub fn save_persona(&self, persona: &Persona) -> Result<String, String> {
        let path = self.base_path.join("persona.md");
        let content = format!(
            "# User Persona\n\n> Generated by L3 pipeline\n\n## Base Anchors\n{}\n\n## Interest Map\n{}\n\n## Interaction Protocol\n{}\n\n## Cognitive Kernel\n{}\n\n*Last updated: {}*\n",
            persona.base_anchors.join("\n- "),
            persona.interest_map.join("\n- "),
            persona.interaction_protocol.join("\n- "),
            persona.cognitive_kernel.join("\n- "),
            chrono::Utc::now().timestamp(),
        );
        std::fs::write(&path, &content).map_err(|e| format!("Persona save: {}", e))?;
        Ok(path.to_string_lossy().to_string())
    }

    pub fn load_persona(&self) -> Option<String> {
        let path = self.base_path.join("persona.md");
        match std::fs::read_to_string(&path) {
            Ok(s) => Some(s),
            Err(e) => {
                log::warn!("[offload] load persona: {}", e);
                None
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_offload_manager_new() {
        let tmp = std::env::temp_dir().join("neotrix-test-offload");
        let _ = std::fs::remove_dir_all(&tmp);
        let om = OffloadManager::new(&tmp);
        assert_eq!(om.base_path, tmp);
    }

    #[test]
    fn test_offload_manager_load_persona_nonexistent() {
        let tmp = std::env::temp_dir().join("neotrix-test-offload-nonexistent");
        let _ = std::fs::remove_dir_all(&tmp);
        let om = OffloadManager::new(&tmp);
        assert!(om.load_persona().is_none());
    }
}
