use std::collections::BTreeSet;

use crate::ir::{Function, Module, TestCase, TestSuite, Type};

pub fn generate(suite: &TestSuite) -> String {
    let mut out = String::new();

    out.push_str("// Generated by nt-lang. DO NOT EDIT.\n");
    out.push_str(&format!("// Source: {}\n\n", suite.source_file.display()));

    let all_imports: BTreeSet<&str> = suite
        .tests
        .iter()
        .flat_map(|t| t.imports.iter().map(|s| s.as_str()))
        .collect();

    for imp in &all_imports {
        out.push_str(&format!("use {};\n", imp));
    }
    if !all_imports.is_empty() {
        out.push('\n');
    }

    for test in &suite.tests {
        out.push_str(&generate_test(test));
    }

    out
}

fn generate_test(test: &TestCase) -> String {
    let mut out = String::new();

    out.push_str("#[test]\n");
    out.push_str(&format!("fn {}() {{\n", test.name));

    if let Some(setup) = &test.setup {
        for line in setup.trim().lines() {
            out.push_str(&format!("    {}\n", line));
        }
    }

    for line in test.code.trim().lines() {
        out.push_str(&format!("    {}\n", line));
    }

    out.push_str("}\n\n");
    out
}

#[allow(dead_code)]
pub fn generate_module(module: &Module) -> String {
    let mut out = String::new();
    let mut all_imports: BTreeSet<&str> = BTreeSet::new();
    for imp in &module.imports {
        all_imports.insert(imp.path.as_str());
    }
    for imp in &all_imports {
        out.push_str(&format!("use {};\n", imp));
    }
    if !all_imports.is_empty() {
        out.push('\n');
    }
    for func in &module.functions {
        out.push_str(&generate_function(func));
    }
    for test in &module.tests {
        out.push_str(&generate_test(test));
    }
    out
}

#[allow(dead_code)]
fn generate_function(func: &Function) -> String {
    let mut out = String::new();
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, type_to_rust(&p.param_type)))
        .collect();
    let return_type = type_to_rust(&func.return_type);
    out.push_str(&format!(
        "pub fn {}({}) -> {} {{\n    todo!(\"function body not yet generated\")\n}}\n\n",
        func.name,
        params.join(", "),
        return_type
    ));
    out
}

#[allow(dead_code)]
fn type_to_rust(t: &Type) -> String {
    match t {
        Type::Vsa(_, _) => "QuantizedVSA".to_string(),
        Type::F32 => "f32".to_string(),
        Type::F64 => "f64".to_string(),
        Type::U64 => "u64".to_string(),
        Type::I64 => "i64".to_string(),
        Type::Usize => "usize".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::Vec(inner) => format!("Vec<{}>", type_to_rust(inner)),
        Type::VecU8 => "Vec<u8>".to_string(),
        Type::Fuzzy => "f64".to_string(),
        Type::Named(name) => name.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{TestCase, TestSuite};
    use std::path::PathBuf;

    #[test]
    fn test_generates_simple_suite() {
        let suite = TestSuite {
            name: "basic".into(),
            description: "basic tests".into(),
            source_file: PathBuf::from("test_suites/basic.nt"),
            tests: vec![TestCase {
                name: "test_one".into(),
                description: "first test".into(),
                imports: vec!["crate::core::Foo".into()],
                setup: None,
                code: "assert_eq!(2 + 2, 4);".into(),
            }],
        };

        let output = generate(&suite);
        assert!(output.contains("use crate::core::Foo;"));
        assert!(output.contains("fn test_one()"));
        assert!(output.contains("assert_eq!(2 + 2, 4);"));
        assert!(output.contains("// Source: test_suites/basic.nt"));
    }

    #[test]
    fn test_generates_setup_block() {
        let suite = TestSuite {
            name: "with_setup".into(),
            description: "setup test".into(),
            source_file: PathBuf::from("test_suites/setup.nt"),
            tests: vec![TestCase {
                name: "test_setup".into(),
                description: "test with setup".into(),
                imports: vec![],
                setup: Some("let x = 42;".into()),
                code: "assert_eq!(x, 42);".into(),
            }],
        };

        let output = generate(&suite);
        assert!(output.contains("let x = 42;"));
        assert!(output.contains("assert_eq!(x, 42);"));
    }
}
