use std::collections::BTreeSet;

use crate::ir::{TestCase, TestSuite};

pub fn generate(suite: &TestSuite) -> String {
    let mut out = String::new();

    out.push_str("// Generated by nt-lang. DO NOT EDIT.\n");
    out.push_str(&format!("// Source: {}\n\n", suite.source_file.display()));

    let all_imports: BTreeSet<&str> = suite
        .tests
        .iter()
        .flat_map(|t| t.imports.iter().map(|s| s.as_str()))
        .collect();

    for imp in &all_imports {
        out.push_str(&format!("use {};\n", imp));
    }
    if !all_imports.is_empty() {
        out.push('\n');
    }

    for test in &suite.tests {
        out.push_str(&generate_test(test));
    }

    out
}

fn generate_test(test: &TestCase) -> String {
    let mut out = String::new();

    out.push_str(&format!("#[test]\n"));
    out.push_str(&format!("fn {}() {{\n", test.name));

    if let Some(setup) = &test.setup {
        for line in setup.trim().lines() {
            out.push_str(&format!("    {}\n", line));
        }
    }

    for line in test.code.trim().lines() {
        out.push_str(&format!("    {}\n", line));
    }

    out.push_str("}\n\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{TestCase, TestSuite};
    use std::path::PathBuf;

    #[test]
    fn test_generates_simple_suite() {
        let suite = TestSuite {
            name: "basic".into(),
            description: "basic tests".into(),
            source_file: PathBuf::from("test_suites/basic.nt"),
            tests: vec![TestCase {
                name: "test_one".into(),
                description: "first test".into(),
                imports: vec!["crate::core::Foo".into()],
                setup: None,
                code: "assert_eq!(2 + 2, 4);".into(),
            }],
        };

        let output = generate(&suite);
        assert!(output.contains("use crate::core::Foo;"));
        assert!(output.contains("fn test_one()"));
        assert!(output.contains("assert_eq!(2 + 2, 4);"));
        assert!(output.contains("// Source: test_suites/basic.nt"));
    }

    #[test]
    fn test_generates_setup_block() {
        let suite = TestSuite {
            name: "with_setup".into(),
            description: "setup test".into(),
            source_file: PathBuf::from("test_suites/setup.nt"),
            tests: vec![TestCase {
                name: "test_setup".into(),
                description: "test with setup".into(),
                imports: vec![],
                setup: Some("let x = 42;".into()),
                code: "assert_eq!(x, 42);".into(),
            }],
        };

        let output = generate(&suite);
        assert!(output.contains("let x = 42;"));
        assert!(output.contains("assert_eq!(x, 42);"));
    }
}
