use crate::core::nt_core_experience::handler_tier::{HandlerRegistry, LoadTier};
use crate::core::nt_core_experience::hypothesis_tree::HypothesisTree;
use crate::core::nt_core_hcube::vsa_quantized::QuantizedVSA;
use serde::{Deserialize, Serialize};

/// Unified event type for cross-engine evolution coordination.
/// Each variant carries VSA-encoded payloads for consciousness fusion.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub enum EvolutionEvent {
    WeaknessFound {
        handler: String,
        severity: f64,
        pattern: String,
    },
    HarnessProposed {
        target: String,
        kind: String,
        confidence: f64,
    },
    HarnessValidated {
        target: String,
        accepted: bool,
    },
    NoveltyDetected {
        step: u64,
        novelty: f64,
    },
    PolicyUpdated {
        old_hash: Vec<u8>,
        new_hash: Vec<u8>,
    },
    MutationApplied {
        handler: String,
        mutation: String,
        success: bool,
    },
    WritebackApplied {
        target: String,
        delta: f64,
    },
    CycleTick(u64),
    Degradation {
        handler: String,
        reason: String,
    },
}

/// A handler-level mutation for the EvolutionCoordinator to apply against the HandlerRegistry.
/// Unlike MutationOp (code-level), these operate on handler lifecycle (add/remove/tier).
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum Mutation {
    AddHandler { name: String, tier: LoadTier },
    RemoveHandler { name: String },
    ChangeTier { name: String, tier: LoadTier },
}

/// Lightweight coordinator that bridges the 4 evolution subsystems:
/// SelfHarness → EGPO → SEAL → DGM-H → SelfHarness (closed loop)
/// Runs inside ConsciousnessIntegration via evolution_coordinator_tick.
#[derive(Debug, Clone)]
pub struct EvolutionCoordinator {
    event_log: Vec<EvolutionEvent>,
    max_events: usize,

    /// Bridge state: SelfHarness → EGPO (explore where weaknesses cluster)
    pub exploration_targets: Vec<String>,
    /// Bridge state: EGPO → SEAL (high-novelty regions need mutation candidates)
    pub mutation_candidates: Vec<String>,
    /// Bridge state: SEAL → SelfHarness (re-validate mutated handlers)
    pub revalidation_queue: Vec<String>,

    pub total_weaknesses: u64,
    pub total_mutations: u64,
    pub total_bridges: u64,
    pub cycle: u64,
    pub enabled: bool,

    pub last_weakness_cycle: u64,
    pub last_novelty_cycle: u64,
    pub last_mutation_cycle: u64,
    pub pending_proposals: Vec<String>,
    pub active_mutations: Vec<String>,
    pub bridge_result: String,

    /// Queued handler-level mutations to be drained by mutation_apply().
    pub pending_mutations: Vec<Mutation>,

    /// HypothesisTree wired into evolution pipeline for MCTS-based proposal generation.
    pub hypothesis_tree: Option<HypothesisTree>,
    /// Total proposals generated by hypothesis tree incorporation across all cycles.
    pub hypothesis_proposals_generated: u64,

    /// VSA representation of the current cross-engine bridge state.
    pub vsa_bridge_state: Option<Vec<u8>>,
    /// VSA vectors for exploration targets (for EGPO similarity matching).
    pub exploration_vsa: Vec<(String, Vec<u8>)>,
    /// VSA vectors for mutation candidates.
    pub mutation_vsa: Vec<(String, Vec<u8>)>,
}

fn stable_hash(texts: &[&str]) -> u64 {
    let mut h = 0u64;
    for t in texts {
        for &b in t.as_bytes() {
            h = h.wrapping_mul(31).wrapping_add(b as u64);
        }
    }
    h
}

impl Default for EvolutionCoordinator {
    fn default() -> Self {
        Self::new()
    }
}

impl EvolutionCoordinator {
    pub fn new() -> Self {
        Self {
            event_log: Vec::with_capacity(100),
            max_events: 1000,
            exploration_targets: Vec::new(),
            mutation_candidates: Vec::new(),
            revalidation_queue: Vec::new(),
            total_weaknesses: 0,
            total_mutations: 0,
            total_bridges: 0,
            cycle: 0,
            enabled: true,
            last_weakness_cycle: 0,
            last_novelty_cycle: 0,
            last_mutation_cycle: 0,
            pending_proposals: Vec::new(),
            active_mutations: Vec::new(),
            bridge_result: String::new(),
            pending_mutations: Vec::new(),
            hypothesis_tree: None,
            hypothesis_proposals_generated: 0,
            vsa_bridge_state: None,
            exploration_vsa: Vec::new(),
            mutation_vsa: Vec::new(),
        }
    }

    /// Builder: attach a HypothesisTree for MCTS-based evolution proposal generation.
    pub fn with_hypothesis_tree(mut self, tree: HypothesisTree) -> Self {
        self.hypothesis_tree = Some(tree);
        self
    }

    /// Use the internal HypothesisTree to generate evolution proposals.
    /// Searches the tree for best candidate hypotheses, creates HarnessProposed events,
    /// queues Mutation entries, and marks hypotheses as incorporated.
    /// Returns the number of proposals generated.
    pub fn incorporate_hypothesis_tree(&mut self) -> usize {
        let candidates = {
            let tree = match self.hypothesis_tree.as_mut() {
                Some(t) => t,
                None => return 0,
            };
            let cand = tree.search(10);
            if cand.is_empty() {
                return 0;
            }
            for (_idd, name, dev_score, test_score) in &cand {
                let confidence = test_score.max(*dev_score);
                self.push(EvolutionEvent::HarnessProposed {
                    target: name.clone(),
                    kind: format!("hypothesis:score={:.2}", confidence),
                    confidence,
                });
                self.mutation_candidates.push(name.clone());
                self.total_mutations += 1;
                self.queue_mutation(Mutation::AddHandler {
                    name: name.clone(),
                    tier: crate::core::nt_core_experience::handler_tier::LoadTier::Warm,
                });
            }
            cand
        };
        for (id, ..) in &candidates {
            if let Some(tree) = self.hypothesis_tree.as_mut() {
                tree.incorporate(*id);
            }
        }
        let count = candidates.len();
        self.hypothesis_proposals_generated += count as u64;
        log::info!(
            "EVO_COORD: hypothesis_tree generated {} proposals (total: {})",
            count,
            self.hypothesis_proposals_generated
        );
        count
    }

    /// Main coordination tick. Called every ~30 consciousness cycles.
    /// Checks bridge queues and triggers cross-system actions.
    /// Returns actionable instructions for downstream consumers.
    pub fn tick(&mut self) -> String {
        self.cycle += 1;
        if !self.enabled {
            return "coordinator:disabled".into();
        }

        let mut actions = Vec::new();

        // Bridge 1: SelfHarness → EGPO — promote weakness patterns to exploration targets
        if !self.exploration_targets.is_empty() {
            let count = self.exploration_targets.len();
            actions.push(format!("explore:{}_targets", count));
            self.total_bridges += count as u64;
            self.last_weakness_cycle = self.cycle;
            self.exploration_targets.clear();
            if !self.exploration_vsa.is_empty() {
                let vsa_clone: Vec<Vec<u8>> = self
                    .exploration_vsa
                    .iter()
                    .map(|(_, v)| v.clone())
                    .collect();
                let refs: Vec<&[u8]> = vsa_clone.iter().map(|v| v.as_slice()).collect();
                self.vsa_bridge_state = Some(QuantizedVSA::bundle(&refs));
                self.exploration_vsa.clear();
            }
        }

        // Bridge 2: EGPO → SEAL — high novelty → mutation candidates
        if !self.mutation_candidates.is_empty() {
            let count = self.mutation_candidates.len();
            actions.push(format!("mutate:{}_candidates", count));
            self.total_bridges += count as u64;
            self.last_novelty_cycle = self.cycle;
            self.mutation_candidates.clear();
            if !self.mutation_vsa.is_empty() {
                let vsa_clone: Vec<Vec<u8>> =
                    self.mutation_vsa.iter().map(|(_, v)| v.clone()).collect();
                let refs: Vec<&[u8]> = vsa_clone.iter().map(|v| v.as_slice()).collect();
                self.vsa_bridge_state = Some(QuantizedVSA::bundle(&refs));
                self.mutation_vsa.clear();
            }
        }

        // (mutation_apply is called by handle_evolution_coordinator_tick
        //  after tick(), since it needs HandlerRegistry access)

        // Bridge 3: SEAL → SelfHarness — re-validate mutated handlers
        if !self.revalidation_queue.is_empty() {
            let count = self.revalidation_queue.len();
            actions.push(format!("revalidate:{}_handlers", count));
            self.total_bridges += count as u64;
            self.last_mutation_cycle = self.cycle;
            self.revalidation_queue.clear();
        }

        self.prune_events();
        let summary = if actions.is_empty() {
            "coordinator:idle".into()
        } else {
            format!("coordinator:{}", actions.join("|"))
        };
        self.push(EvolutionEvent::CycleTick(self.cycle));
        summary
    }

    /// Called by SelfHarness when a weakness is mined
    pub fn report_weakness(&mut self, handler: &str, severity: f64, pattern: &str) {
        self.total_weaknesses += 1;
        self.exploration_targets.push(handler.to_string());
        let seed = stable_hash(&[handler, pattern]);
        let vsa = QuantizedVSA::seeded_random(seed, 64);
        self.exploration_vsa.push((handler.to_string(), vsa));
        self.push(EvolutionEvent::WeaknessFound {
            handler: handler.into(),
            severity,
            pattern: pattern.into(),
        });
    }

    /// Called by EGPO when a novelty spike is detected
    pub fn report_novelty(&mut self, step: u64, novelty: f64) {
        let label = format!("novelty_{}", step);
        self.mutation_candidates.push(label.clone());
        let seed = stable_hash(&["novelty", &step.to_string()]);
        let vsa = QuantizedVSA::seeded_random(seed, 64);
        self.mutation_vsa.push((label, vsa));
        self.push(EvolutionEvent::NoveltyDetected { step, novelty });
    }

    /// Called by SEAL when a mutation is applied
    pub fn report_mutation(&mut self, handler: &str, mutation: &str, success: bool) {
        self.total_mutations += 1;
        self.revalidation_queue.push(handler.to_string());
        self.push(EvolutionEvent::MutationApplied {
            handler: handler.into(),
            mutation: mutation.into(),
            success,
        });
    }

    /// Called by DGM-H or any external writeback
    pub fn report_writeback(&mut self, target: &str, delta: f64) {
        self.push(EvolutionEvent::WritebackApplied {
            target: target.into(),
            delta,
        });
    }

    /// Called when a handler degrades
    pub fn report_degradation(&mut self, handler: &str, reason: &str) {
        self.exploration_targets.push(handler.to_string());
        let seed = stable_hash(&[handler, reason]);
        let vsa = QuantizedVSA::seeded_random(seed, 64);
        self.exploration_vsa.push((handler.to_string(), vsa));
        self.push(EvolutionEvent::Degradation {
            handler: handler.into(),
            reason: reason.into(),
        });
    }

    /// Bridges SelfHarness weaknesses → EGPO exploration targets,
    /// EGPO novelty → SEAL mutation candidates, and
    /// mutation outcomes → SelfHarness revalidation queue.
    /// Drains all bridge queues and returns a summary of actions taken.
    pub fn process_bridge(&mut self, cycle: u64) -> String {
        let mut actions = Vec::new();

        if !self.exploration_targets.is_empty() {
            actions.push(format!("explore:{}", self.exploration_targets.len()));
            self.last_weakness_cycle = cycle;
            self.total_bridges += self.exploration_targets.len() as u64;
            self.exploration_targets.clear();
            if !self.exploration_vsa.is_empty() {
                let vsa_clone: Vec<Vec<u8>> = self
                    .exploration_vsa
                    .iter()
                    .map(|(_, v)| v.clone())
                    .collect();
                let refs: Vec<&[u8]> = vsa_clone.iter().map(|v| v.as_slice()).collect();
                self.vsa_bridge_state = Some(QuantizedVSA::bundle(&refs));
                self.exploration_vsa.clear();
            }
        }

        if !self.mutation_candidates.is_empty() {
            actions.push(format!("mutate:{}", self.mutation_candidates.len()));
            self.last_novelty_cycle = cycle;
            self.total_bridges += self.mutation_candidates.len() as u64;
            self.mutation_candidates.clear();
            if !self.mutation_vsa.is_empty() {
                let vsa_clone: Vec<Vec<u8>> =
                    self.mutation_vsa.iter().map(|(_, v)| v.clone()).collect();
                let refs: Vec<&[u8]> = vsa_clone.iter().map(|v| v.as_slice()).collect();
                self.vsa_bridge_state = Some(QuantizedVSA::bundle(&refs));
                self.mutation_vsa.clear();
            }
        }

        if !self.revalidation_queue.is_empty() {
            actions.push(format!("revalidate:{}", self.revalidation_queue.len()));
            self.last_mutation_cycle = cycle;
            self.total_bridges += self.revalidation_queue.len() as u64;
            self.revalidation_queue.clear();
        }

        if !self.pending_mutations.is_empty() {
            actions.push(format!("apply:{}_pending", self.pending_mutations.len()));
        }
        self.bridge_result = actions.join("|");
        self.push(EvolutionEvent::CycleTick(cycle));
        self.bridge_result.clone()
    }

    /// Queue a handler-level mutation for later application.
    pub fn queue_mutation(&mut self, mutation: Mutation) {
        self.pending_mutations.push(mutation);
    }

    /// Drain all pending mutations and apply them to the HandlerRegistry.
    /// Returns the number of successfully applied mutations.
    /// Failures are logged but do not halt processing of remaining mutations.
    pub fn mutation_apply(&mut self, registry: &mut HandlerRegistry) -> usize {
        let mutations: Vec<Mutation> = self.pending_mutations.drain(..).collect();
        if mutations.is_empty() {
            return 0;
        }
        let mut success_count = 0usize;
        let total = mutations.len();
        for m in &mutations {
            let label = match m {
                Mutation::AddHandler { .. } => "AddHandler",
                Mutation::RemoveHandler { .. } => "RemoveHandler",
                Mutation::ChangeTier { .. } => "ChangeTier",
            };
            let name = match m {
                Mutation::AddHandler { ref name, .. }
                | Mutation::RemoveHandler { ref name, .. }
                | Mutation::ChangeTier { ref name, .. } => name.clone(),
            };
            match m {
                Mutation::AddHandler { ref name, tier } => {
                    if registry.contains(name) {
                        log::warn!(
                            "EVO_COORD: AddHandler skipped, already registered: {}",
                            name
                        );
                        continue;
                    }
                    registry.register(name, *tier);
                    registry.mark_loaded(name);
                    success_count += 1;
                    log::info!("EVO_COORD: AddHandler {} {:?}", name, tier);
                }
                Mutation::RemoveHandler { ref name } => {
                    if !registry.contains(name) {
                        log::warn!("EVO_COORD: RemoveHandler skipped, not found: {}", name);
                        continue;
                    }
                    registry.unregister(name);
                    success_count += 1;
                    log::info!("EVO_COORD: RemoveHandler {}", name);
                }
                Mutation::ChangeTier { ref name, tier } => {
                    if !registry.contains(name) {
                        log::warn!("EVO_COORD: ChangeTier skipped, not found: {}", name);
                        continue;
                    }
                    registry.set_tier(name, *tier);
                    success_count += 1;
                    log::info!("EVO_COORD: ChangeTier {} -> {:?}", name, tier);
                }
            }
            self.total_mutations += 1;
            self.push(EvolutionEvent::MutationApplied {
                handler: name.clone(),
                mutation: label.to_string(),
                success: true,
            });
            self.revalidation_queue.push(name);
        }
        let failed = total - success_count;
        if failed > 0 {
            log::warn!(
                "EVO_COORD: mutation_apply {}/{} succeeded, {} failed",
                success_count,
                total,
                failed
            );
        } else if success_count > 0 {
            log::debug!(
                "EVO_COORD: mutation_apply {} mutations applied",
                success_count
            );
        }
        success_count
    }

    pub fn stats(&self) -> String {
        format!(
            "coordinator:weak={} mut={} bridges={} cycle={} log={}|queues:explore={} mutate={} reval={} pending={}|last_cycles:weak={} novel={} mut={}|bridge:{}|hypothesis_tree={} proposals={}|vsa:{}",
            self.total_weaknesses,
            self.total_mutations,
            self.total_bridges,
            self.cycle,
            self.event_log.len(),
            self.exploration_targets.len(),
            self.mutation_candidates.len(),
            self.revalidation_queue.len(),
            self.pending_mutations.len(),
            self.last_weakness_cycle,
            self.last_novelty_cycle,
            self.last_mutation_cycle,
            self.bridge_result,
            self.hypothesis_tree.as_ref().map(|t| t.nodes.len()).unwrap_or(0),
            self.hypothesis_proposals_generated,
            self.vsa_bridge_state.is_some(),
        )
    }

    pub fn recent_events(&self, n: usize) -> &[EvolutionEvent] {
        let start = self.event_log.len().saturating_sub(n);
        &self.event_log[start..]
    }

    fn push(&mut self, event: EvolutionEvent) {
        self.event_log.push(event);
        if self.event_log.len() > self.max_events {
            self.event_log.remove(0);
        }
    }

    fn prune_events(&mut self) {
        if self.event_log.len() > self.max_events {
            let excess = self.event_log.len() - self.max_events;
            self.event_log.drain(0..excess);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::nt_core_experience::handler_tier::{HandlerRegistry, LoadTier};

    #[test]
    fn test_coordinator_new_is_idle() {
        let c = EvolutionCoordinator::new();
        assert!(c.enabled);
        assert!(c.event_log.is_empty());
    }

    #[test]
    fn test_coordinator_tick_idle() {
        let mut c = EvolutionCoordinator::new();
        let r = c.tick();
        assert!(r.contains("idle") || r.contains("evo_coord"));
    }

    #[test]
    fn test_weakness_triggers_exploration() {
        let mut c = EvolutionCoordinator::new();
        c.report_weakness("test_handler", 0.8, "low coverage");
        assert_eq!(c.exploration_targets.len(), 1);
        assert!(c.exploration_targets[0] == "test_handler");
    }

    #[test]
    fn test_novelty_triggers_mutation() {
        let mut c = EvolutionCoordinator::new();
        c.report_novelty(42, 0.95);
        assert_eq!(c.mutation_candidates.len(), 1);
    }

    #[test]
    fn test_mutation_triggers_revalidation() {
        let mut c = EvolutionCoordinator::new();
        c.report_mutation("handler_x", "rewrite_fallback", true);
        assert_eq!(c.revalidation_queue.len(), 1);
        assert!(c.revalidation_queue[0] == "handler_x");
    }

    #[test]
    fn test_tick_clears_bridges() {
        let mut c = EvolutionCoordinator::new();
        c.report_weakness("a", 0.5, "low");
        c.report_weakness("b", 0.6, "high_latency");
        let r = c.tick();
        assert!(r.contains("explore:2_targets"));
        assert!(c.exploration_targets.is_empty());
    }

    #[test]
    fn test_stats_format() {
        let mut c = EvolutionCoordinator::new();
        c.report_weakness("x", 0.5, "p");
        c.report_mutation("x", "fix", true);
        c.tick();
        let s = c.stats();
        assert!(s.contains("weak="));
        assert!(s.contains("bridges="));
    }

    #[test]
    fn test_disabled_returns_immediately() {
        let mut c = EvolutionCoordinator::new();
        c.enabled = false;
        let r = c.tick();
        assert_eq!(r, "coordinator:disabled");
    }

    #[test]
    fn test_event_log_bounded() {
        let mut c = EvolutionCoordinator::new();
        c.max_events = 5;
        for i in 0..10 {
            c.report_weakness(&format!("h{}", i), 0.5, "test");
        }
        assert!(c.event_log.len() <= 5);
    }

    #[test]
    fn test_recent_events() {
        let mut c = EvolutionCoordinator::new();
        c.report_weakness("a", 0.5, "p1");
        c.report_weakness("b", 0.6, "p2");
        let recent = c.recent_events(1);
        assert_eq!(recent.len(), 1);
        if let EvolutionEvent::WeaknessFound { ref handler, .. } = recent[0] {
            assert_eq!(handler, "b");
        } else {
            panic!("expected WeaknessFound");
        }
    }

    #[test]
    fn test_bridge_processing() {
        let mut coord = EvolutionCoordinator::new();
        coord.report_weakness("test_handler", 0.8, "high_latency");
        coord.report_novelty(42, 0.7);
        coord.report_mutation("handler_a", "rewrite", true);

        let result = coord.process_bridge(100);
        assert!(
            result.contains("explore:1"),
            "expected explore:1 in result, got: {}",
            result
        );
        assert!(
            result.contains("mutate:1"),
            "expected mutate:1 in result, got: {}",
            result
        );
        assert!(
            result.contains("revalidate:1"),
            "expected revalidate:1 in result, got: {}",
            result
        );

        assert_eq!(coord.last_weakness_cycle, 100);
        assert_eq!(coord.last_novelty_cycle, 100);
        assert_eq!(coord.last_mutation_cycle, 100);

        let result2 = coord.process_bridge(101);
        assert_eq!(
            result2, "",
            "expected empty after draining, got: {}",
            result2
        );
    }

    #[test]
    fn test_stats_contains_bridge_info() {
        let mut c = EvolutionCoordinator::new();
        c.report_weakness("x", 0.5, "p");
        c.report_mutation("x", "fix", true);
        c.process_bridge(50);
        let s = c.stats();
        assert!(s.contains("queues:"), "stats missing queues: {}", s);
        assert!(
            s.contains("last_cycles:"),
            "stats missing last_cycles: {}",
            s
        );
        assert!(s.contains("bridge:"), "stats missing bridge: {}", s);
    }

    #[test]
    fn test_queue_mutation_appends() {
        let mut c = EvolutionCoordinator::new();
        assert!(c.pending_mutations.is_empty());
        c.queue_mutation(Mutation::AddHandler {
            name: "test_handler".into(),
            tier: LoadTier::Hot,
        });
        assert_eq!(c.pending_mutations.len(), 1);
    }

    #[test]
    fn test_mutation_apply_add_handler() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        c.queue_mutation(Mutation::AddHandler {
            name: "new_hot_handler".into(),
            tier: LoadTier::Hot,
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 1);
        assert!(r.contains("new_hot_handler"));
        assert_eq!(r.tier("new_hot_handler"), LoadTier::Hot);
    }

    #[test]
    fn test_mutation_apply_remove_handler() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        r.register("to_remove", LoadTier::Warm);
        c.queue_mutation(Mutation::RemoveHandler {
            name: "to_remove".into(),
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 1);
        assert!(!r.contains("to_remove"));
    }

    #[test]
    fn test_mutation_apply_change_tier() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        r.register("mutable", LoadTier::Cold);
        c.queue_mutation(Mutation::ChangeTier {
            name: "mutable".into(),
            tier: LoadTier::Hot,
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 1);
        assert_eq!(r.tier("mutable"), LoadTier::Hot);
    }

    #[test]
    fn test_mutation_apply_skips_duplicate_add() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        r.register("existing", LoadTier::Warm);
        c.queue_mutation(Mutation::AddHandler {
            name: "existing".into(),
            tier: LoadTier::Hot,
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 0, "should skip duplicate add");
        assert_eq!(r.tier("existing"), LoadTier::Warm, "tier unchanged");
    }

    #[test]
    fn test_mutation_apply_skips_missing_remove() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        c.queue_mutation(Mutation::RemoveHandler {
            name: "nonexistent".into(),
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 0, "should skip missing remove");
    }

    #[test]
    fn test_mutation_apply_skips_missing_change_tier() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        c.queue_mutation(Mutation::ChangeTier {
            name: "nope".into(),
            tier: LoadTier::Hot,
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 0, "should skip missing change tier");
    }

    #[test]
    fn test_mutation_apply_multiple() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        r.register("keep", LoadTier::Cold);
        c.queue_mutation(Mutation::ChangeTier {
            name: "keep".into(),
            tier: LoadTier::Hot,
        });
        c.queue_mutation(Mutation::AddHandler {
            name: "new_a".into(),
            tier: LoadTier::Warm,
        });
        c.queue_mutation(Mutation::AddHandler {
            name: "new_b".into(),
            tier: LoadTier::Warm,
        });
        c.queue_mutation(Mutation::RemoveHandler {
            name: "nonexistent".into(),
        });
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 3, "3/4 should succeed; nonexistent skip");
        assert_eq!(r.tier("keep"), LoadTier::Hot);
        assert!(r.contains("new_a"));
        assert!(r.contains("new_b"));
        assert!(!r.contains("nonexistent"));
    }

    #[test]
    fn test_mutation_apply_drains_queue() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        c.queue_mutation(Mutation::AddHandler {
            name: "drain_test".into(),
            tier: LoadTier::Hot,
        });
        c.mutation_apply(&mut r);
        assert!(c.pending_mutations.is_empty(), "queue should be drained");
    }

    #[test]
    fn test_queue_and_apply_roundtrip() {
        let mut c = EvolutionCoordinator::new();
        let mut r = HandlerRegistry::new();
        let names = ["alpha", "beta", "gamma"];
        for (i, name) in names.iter().enumerate() {
            let tier = if i == 0 {
                LoadTier::Hot
            } else if i == 1 {
                LoadTier::Warm
            } else {
                LoadTier::Cold
            };
            c.queue_mutation(Mutation::AddHandler {
                name: name.to_string(),
                tier,
            });
        }
        assert_eq!(c.pending_mutations.len(), 3);
        let n = c.mutation_apply(&mut r);
        assert_eq!(n, 3);
        assert_eq!(r.count(), 3);
        assert!(c.pending_mutations.is_empty());
    }

    #[test]
    fn test_stats_includes_pending_mutations() {
        let mut c = EvolutionCoordinator::new();
        c.queue_mutation(Mutation::AddHandler {
            name: "x".into(),
            tier: LoadTier::Hot,
        });
        let s = c.stats();
        assert!(
            s.contains("pending=1"),
            "stats should include pending=1, got: {}",
            s
        );
    }

    #[test]
    fn test_process_bridge_reports_pending_mutations() {
        let mut c = EvolutionCoordinator::new();
        c.queue_mutation(Mutation::AddHandler {
            name: "x".into(),
            tier: LoadTier::Hot,
        });
        let r = c.process_bridge(1);
        assert!(r.contains("apply:"), "bridge should report pending: {}", r);
    }
}
