// FolderEngine - 智能文件夹 (Fusion Architecture ADR-002)
// 融合: Nicegram 自定义 Tabs + Swiftgram Folders 管理 + Turrit 侧边/底部导航
// 独有: AI 自动文件夹 (E8 语义聚类) + 隐藏未使用 Tab + 记住上次打开的文件夹

import Foundation
import Combine
import SwiftUI

// MARK: - Folder Models

public struct ChatFolder: Identifiable, Equatable, Codable {
    public let id: UUID
    public var name: String
    public var icon: String
    public var isAutoGenerated: Bool
    public var chatIDs: Set<Int64>
    public var isHidden: Bool
    
    public init(id: UUID = UUID(), name: String, icon: String, isAutoGenerated: Bool = false, chatIDs: Set<Int64> = [], isHidden: Bool = false) {
        self.id = id
        self.name = name
        self.icon = icon
        self.isAutoGenerated = isAutoGenerated
        self.chatIDs = chatIDs
        self.isHidden = isHidden
    }
}

// MARK: - Folder Engine

@MainActor
public final class FolderEngine: ObservableObject {
    @Published public var folders: [ChatFolder] = []
    @Published public var selectedFolderID: UUID?
    @Published public var navigationMode: NavigationMode = .bottom
    @Published public var rememberLastFolder = true
    
    private let aiHub = AIHub.shared
    
    public enum NavigationMode: String, CaseIterable {
        case bottom = "Bottom Tabs"
        case side = "Side Bar"
    }
    
    public init() {
        loadFolders()
        restoreLastFolder()
    }
    
    private func loadFolders() {
        // 修复: 从 UserDefaults 恢复用户自建/修改的文件夹（此前每次从 mock 重建，增删/显隐全丢）
        let defaults = UserDefaults.standard
        if let data = defaults.data(forKey: "chat_folders"),
           let saved = try? JSONDecoder().decode([ChatFolder].self, from: data),
           !saved.isEmpty {
            folders = saved
            return
        }
        // 首次启动: mock 播种
        folders = [
            ChatFolder(name: "All Chats", icon: "bubble.left.and.bubble.right.fill"),
            ChatFolder(name: "Personal", icon: "person.fill"),
            ChatFolder(name: "Work", icon: "briefcase.fill"),
            ChatFolder(name: "Groups", icon: "person.3.fill"),
            ChatFolder(name: "Channels", icon: "megaphone.fill"),
            ChatFolder(name: "Bots", icon: "cpu.fill"),
            ChatFolder(name: "Favorites", icon: "star.fill"),
        ]
        saveFolders()
    }
    
    /// 持久化文件夹（修复: 增删/显隐/重命名全部落盘，重启不丢）
    public func saveFolders() {
        if let data = try? JSONEncoder().encode(folders) {
            UserDefaults.standard.set(data, forKey: "chat_folders")
        }
    }
    
    private func restoreLastFolder() {
        if rememberLastFolder,
           let savedID = UserDefaults.standard.string(forKey: "last_folder_id"),
           let uuid = UUID(uuidString: savedID) {
            // 修复: 持久化文件夹存在性 guard — 被删除的文件夹 id 不恢复选中
            if folders.contains(where: { $0.id == uuid }) {
                selectedFolderID = uuid
            }
        }
    }
    
    public func selectFolder(_ folder: ChatFolder) {
        selectedFolderID = folder.id
        if rememberLastFolder {
            UserDefaults.standard.set(folder.id.uuidString, forKey: "last_folder_id")
        }
    }
    
    /// 取消选中（修复: 无选中状态支持，避免"选中后无法回到 All"）
    public func deselectFolder() {
        selectedFolderID = nil
        if rememberLastFolder {
            UserDefaults.standard.removeObject(forKey: "last_folder_id")
        }
    }
    
    public func toggleFolderVisibility(_ folder: ChatFolder) {
        if let index = folders.firstIndex(where: { $0.id == folder.id }) {
            folders[index].isHidden.toggle()
            saveFolders()
        }
    }
    
    public func createFolder(name: String, icon: String) {
        folders.append(ChatFolder(name: name, icon: icon))
        saveFolders()
    }
    
    public func deleteFolder(_ folder: ChatFolder) {
        folders.removeAll { $0.id == folder.id }
        if selectedFolderID == folder.id {
            selectedFolderID = nil
        }
        saveFolders()
    }
    
    // MARK: - AI Auto-Classification
    
    public func autoClassifyChats(_ chats: [ChatListItem]) async {
        // Use E8 to semantically cluster chats into folders
        // Fallback: rule-based classification
        for chat in chats {
            let folderName = classifyChat(chat)
            if let index = folders.firstIndex(where: { $0.name == folderName }) {
                folders[index].chatIDs.insert(chat.id)
            }
        }
        saveFolders()
    }
    
    private func classifyChat(_ chat: ChatListItem) -> String {
        // 修复: 用 ChatKind 语义分类（此前标题 contains 匹配 = ChatListUI 已废弃的脆弱模式复活）
        switch chat.kind {
        case .bot: return "Bots"
        case .channel: return "Channels"
        case .group: return "Groups"
        case .personal:
            if chat.isPinned { return "Favorites" }
            return "Personal"
        }
    }
    
    public var visibleFolders: [ChatFolder] {
        folders.filter { !$0.isHidden }
    }
    
    public func chatsForFolder(_ folder: ChatFolder, allChats: [ChatListItem]) -> [ChatListItem] {
        if folder.name == "All Chats" { return allChats }
        // 修复: 默认文件夹无 chatIDs 时按 kind 语义 fallback（此前默认文件夹恒返回空列表）
        if folder.chatIDs.isEmpty {
            switch folder.name {
            case "Personal": return allChats.filter { $0.kind == .personal }
            case "Work": return allChats.filter { $0.title.localizedCaseInsensitiveContains("work") || $0.kind == .personal }
            case "Groups": return allChats.filter { $0.kind == .group }
            case "Channels": return allChats.filter { $0.kind == .channel }
            case "Bots": return allChats.filter { $0.kind == .bot }
            case "Favorites": return allChats.filter { $0.isPinned }
            default: return []
            }
        }
        return allChats.filter { folder.chatIDs.contains($0.id) }
    }
}

// MARK: - Folder Management View

public struct FolderManagementView: View {
    @StateObject private var engine = FolderEngine()
    @State private var showNewFolder = false
    @State private var newFolderName = ""
    
    public init() {}
    
    public var body: some View {
        Form {
            Section("Navigation") {
                Picker("Navigation Mode", selection: $engine.navigationMode) {
                    ForEach(FolderEngine.NavigationMode.allCases, id: \.self) { mode in
                        Text(mode.rawValue).tag(mode)
                    }
                }
                Toggle("Remember last folder", isOn: $engine.rememberLastFolder)
            }
            
            Section("Folders") {
                ForEach(engine.folders) { folder in
                    HStack {
                        Image(systemName: folder.icon)
                            .foregroundColor(NeoTrixTheme.Colors.accent)
                            .frame(width: 28)
                        Text(folder.name)
                        if folder.isAutoGenerated {
                            Text("AI")
                                .font(.caption2.bold())
                                .padding(.horizontal, 6)
                                .padding(.vertical, 2)
                                .background(NeoTrixTheme.Colors.accentSecondary.opacity(0.2))
                                .clipShape(Capsule())
                        }
                        Spacer()
                        Button {
                            engine.toggleFolderVisibility(folder)
                        } label: {
                            Image(systemName: folder.isHidden ? "eye.slash.fill" : "eye.fill")
                                .foregroundColor(folder.isHidden ? .secondary : NeoTrixTheme.Colors.accent)
                        }
                        .buttonStyle(.plain)
                    }
                }
                .onDelete { indexSet in
                    for index in indexSet {
                        engine.deleteFolder(engine.folders[index])
                    }
                }
            }
            
            Section {
                Button {
                    showNewFolder = true
                } label: {
                    Label("New Folder", systemImage: "plus.circle.fill")
                }
            }
        }
        .navigationTitle("Chat Folders")
        .alert("New Folder", isPresented: $showNewFolder) {
            TextField("Folder name", text: $newFolderName)
            Button("Create") {
                engine.createFolder(name: newFolderName, icon: "folder.fill")
                newFolderName = ""
            }
            Button("Cancel", role: .cancel) {}
        }
    }
}