use std::collections::VecDeque;

/// A snapshot of meta-cognitive KPIs at a point in time
#[derive(Debug, Clone)]
pub struct MetaKPISnapshot {
    pub timestamp_ms: i64,
    pub meta_accuracy: f64,
    pub adaptation_rate: f64,
    pub hallucination_rate: f64,
    pub cognitive_load: f64,
    pub negentropy_rate: f64,
    pub composite_score: f64,
}

/// Detects gaps/declines in meta-cognitive dimensions
#[derive(Debug, Clone)]
pub struct MetaGapReport {
    pub timestamp_ms: i64,
    pub declining_dimensions: Vec<(String, f64, f64)>,
    pub gaps: Vec<(String, f64, String)>,
    pub overall_health: f64,
}

/// A self-directed improvement goal generated by the system
#[derive(Debug, Clone)]
pub struct SelfDirectedGoal {
    pub id: u64,
    pub created_ms: i64,
    pub target_dimension: String,
    pub current_value: f64,
    pub target_value: f64,
    pub gap: f64,
    pub strategy: String,
    pub status: GoalStatus,
}

#[derive(Debug, Clone, PartialEq)]
pub enum GoalStatus {
    Proposed,
    InProgress,
    Achieved { achieved_ms: i64 },
    Abandoned { reason: String },
}

/// Persistent repository of meta-cognitive KPIs
#[derive(Debug, Clone)]
pub struct MetaKPIRepository {
    pub snapshots: VecDeque<MetaKPISnapshot>,
    pub goals: VecDeque<SelfDirectedGoal>,
    max_snapshots: usize,
    max_goals: usize,
    next_goal_id: u64,
}

impl MetaKPIRepository {
    pub fn new() -> Self {
        Self {
            snapshots: VecDeque::with_capacity(10000),
            goals: VecDeque::with_capacity(500),
            max_snapshots: 10000,
            max_goals: 500,
            next_goal_id: 1,
        }
    }

    pub fn record_snapshot(&mut self, snapshot: MetaKPISnapshot) {
        if self.snapshots.len() >= self.max_snapshots {
            self.snapshots.pop_front();
        }
        self.snapshots.push_back(snapshot);
    }

    pub fn detect_gaps(&self, lookback: usize) -> MetaGapReport {
        if self.snapshots.len() < 2 {
            return MetaGapReport {
                timestamp_ms: 0,
                declining_dimensions: vec![],
                gaps: vec![],
                overall_health: 1.0,
            };
        }

        let lookback = lookback.min(self.snapshots.len());
        let recent: Vec<&MetaKPISnapshot> = self.snapshots.iter().rev().take(lookback).collect();
        let first = recent.last().unwrap();
        let last = recent.first().unwrap();

        let mut declining = Vec::new();
        let mut gaps = Vec::new();

        let dims = [
            (
                "meta_accuracy",
                first.meta_accuracy,
                last.meta_accuracy,
                0.8,
            ),
            (
                "adaptation_rate",
                first.adaptation_rate,
                last.adaptation_rate,
                0.6,
            ),
            (
                "hallucination_rate",
                first.hallucination_rate,
                last.hallucination_rate,
                0.1,
            ),
            (
                "negentropy_rate",
                first.negentropy_rate,
                last.negentropy_rate,
                0.05,
            ),
        ];

        for (name, prev, curr, threshold) in dims {
            let delta = curr - prev;
            if delta < -0.01 {
                declining.push((name.to_string(), curr, prev));
                let gap_size = (threshold - curr).max(0.0);
                let rec = if gap_size > 0.2 {
                    format!("CRITICAL: {} needs immediate attention", name)
                } else if gap_size > 0.1 {
                    format!("WARN: {} is declining", name)
                } else {
                    format!("MONITOR: {} slightly below threshold", name)
                };
                gaps.push((name.to_string(), gap_size, rec));
            }
        }

        let health = 1.0 - (declining.len() as f64 * 0.1).min(1.0);

        MetaGapReport {
            timestamp_ms: last.timestamp_ms,
            declining_dimensions: declining,
            gaps,
            overall_health: health,
        }
    }

    pub fn propose_goal(&mut self, report: &MetaGapReport) -> Option<SelfDirectedGoal> {
        let biggest = report
            .gaps
            .iter()
            .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal))?;

        let id = self.next_goal_id;
        let goal = SelfDirectedGoal {
            id,
            created_ms: report.timestamp_ms,
            target_dimension: biggest.0.clone(),
            current_value: 0.0,
            target_value: 0.8,
            gap: biggest.1,
            strategy: "increase".to_string(),
            status: GoalStatus::Proposed,
        };

        if self.goals.len() >= self.max_goals {
            self.goals.pop_front();
        }
        self.goals.push_back(goal.clone());
        self.next_goal_id += 1;
        Some(goal)
    }

    pub fn update_goal_status(&mut self, id: u64, status: GoalStatus) {
        if let Some(goal) = self.goals.iter_mut().find(|g| g.id == id) {
            goal.status = status;
        }
    }

    pub fn stats(&self) -> String {
        format!(
            "MetaKPIRepository: {} snapshots, {} goals, health={:.2}",
            self.snapshots.len(),
            self.goals.len(),
            self.detect_gaps(10).overall_health
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_snapshot(
        meta_accuracy: f64,
        adaptation_rate: f64,
        hallucination_rate: f64,
        cognitive_load: f64,
        negentropy_rate: f64,
        composite_score: f64,
    ) -> MetaKPISnapshot {
        MetaKPISnapshot {
            timestamp_ms: 1000,
            meta_accuracy,
            adaptation_rate,
            hallucination_rate,
            cognitive_load,
            negentropy_rate,
            composite_score,
        }
    }

    #[test]
    fn test_snapshot_creation() {
        let snap = make_snapshot(0.9, 0.7, 0.1, 0.3, 0.05, 0.8);
        assert!((snap.meta_accuracy - 0.9).abs() < 1e-6);
        assert!((snap.hallucination_rate - 0.1).abs() < 1e-6);
    }

    #[test]
    fn test_repository_bounds() {
        let mut repo = MetaKPIRepository::new();
        repo.max_snapshots = 10;
        for i in 0..15 {
            repo.record_snapshot(make_snapshot(i as f64 / 15.0, 0.5, 0.1, 0.3, 0.05, 0.5));
        }
        assert_eq!(repo.snapshots.len(), 10);
        assert!(repo.snapshots.front().unwrap().meta_accuracy > 0.3);
    }

    #[test]
    fn test_detect_gaps_stable_data() {
        let mut repo = MetaKPIRepository::new();
        for _ in 0..10 {
            repo.record_snapshot(make_snapshot(0.9, 0.8, 0.05, 0.3, 0.06, 0.85));
        }
        let report = repo.detect_gaps(5);
        assert!(report.gaps.is_empty());
        assert!((report.overall_health - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_detect_gaps_declining() {
        let mut repo = MetaKPIRepository::new();
        for i in 0..10 {
            let acc = 0.9 - i as f64 * 0.05;
            repo.record_snapshot(make_snapshot(acc, 0.5, 0.1, 0.3, 0.05, 0.5));
        }
        let report = repo.detect_gaps(10);
        assert!(!report.gaps.is_empty());
        assert!(report.overall_health < 1.0);
        let has_meta_acc = report
            .gaps
            .iter()
            .any(|(name, _, _)| name == "meta_accuracy");
        assert!(has_meta_acc);
    }

    #[test]
    fn test_detect_gaps_insufficient_data() {
        let repo = MetaKPIRepository::new();
        let report = repo.detect_gaps(10);
        assert!(report.gaps.is_empty());
        assert!((report.overall_health - 1.0).abs() < 1e-6);

        let mut repo = MetaKPIRepository::new();
        repo.record_snapshot(make_snapshot(0.9, 0.8, 0.05, 0.3, 0.06, 0.85));
        let report = repo.detect_gaps(10);
        assert!(report.gaps.is_empty());
    }

    #[test]
    fn test_propose_goal_from_biggest_gap() {
        let mut repo = MetaKPIRepository::new();
        for i in 0..10 {
            let acc = 0.9 - i as f64 * 0.05;
            repo.record_snapshot(make_snapshot(acc, 0.5, 0.1, 0.3, 0.05, 0.5));
        }
        let report = repo.detect_gaps(10);
        let goal = repo.propose_goal(&report);
        assert!(goal.is_some());
        let goal = goal.unwrap();
        assert_eq!(goal.status, GoalStatus::Proposed);
        assert_eq!(goal.strategy, "increase");
        assert!(goal.gap > 0.0);
        assert!(!repo.goals.is_empty());
    }

    #[test]
    fn test_propose_goal_no_gaps_returns_none() {
        let mut repo = MetaKPIRepository::new();
        for _ in 0..5 {
            repo.record_snapshot(make_snapshot(0.95, 0.85, 0.02, 0.2, 0.08, 0.9));
        }
        let report = repo.detect_gaps(5);
        let goal = repo.propose_goal(&report);
        assert!(goal.is_none());
    }

    #[test]
    fn test_goal_status_transitions() {
        let mut repo = MetaKPIRepository::new();
        for i in 0..10 {
            let acc = 0.9 - i as f64 * 0.05;
            repo.record_snapshot(make_snapshot(acc, 0.5, 0.1, 0.3, 0.05, 0.5));
        }
        let report = repo.detect_gaps(10);
        let goal = repo.propose_goal(&report).unwrap();

        repo.update_goal_status(goal.id, GoalStatus::InProgress);
        let g = repo.goals.iter().find(|g| g.id == goal.id).unwrap();
        assert_eq!(g.status, GoalStatus::InProgress);

        repo.update_goal_status(goal.id, GoalStatus::Achieved { achieved_ms: 2000 });
        let g = repo.goals.iter().find(|g| g.id == goal.id).unwrap();
        match &g.status {
            GoalStatus::Achieved { achieved_ms } => assert_eq!(*achieved_ms, 2000),
            _ => panic!("expected Achieved"),
        }
    }

    #[test]
    fn test_stats_format() {
        let mut repo = MetaKPIRepository::new();
        for _ in 0..3 {
            repo.record_snapshot(make_snapshot(0.9, 0.8, 0.05, 0.3, 0.06, 0.85));
        }
        let s = repo.stats();
        assert!(s.contains("MetaKPIRepository:"));
        assert!(s.contains("snapshots"));
        assert!(s.contains("goals"));
        assert!(s.contains("health="));
    }

    #[test]
    fn test_update_goal_status_noop_for_wrong_id() {
        let mut repo = MetaKPIRepository::new();
        repo.update_goal_status(999, GoalStatus::InProgress);
        assert!(repo.goals.is_empty());
    }

    #[test]
    fn test_goal_bounds() {
        let mut repo = MetaKPIRepository::new();
        repo.max_goals = 3;
        for i in 0..10 {
            let acc = 0.9 - i as f64 * 0.05;
            repo.record_snapshot(make_snapshot(acc, 0.5, 0.1, 0.3, 0.05, 0.5));
        }
        let report = repo.detect_gaps(10);
        for _ in 0..5 {
            repo.propose_goal(&report);
        }
        assert_eq!(repo.goals.len(), 3);
    }
}
