use super::CodegenBridge;
use crate::core::nt_core_shared_types::LanguageSpec;

impl CodegenBridge {
    pub fn generate_ne_compiler(spec: &LanguageSpec) -> String {
        let json = spec_to_json(spec);

        format!(
            r###"// Generated by NeoTrix CodegenBridge — DO NOT EDIT
// Ne Language Compiler — Bootstrap v0.1

const EMBEDDED_SPEC: &str = r##"{json}"##;

#[derive(Debug, Clone, PartialEq)]
struct VsaPrimitive {{ name: String, arity: isize, description: String, subspace_requirements: Vec<String> }}

#[derive(Debug, Clone, PartialEq)]
struct SubspaceInfo {{ name: String, tag: u8, field_count: usize, fields: Vec<String>, operations: Vec<String> }}

#[derive(Debug, Clone, PartialEq)]
struct SubspaceMap {{ subspaces: Vec<SubspaceInfo> }}

#[derive(Debug, Clone, PartialEq)]
struct EditPolicy {{ max_gain: f64, max_edits_per_cycle: u32, lifetime_cap: u32, required_gates: Vec<String>, allowed_targets: Vec<String> }}

#[derive(Debug, Clone, PartialEq)]
struct HandlerNode {{ name: String, interval_secs: u64, call_count: u64 }}

#[derive(Debug, Clone, PartialEq)]
struct HandlerGraph {{ handlers: Vec<HandlerNode> }}

#[derive(Debug, Clone, PartialEq)]
struct LanguageSpec {{
    vsa_primitives: Vec<VsaPrimitive>,
    subspace_topology: SubspaceMap,
    edit_policy: EditPolicy,
    handler_graph: HandlerGraph,
    confidence: f64,
    distilled_at: u64,
}}

// ---- Minimal JSON parser ----
struct JParse<'a> {{ src: &'a [u8], pos: usize }}

impl<'a> JParse<'a> {{
    fn new(s: &'a str) -> Self {{ Self {{ src: s.as_bytes(), pos: 0 }} }}
    fn skip(&mut self) {{ while self.pos < self.src.len() && self.src[self.pos].is_ascii_whitespace() {{ self.pos += 1; }} }}
    fn take(&mut self) -> u8 {{ self.skip(); let c = self.src[self.pos]; self.pos += 1; c }}
    fn peek(&mut self) -> u8 {{ self.skip(); self.src[self.pos] }}

    fn string(&mut self) -> Result<String, String> {{
        self.expect(b'"')?;
        let mut r = String::new();
        while self.pos < self.src.len() && self.src[self.pos] != b'"' {{
            if self.src[self.pos] == b'\\' {{ self.pos += 1;
                match self.src[self.pos] {{
                    b'"' => r.push('"'),
                    b'\\' => r.push('\\'),
                    b'n' => r.push('\n'),
                    b't' => r.push('\t'),
                    c => r.push(c as char),
                }}
            }} else {{ r.push(self.src[self.pos] as char); }}
            self.pos += 1;
        }}
        if self.pos < self.src.len() {{ self.pos += 1; }}
        Ok(r)
    }}

    fn number(&mut self) -> f64 {{
        let start = self.pos;
        if self.pos < self.src.len() && self.src[self.pos] == b'-' {{ self.pos += 1; }}
        while self.pos < self.src.len() && self.src[self.pos].is_ascii_digit() {{ self.pos += 1; }}
        if self.pos < self.src.len() && self.src[self.pos] == b'.' {{ self.pos += 1;
            while self.pos < self.src.len() && self.src[self.pos].is_ascii_digit() {{ self.pos += 1; }}
        }}
        std::str::from_utf8(&self.src[start..self.pos]).unwrap_or("0").parse().unwrap_or(0.0)
    }}

    fn expect(&mut self, c: u8) -> Result<(), String> {{ let actual = self.take(); if actual == c {{ Ok(()) }} else {{ Err(format!("expected '{{}}' got '{{}}'", c as char, actual as char)) }} }}
    fn comma(&mut self) {{ self.skip(); if self.pos < self.src.len() && self.src[self.pos] == b',' {{ self.pos += 1; }} }}

    fn string_array(&mut self) -> Result<Vec<String>, String> {{
        let mut v = Vec::new();
        self.expect(b'[')?;
        while self.peek() != b']' {{ v.push(self.string()?); self.comma(); }}
        self.expect(b']')?;
        Ok(v)
    }}

    fn parse_spec(&mut self) -> Result<LanguageSpec, String> {{
        self.expect(b'{{')?;
        let mut vsa_primitives = Vec::new();
        let mut subspace_topology = SubspaceMap {{ subspaces: Vec::new() }};
        let mut edit_policy = EditPolicy {{ max_gain: 0.0, max_edits_per_cycle: 0, lifetime_cap: 0, required_gates: vec![], allowed_targets: vec![] }};
        let mut handler_graph = HandlerGraph {{ handlers: vec![] }};
        let mut confidence = 0.0;
        let mut distilled_at = 0;

        while self.peek() != b'}}' {{
            let key = self.string()?;
            self.expect(b':')?;
            match key.as_str() {{
                "vsa_primitives" => {{
                    self.expect(b'[')?;
                    while self.peek() != b']' {{
                        self.expect(b'{{')?;
                        let mut p = VsaPrimitive {{ name: String::new(), arity: 0, description: String::new(), subspace_requirements: vec![] }};
                        while self.peek() != b'}}' {{
                            let k = self.string()?;
                            self.expect(b':')?;
                            match k.as_str() {{
                                "name" => p.name = self.string()?,
                                "arity" => p.arity = self.number() as isize,
                                "description" => p.description = self.string()?,
                                "subspace_requirements" => p.subspace_requirements = self.string_array()?,
                                _ => {{ }}
                            }}
                            self.comma();
                        }}
                        self.expect(b'}}')?;
                        vsa_primitives.push(p);
                        self.comma();
                    }}
                    self.expect(b']')?;
                }}
                "subspace_topology" => {{
                    self.expect(b'{{')?;
                    while self.peek() != b'}}' {{
                        let k = self.string()?;
                        self.expect(b':')?;
                        if k == "subspaces" {{
                            self.expect(b'[')?;
                            while self.peek() != b']' {{
                                self.expect(b'{{')?;
                                let mut s = SubspaceInfo {{ name: String::new(), tag: 0, field_count: 0, fields: vec![], operations: vec![] }};
                                while self.peek() != b'}}' {{
                                    let fk = self.string()?;
                                    self.expect(b':')?;
                                    match fk.as_str() {{
                                        "name" => s.name = self.string()?,
                                        "tag" => s.tag = self.number() as u8,
                                        "field_count" => s.field_count = self.number() as usize,
                                        "fields" => s.fields = self.string_array()?,
                                        "operations" => s.operations = self.string_array()?,
                                        _ => {{ }}
                                    }}
                                    self.comma();
                                }}
                                self.expect(b'}}')?;
                                subspace_topology.subspaces.push(s);
                                self.comma();
                            }}
                            self.expect(b']')?;
                        }}
                        self.comma();
                    }}
                    self.expect(b'}}')?;
                }}
                "edit_policy" => {{
                    self.expect(b'{{')?;
                    while self.peek() != b'}}' {{
                        let fk = self.string()?;
                        self.expect(b':')?;
                        match fk.as_str() {{
                            "max_gain" => edit_policy.max_gain = self.number(),
                            "max_edits_per_cycle" => edit_policy.max_edits_per_cycle = self.number() as u32,
                            "lifetime_cap" => edit_policy.lifetime_cap = self.number() as u32,
                            "required_gates" => edit_policy.required_gates = self.string_array()?,
                            "allowed_targets" => edit_policy.allowed_targets = self.string_array()?,
                            _ => {{ }}
                        }}
                        self.comma();
                    }}
                    self.expect(b'}}')?;
                }}
                "handler_graph" => {{
                    self.expect(b'{{')?;
                    while self.peek() != b'}}' {{
                        let k = self.string()?;
                        self.expect(b':')?;
                        if k == "handlers" {{
                            self.expect(b'[')?;
                            while self.peek() != b']' {{
                                self.expect(b'{{')?;
                                let mut h = HandlerNode {{ name: String::new(), interval_secs: 0, call_count: 0 }};
                                while self.peek() != b'}}' {{
                                    let hk = self.string()?;
                                    self.expect(b':')?;
                                    match hk.as_str() {{
                                        "name" => h.name = self.string()?,
                                        "interval_secs" => h.interval_secs = self.number() as u64,
                                        "call_count" => h.call_count = self.number() as u64,
                                        _ => {{ }}
                                    }}
                                    self.comma();
                                }}
                                self.expect(b'}}')?;
                                handler_graph.handlers.push(h);
                                self.comma();
                            }}
                            self.expect(b']')?;
                        }}
                        self.comma();
                    }}
                    self.expect(b'}}')?;
                }}
                "confidence" => confidence = self.number(),
                "distilled_at" => distilled_at = self.number() as u64,
                _ => {{ }}
            }}
            self.comma();
        }}
        self.expect(b'}}')?;
        Ok(LanguageSpec {{ vsa_primitives, subspace_topology, edit_policy, handler_graph, confidence, distilled_at }})
    }}
}}

// ---- Ne file parser ----
fn parse_hex(s: &str) -> u8 {{
    u8::from_str_radix(s.trim_start_matches("0x"), 16).unwrap_or(0)
}}

fn parse_ne_file(content: &str) -> LanguageSpec {{
    let mut vsa_primitives = Vec::new();
    let mut subspaces = Vec::new();
    let mut edit_policy = EditPolicy {{ max_gain: 0.0, max_edits_per_cycle: 0, lifetime_cap: 0, required_gates: vec![], allowed_targets: vec![] }};
    let mut handlers = Vec::new();
    let mut confidence = 0.7;
    let mut distilled_at = 0;

    for line in content.lines() {{
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") {{ continue; }}
        let tokens: Vec<&str> = line.split_whitespace().collect();
        if tokens.is_empty() {{ continue; }}
        match tokens[0] {{
            "primitive" if tokens.len() >= 2 => {{
                let name_part = tokens[1];
                let name = name_part.split('(').next().unwrap_or(name_part);
                let arity_str = name_part.split("arity:").nth(1)
                    .and_then(|s| s.split(')').next())
                    .unwrap_or("0").trim();
                let arity: isize = arity_str.parse().unwrap_or(0);
                vsa_primitives.push(VsaPrimitive {{ name: name.to_string(), arity, description: String::new(), subspace_requirements: vec![] }});
            }}
            "subspace" if tokens.len() >= 2 => {{
                let sub_name = tokens[1].split('(').next().unwrap_or(tokens[1]);
                let tag_str = tokens[1].split("tag:").nth(1)
                    .and_then(|s| s.split(')').next())
                    .unwrap_or("0x00").trim();
                let tag = parse_hex(tag_str);
                subspaces.push(SubspaceInfo {{ name: sub_name.to_string(), tag, field_count: 0, fields: vec![], operations: vec![] }});
            }}
            "edit" => {{
                let rest = line.strip_prefix("edit ").unwrap_or("");
                for part in rest.split(',') {{
                    let part = part.trim();
                    if let Some(val) = part.strip_prefix("max_gain:") {{
                        edit_policy.max_gain = val.trim().parse().unwrap_or(0.0);
                    }} else if let Some(val) = part.strip_prefix("max_edits:") {{
                        edit_policy.max_edits_per_cycle = val.trim().parse().unwrap_or(0);
                    }}
                }}
            }}
            "handler" if tokens.len() >= 3 => {{
                let name_part = tokens[1].trim_matches('"');
                let interval_str = tokens[2].split("every:").nth(1)
                    .and_then(|s| s.split('s').next().or_else(|| s.split(')').next()))
                    .unwrap_or("0").trim();
                let interval: u64 = interval_str.parse().unwrap_or(0);
                handlers.push(HandlerNode {{ name: name_part.to_string(), interval_secs: interval, call_count: 0 }});
            }}
            "check" if tokens.get(1) == Some(&"identity") => {{ }}
            _ => {{ }}
        }}
    }}

    LanguageSpec {{
        vsa_primitives,
        subspace_topology: SubspaceMap {{ subspaces }},
        edit_policy,
        handler_graph: HandlerGraph {{ handlers }},
        confidence,
        distilled_at,
    }}
}}

// ---- Spec comparison ----
fn compare_specs(a: &LanguageSpec, b: &LanguageSpec) -> Vec<String> {{
    let mut diffs = Vec::new();
    if a.vsa_primitives.len() != b.vsa_primitives.len() {{
        diffs.push(format!("primitive count: {{}} vs {{}}", a.vsa_primitives.len(), b.vsa_primitives.len()));
    }}
    for (i, (pa, pb)) in a.vsa_primitives.iter().zip(b.vsa_primitives.iter()).enumerate() {{
        if pa.name != pb.name {{ diffs.push(format!("primitive[{{}}].name: {{}} vs {{}}", i, pa.name, pb.name)); }}
        if pa.arity != pb.arity {{ diffs.push(format!("primitive[{{}}].arity: {{}} vs {{}}", i, pa.arity, pb.arity)); }}
    }}
    if a.subspace_topology.subspaces.len() != b.subspace_topology.subspaces.len() {{
        diffs.push(format!("subspace count: {{}} vs {{}}", a.subspace_topology.subspaces.len(), b.subspace_topology.subspaces.len()));
    }}
    for (i, (sa, sb)) in a.subspace_topology.subspaces.iter().zip(b.subspace_topology.subspaces.iter()).enumerate() {{
        if sa.name != sb.name {{ diffs.push(format!("subspace[{{}}].name: {{}} vs {{}}", i, sa.name, sb.name)); }}
        if sa.tag != sb.tag {{ diffs.push(format!("subspace[{{}}].tag: 0x{{:02x}} vs 0x{{:02x}}", i, sa.tag, sb.tag)); }}
    }}
    if (a.edit_policy.max_gain - b.edit_policy.max_gain).abs() > 1e-9 {{
        diffs.push(format!("max_gain: {{}} vs {{}}", a.edit_policy.max_gain, b.edit_policy.max_gain));
    }}
    if a.edit_policy.max_edits_per_cycle != b.edit_policy.max_edits_per_cycle {{
        diffs.push(format!("max_edits: {{}} vs {{}}", a.edit_policy.max_edits_per_cycle, b.edit_policy.max_edits_per_cycle));
    }}
    diffs
}}

// ---- Comptime preprocessing ----
fn comptime_eval(expr: &str) -> Result<String, String> {{
    let e = expr.trim();
    if e == "true" {{ return Ok("true".into()); }}
    if e == "false" {{ return Ok("false".into()); }}
    if e.starts_with('"') {{
        if !e.ends_with('"') {{ return Err("unterminated string literal".into()); }}
        return Ok(e[1..e.len()-1].to_string());
    }}
    if let Ok(i) = e.parse::<i64>() {{ return Ok(i.to_string()); }}
    if let Ok(f) = e.parse::<f64>() {{ return Ok(f.to_string()); }}
    let op_pos = e.find('+').or_else(|| e.find('-')).or_else(|| e.find('*')).or_else(|| e.find('/'));
    if let Some(pos) = op_pos {{
        let (left, rest) = e.split_at(pos);
        let op = rest.chars().next().ok_or_else(|| "comptime: empty operator target".to_string())?;
        let right = rest[1..].trim();
        let lv = comptime_eval(left.trim())?;
        let rv = comptime_eval(right)?;
        let li: i64 = lv.parse().map_err(|_| "non-numeric left operand".to_string())?;
        let ri: i64 = rv.parse().map_err(|_| "non-numeric right operand".to_string())?;
        return match op {{
            '+' => Ok((li + ri).to_string()),
            '-' => Ok((li - ri).to_string()),
            '*' => Ok((li * ri).to_string()),
            '/' => {{
                if ri == 0 {{ return Err("division by zero".into()); }}
                Ok((li / ri).to_string())
            }}
            _ => Err(format!("unknown operator: {{}}", op)),
        }};
    }}
    Err(format!("cannot eval: {{}}", expr))
}}

fn preprocess_line(source: &str) -> String {{
    let mut result = String::new();
    let mut rest = source;
    while let Some(start) = rest.find("$comptime(") {{
        result.push_str(&rest[..start]);
        let inner_start = start + 10;
        let after = &rest[inner_start..];
        let mut depth: u32 = 1;
        let mut end = 0;
        for (i, c) in after.chars().enumerate() {{
            match c {{
                '(' => depth += 1,
                ')' => {{ depth -= 1; if depth == 0 {{ end = i; break; }} }}
                _ => {{ }}
            }}
        }}
        if depth == 0 {{
            let expr = &after[..end];
            match comptime_eval(expr) {{
                Ok(v) => result.push_str(&v),
                Err(e) => result.push_str(&format!("/* comptime_error: {{}} */", e)),
            }}
            rest = &after[end + 1..];
        }} else {{
            result.push_str("$comptime(");
            rest = after;
        }}
    }}
    result.push_str(rest);
    result
}}

fn main() {{
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {{
        eprintln!("Usage: ne_compiler <file.ne>");
        std::process::exit(1);
    }}
    let content = std::fs::read_to_string(&args[1]).unwrap_or_else(|e| {{
        eprintln!("Error reading {{}}: {{}}", args[1], e);
        std::process::exit(1);
    }});
    let content = preprocess_line(&content);
    let parsed = parse_ne_file(&content);
    let embedded = JParse::new(EMBEDDED_SPEC).parse_spec().unwrap_or_else(|e| {{ eprintln!("Failed to parse embedded spec: {{}}", e); std::process::exit(1); }});
    let diffs = compare_specs(&embedded, &parsed);
    if diffs.is_empty() {{
        println!("NE COMPILER v0.1: spec matches");
    }} else {{
        println!("NE COMPILER v0.1: spec mismatch");
        for d in &diffs {{
            println!("  {{}}", d);
        }}
        std::process::exit(1);
    }}
}}
"###,
            json = json
        )
    }
}

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

fn spec_to_json(spec: &LanguageSpec) -> String {
    let mut j = String::from("{\"vsa_primitives\":[");
    for (i, p) in spec.vsa_primitives.iter().enumerate() {
        if i > 0 {
            j.push(',');
        }
        j.push_str(&format!(
            r#"{{"name":"{}","arity":{},"description":"{}","subspace_requirements":["#,
            json_escape(p.name),
            p.arity,
            json_escape(p.description),
        ));
        for (j2, sr) in p.subspace_requirements.iter().enumerate() {
            if j2 > 0 {
                j.push(',');
            }
            j.push('"');
            j.push_str(&json_escape(sr));
            j.push('"');
        }
        j.push_str("]}");
    }
    j.push_str("],\"subspace_topology\":{\"subspaces\":[");
    for (i, s) in spec.subspace_topology.subspaces.iter().enumerate() {
        if i > 0 {
            j.push(',');
        }
        j.push_str(&format!(
            r#"{{"name":"{}","tag":{},"field_count":{},"fields":["#,
            json_escape(s.name),
            s.tag,
            s.field_count,
        ));
        for (j2, f) in s.fields.iter().enumerate() {
            if j2 > 0 {
                j.push(',');
            }
            j.push('"');
            j.push_str(&json_escape(f));
            j.push('"');
        }
        j.push_str("],\"operations\":[");
        for (j2, op) in s.operations.iter().enumerate() {
            if j2 > 0 {
                j.push(',');
            }
            j.push('"');
            j.push_str(&json_escape(op));
            j.push('"');
        }
        j.push_str("]}");
    }
    j.push_str("]},\"edit_policy\":{");
    j.push_str(&format!(
        r#""max_gain":{},"max_edits_per_cycle":{},"lifetime_cap":{},"required_gates":["#,
        spec.edit_policy.max_gain,
        spec.edit_policy.max_edits_per_cycle,
        spec.edit_policy.lifetime_cap,
    ));
    for (i, g) in spec.edit_policy.required_gates.iter().enumerate() {
        if i > 0 {
            j.push(',');
        }
        j.push('"');
        j.push_str(&json_escape(g));
        j.push('"');
    }
    j.push_str("],\"allowed_targets\":[");
    for (i, t) in spec.edit_policy.allowed_targets.iter().enumerate() {
        if i > 0 {
            j.push(',');
        }
        j.push('"');
        j.push_str(&json_escape(t));
        j.push('"');
    }
    j.push_str(&format!("]}},\"handler_graph\":{{\"handlers\":["));
    for (i, h) in spec.handler_graph.handlers.iter().enumerate() {
        if i > 0 {
            j.push(',');
        }
        j.push_str(&format!(
            r#"{{"name":"{}","interval_secs":{},"call_count":{}}}"#,
            json_escape(h.name),
            h.interval_secs,
            h.call_count,
        ));
    }
    j.push_str(&format!(
        "]}},\"confidence\":{},\"distilled_at\":{}}}",
        spec.confidence, spec.distilled_at,
    ));
    j
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::nt_core_shared_types::{
        default_edit_policy, default_subspace_topology, default_vsa_primitives, EditPolicy,
        HandlerGraph, LanguageSpec, SubspaceInfo, SubspaceMap, VsaPrimitive,
    };
    use std::process::Command;
    use std::sync::Mutex;

    fn minimal_spec() -> LanguageSpec {
        LanguageSpec {
            vsa_primitives: default_vsa_primitives(),
            subspace_topology: default_subspace_topology(),
            edit_policy: default_edit_policy(),
            handler_graph: HandlerGraph { handlers: vec![] },
            confidence: 0.7,
            distilled_at: 0,
        }
    }

    // ── json_escape tests ──

    #[test]
    fn test_json_escape_empty() {
        assert_eq!(json_escape(""), "");
    }

    #[test]
    fn test_json_escape_plain_text() {
        assert_eq!(json_escape("hello_world_42"), "hello_world_42");
    }

    #[test]
    fn test_json_escape_double_quote() {
        assert_eq!(json_escape("\"quoted\""), "\\\"quoted\\\"");
    }

    #[test]
    fn test_json_escape_backslash() {
        assert_eq!(json_escape("a\\b"), "a\\\\b");
    }

    #[test]
    fn test_json_escape_newline() {
        assert_eq!(json_escape("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn test_json_escape_tab() {
        assert_eq!(json_escape("col1\tcol2"), "col1\\tcol2");
    }

    #[test]
    fn test_json_escape_carriage_return() {
        assert_eq!(json_escape("line1\rline2"), "line1\\rline2");
    }

    #[test]
    fn test_json_escape_control_char() {
        assert_eq!(json_escape("a\x01b"), "a\\u0001b");
    }

    #[test]
    fn test_json_escape_multiple_special_chars() {
        assert_eq!(json_escape("a\"b\\c\nd"), "a\\\"b\\\\c\\nd");
    }

    // ── spec_to_json tests ──

    #[test]
    fn test_spec_to_json_valid_syntax() {
        let spec = minimal_spec();
        let json = spec_to_json(&spec);
        // Must start with `{` and end with `}`
        assert!(json.starts_with('{'), "JSON must start with '{{'");
        assert!(json.ends_with('}'), "JSON must end with '}}'");
        // Must contain top-level keys
        assert!(json.contains("\"vsa_primitives\""));
        assert!(json.contains("\"subspace_topology\""));
        assert!(json.contains("\"edit_policy\""));
        assert!(json.contains("\"handler_graph\""));
        assert!(json.contains("\"confidence\""));
        assert!(json.contains("\"distilled_at\""));
    }

    #[test]
    fn test_spec_to_json_contains_primitive_names() {
        let spec = minimal_spec();
        let json = spec_to_json(&spec);
        for prim in &spec.vsa_primitives {
            let key = format!("\"name\":\"{}\"", prim.name);
            assert!(
                json.contains(&key),
                "JSON must contain primitive '{}'",
                prim.name
            );
        }
    }

    #[test]
    fn test_spec_to_json_confidence_value() {
        let mut spec = minimal_spec();
        spec.confidence = 0.95;
        let json = spec_to_json(&spec);
        assert!(json.contains("\"confidence\":0.95") || json.contains("\"confidence\":0.949"));
    }

    #[test]
    fn test_spec_to_json_with_subspaces() {
        let spec = LanguageSpec {
            vsa_primitives: vec![],
            subspace_topology: SubspaceMap {
                subspaces: vec![SubspaceInfo {
                    name: "test_sub".into(),
                    tag: 0x07,
                    field_count: 2,
                    fields: vec!["f1".into(), "f2".into()],
                    operations: vec!["op1".into()],
                }],
            },
            edit_policy: default_edit_policy(),
            handler_graph: HandlerGraph { handlers: vec![] },
            confidence: 0.5,
            distilled_at: 100,
        };
        let json = spec_to_json(&spec);
        assert!(json.contains("\"name\":\"test_sub\""));
        assert!(json.contains("\"tag\":7"));
        assert!(json.contains("\"field_count\":2"));
        assert!(json.contains("\"f1\""));
        assert!(json.contains("\"f2\""));
        assert!(json.contains("\"op1\""));
    }

    #[test]
    fn test_spec_to_json_with_handlers() {
        let spec = LanguageSpec {
            vsa_primitives: vec![],
            subspace_topology: default_subspace_topology(),
            edit_policy: default_edit_policy(),
            handler_graph: HandlerGraph {
                handlers: vec![crate::core::nt_core_shared_types::HandlerNode {
                    name: "h1".into(),
                    interval_secs: 60,
                    call_count: 5,
                }],
            },
            confidence: 0.3,
            distilled_at: 42,
        };
        let json = spec_to_json(&spec);
        assert!(json.contains("\"name\":\"h1\""));
        assert!(json.contains("\"interval_secs\":60"));
        assert!(json.contains("\"call_count\":5"));
        assert!(json.contains("\"distilled_at\":42"));
    }

    // ── generate_ne_compiler tests ──

    #[test]
    fn test_generate_compiler_contains_fn_main() {
        let spec = minimal_spec();
        let code = CodegenBridge::generate_ne_compiler(&spec);
        assert!(
            code.contains("fn main()"),
            "generated compiler must contain fn main()"
        );
    }

    #[test]
    fn test_generate_compiler_contains_embedded_spec() {
        let spec = minimal_spec();
        let code = CodegenBridge::generate_ne_compiler(&spec);
        assert!(
            code.contains("EMBEDDED_SPEC"),
            "generated compiler must embed spec"
        );
        assert!(
            code.contains("parse_ne_file"),
            "generated compiler must contain parser"
        );
        assert!(
            code.contains("preprocess_line"),
            "generated compiler must contain preprocessor"
        );
    }

    #[test]
    fn test_generate_compiler_contains_primitives_from_spec() {
        let spec = minimal_spec();
        let code = CodegenBridge::generate_ne_compiler(&spec);
        for prim in &spec.vsa_primitives {
            if prim.name == "bind" || prim.name == "bundle" || prim.name == "negate" {
                assert!(
                    code.contains(&prim.name),
                    "generated compiler must reference primitive '{}'",
                    prim.name
                );
            }
        }
    }

    #[test]
    fn test_generate_compiler_with_empty_spec() {
        let spec = LanguageSpec {
            vsa_primitives: vec![],
            subspace_topology: SubspaceMap { subspaces: vec![] },
            edit_policy: default_edit_policy(),
            handler_graph: HandlerGraph { handlers: vec![] },
            confidence: 0.0,
            distilled_at: 0,
        };
        let code = CodegenBridge::generate_ne_compiler(&spec);
        assert!(
            code.contains("fn main()"),
            "even with empty spec, compiler must contain fn main()"
        );
        assert!(
            code.len() > 200,
            "compiler output must be substantial ({} bytes)",
            code.len()
        );
    }

    #[test]
    fn test_generate_compiler_is_self_contained() {
        let spec = minimal_spec();
        let code = CodegenBridge::generate_ne_compiler(&spec);
        // These are the core components a self-contained compiler needs
        assert!(code.contains("use std::"), "must use std");
        assert!(code.contains("fn main()"), "must have main entry");
        assert!(code.contains("parse_ne_file"), "must define parser");
        assert!(code.contains("compare_specs"), "must define comparison");
    }

    #[test]
    fn test_generate_compiler_handles_stress_names() {
        let spec = LanguageSpec {
            vsa_primitives: vec![VsaPrimitive {
                name: "x\\y\"z".into(),
                arity: 1,
                description: "desc with \"quotes\" and \\backslash\\".into(),
                subspace_requirements: vec![],
            }],
            subspace_topology: default_subspace_topology(),
            edit_policy: default_edit_policy(),
            handler_graph: HandlerGraph { handlers: vec![] },
            confidence: 0.5,
            distilled_at: 0,
        };
        // This must not panic and produce valid output
        let code = CodegenBridge::generate_ne_compiler(&spec);
        assert!(code.contains("fn main()"));
        assert!(code.len() > 100);
    }

    #[test]
    fn test_spec_to_json_roundtrip_key_consistency() {
        // Ensure that all LanguageSpec fields appear as JSON keys
        let spec = minimal_spec();
        let json = spec_to_json(&spec);
        let required_keys = &[
            "vsa_primitives",
            "subspace_topology",
            "edit_policy",
            "handler_graph",
            "confidence",
            "distilled_at",
        ];
        for key in required_keys {
            let quoted = format!("\"{}\"", key);
            assert!(json.contains(&quoted), "JSON must contain key \"{}\"", key);
        }
    }

    // ── compiled-and-run integration tests ──

    static RUSTC_LOCK: Mutex<()> = Mutex::new(());

    /// `.ne` content that matches the default `minimal_spec()`.
    const MATCHING_NE_CONTENT: &str = "\
primitive bind(arity:2)
primitive hlb_bind(arity:2)
primitive bundle(arity:-1)
primitive permute(arity:2)
primitive negate(arity:1)
primitive similarity(arity:2)
primitive cosine(arity:2)
primitive hamming_distance(arity:2)
primitive random_vector(arity:0)
primitive seeded_random(arity:2)
primitive binarize(arity:1)
primitive majority_bundle(arity:-1)
primitive translate_direct(arity:2)
primitive translate_compositional(arity:3)
primitive translate_refinement(arity:2)
subspace @self(tag:0x01)
subspace @world(tag:0x02)
subspace @spatial(tag:0x03)
subspace @episodic(tag:0x04)
subspace @goal(tag:0x05)
subspace @physics(tag:0x06)
subspace @emotional(tag:0x07)
subspace @temporal(tag:0x08)
edit max_gain:0.5, max_edits:20
";

    /// Write generated Rust source and `.ne` input to temp files, compile with `rustc`,
    /// run the binary against the `.ne` input, and return `(success, output)`.
    /// Temp files are cleaned up on all exit paths.
    fn compile_and_run(generated: &str, ne_input: &str) -> (bool, String) {
        let _lock = RUSTC_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let pid = std::process::id();
        let tmp = std::env::temp_dir();

        let rs_path = tmp.join(format!("nt_nec_test_{}.rs", pid));
        let ne_path = tmp.join(format!("nt_nec_test_{}.ne", pid));
        let bin_path = tmp.join(format!("nt_nec_test_bin_{}", pid));

        let cleanup = || -> Result<(), std::io::Error> {
            let _ = std::fs::remove_file(&rs_path);
            let _ = std::fs::remove_file(&ne_path);
            let _ = std::fs::remove_file(&bin_path);
            Ok(())
        };

        let fail = |msg: &str| -> (bool, String) {
            let _ = cleanup();
            (false, msg.to_string())
        };

        if std::fs::write(&rs_path, generated).is_err() {
            return fail("failed to write temp .rs");
        }
        if std::fs::write(&ne_path, ne_input).is_err() {
            return fail("failed to write temp .ne");
        }

        // Verify rustc is installed
        match Command::new("rustc").arg("--version").output() {
            Ok(out) if out.status.success() => {}
            _ => return fail("rustc not available"),
        }

        // Compile with rustc
        let compile = Command::new("rustc")
            .args(["--edition", "2021", "--crate-type", "bin"])
            .arg(&rs_path)
            .arg("-o")
            .arg(&bin_path)
            .output();

        let compile = match compile {
            Ok(o) => o,
            Err(e) => return fail(&format!("rustc execution error: {}", e)),
        };
        if !compile.status.success() {
            let stderr = String::from_utf8_lossy(&compile.stderr).to_string();
            return fail(&stderr);
        }

        // Run the compiled binary against the .ne input
        let run = Command::new(&bin_path).arg(&ne_path).output();

        let run = match run {
            Ok(o) => o,
            Err(e) => {
                let _ = cleanup();
                return (false, format!("binary execution error: {}", e));
            }
        };

        let stdout = String::from_utf8_lossy(&run.stdout).to_string();
        let stderr = String::from_utf8_lossy(&run.stderr).to_string();
        let combined = if stderr.is_empty() {
            stdout
        } else {
            format!("{}\n{}", stdout, stderr)
        };

        let _ = cleanup();
        (run.status.success(), combined)
    }

    fn mismatch_spec() -> LanguageSpec {
        let mut spec = minimal_spec();
        spec.vsa_primitives.push(VsaPrimitive {
            name: "extra_op".into(),
            arity: 1,
            description: "extra primitive for mismatch test".into(),
            subspace_requirements: vec![],
        });
        spec
    }

    fn empty_spec() -> LanguageSpec {
        LanguageSpec {
            vsa_primitives: vec![],
            subspace_topology: SubspaceMap { subspaces: vec![] },
            edit_policy: EditPolicy {
                max_gain: 0.0,
                max_edits_per_cycle: 0,
                lifetime_cap: 0,
                required_gates: vec![],
                allowed_targets: vec![],
            },
            handler_graph: HandlerGraph { handlers: vec![] },
            confidence: 0.0,
            distilled_at: 0,
        }
    }

    #[test]
    #[ignore = "requires rustc to be installed"]
    fn test_generated_code_is_valid_rust() {
        let code = CodegenBridge::generate_ne_compiler(&minimal_spec());
        let (ok, msg) = compile_and_run(&code, MATCHING_NE_CONTENT);
        assert!(ok, "rustc compilation failed: {}", msg);
    }

    #[test]
    #[ignore = "requires rustc to be installed"]
    fn test_generated_binary_runs_and_exits_success() {
        let code = CodegenBridge::generate_ne_compiler(&minimal_spec());
        let (ok, msg) = compile_and_run(&code, MATCHING_NE_CONTENT);
        assert!(ok, "binary should exit 0 when spec matches: {}", msg);
        assert!(
            msg.contains("spec matches"),
            "output should confirm match, got: {}",
            msg
        );
    }

    #[test]
    #[ignore = "requires rustc to be installed"]
    fn test_generated_binary_reports_mismatch() {
        let code = CodegenBridge::generate_ne_compiler(&mismatch_spec());
        let (ok, msg) = compile_and_run(&code, MATCHING_NE_CONTENT);
        assert!(
            !ok,
            "binary should report mismatch when specs differ, output: {}",
            msg
        );
        assert!(
            msg.contains("spec mismatch"),
            "output should mention mismatch, got: {}",
            msg
        );
    }

    #[test]
    #[ignore = "requires rustc to be installed"]
    fn test_generated_code_rustfmt_check() {
        let code = CodegenBridge::generate_ne_compiler(&minimal_spec());
        let tmp = std::env::temp_dir();
        let rs_path = tmp.join(format!("nt_nec_fmt_{}.rs", std::process::id()));

        std::fs::write(&rs_path, &code).expect("write temp .rs for rustfmt");
        let status = Command::new("rustfmt")
            .arg("--check")
            .arg(&rs_path)
            .status()
            .expect("rustfmt execution");
        let _ = std::fs::remove_file(&rs_path);
        assert!(status.success(), "generated code must pass rustfmt --check");
    }

    #[test]
    #[ignore = "requires rustc to be installed"]
    fn test_empty_spec_still_compiles() {
        let code = CodegenBridge::generate_ne_compiler(&empty_spec());
        let (ok, msg) = compile_and_run(&code, "// empty test\ncheck identity\n");
        assert!(
            ok,
            "empty spec should compile and run successfully: {}",
            msg
        );
    }
}
