#!/usr/bin/env python3
"""nt_parity_ref.py — 从**对方产品本体**机械采集行为 oracle（复现对方产品的数据侧）。

为什么需要它：DECOMPOSE-PARITY 的 `parity` 子命令只能做**名字级**对位（已实测
误报：`get` 被报成「仅对方有」，而我方同义方法叫 `cache`）。名字级矩阵证明不了
「复现对方产品」。本脚本补上**行为级**那一腿：

  1. 读 `.neotrix/parity/<name>.vectors.json`（唯一事实源，我方测试也读它）；
  2. 在**临时 cargo 工程**里写一个只依赖对方 crate 的 runner（`--offline`，
     依赖取自本机 cargo registry，不联网、不执行对方代码之外的东西）；
  3. 跑完把逐步观测写成 `<name>.reference.json` —— 这就是「对方产品的可观测行为」。

⚠️ 为什么 runner 要**代码生成**而不是让 Rust 侧解析 JSON：临时工程只允许一个
依赖（对方 crate），加 serde 就得赌 registry 缓存命中。把 vectors 编译进
runner 则零额外依赖，且 vectors 仍是唯一事实源（生成器直接读它）。

诚实边界（必须随产物一起看）：
  - oracle 是**对方实现自己吐的**，不是人手写的期望值 ⇒ 不会自证。
  - 但它只覆盖 vectors 覆盖的 op 集合；vectors 没写的语义**没有被验证**。
  - 对位是**公共子集**：我方扩展（pinning / hit_count）刻意不在 vectors 里，
    因为进则必分歧，那是扩展不是缺陷。

用法：
  python3 scripts/ops/nt_parity_ref.py --vectors .neotrix/parity/response-cache.vectors.json \\
      [--crate lru@0.18.5] [--out .neotrix/parity/response-cache.reference.json] [--check]

  --check  只比对现有 reference.json 与本次实跑是否一致（不写）⇒ 可作门。
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REGISTRY_GLOB = os.path.expanduser(
    '~/.cargo/registry/src/*/{crate}')

RUNNER_TMPL = '''// GENERATED by scripts/ops/nt_parity_ref.py — do not edit by hand.
// Runs the {crate} reference implementation over the same op script our
// implementation is driven with, printing one observation line per step.
use std::collections::HashMap;

struct Case {{
    name: &'static str,
    capacity: usize,
    ops: Vec<(&'static str, &'static str, &'static str)>,
}}

fn main() {{
    let cases: Vec<Case> = vec![
{cases}
    ];
    let mut out: Vec<String> = Vec::new();
    for c in &cases {{
        out.push(format!("{{}}", c.name));
        let mut cache: lru::LruCache<String, String> =
            lru::LruCache::new(std::num::NonZero::new(c.capacity.max(1)).unwrap());
        let mut idx: HashMap<String, String> = HashMap::new();
        for (op, k, v) in &c.ops {{
            match *op {{
                "put" => {{
                    // If the key was evicted, drop the reverse index too, so
                    // `contains` reflects the cache, not our bookkeeping.
                    if idx.insert(k.to_string(), v.to_string()).is_none() {{
                        cache.put(k.to_string(), v.to_string());
                    }} else {{
                        cache.put(k.to_string(), v.to_string());
                    }}
                    out.push("put:none".to_string());
                }}
                "get" => {{
                    let r = cache.get(*k).cloned();
                    match r {{
                        Some(val) => out.push(format!("get:Some({{}})", val)),
                        None => out.push("get:None".to_string()),
                    }}
                }}
                "len" => out.push(format!("len:{{}}", cache.len())),
                "contains" => {{
                    out.push(format!("contains:{{}}", cache.contains(*k)));
                }}
                other => {{
                    out.push(format!("unsupported:{{}}", other));
                }}
            }}
        }}
    }}
    for line in &out {{
        println!("{{}}", line);
    }}
}}
'''


def load_vectors(path):
    with open(path, encoding='utf-8') as fh:
        doc = json.load(fh)
    if doc.get('schema') != 'nt-parity/vectors/1':
        raise SystemExit('unexpected vectors schema: %r' % doc.get('schema'))
    if not doc.get('cases'):
        raise SystemExit('vectors has no cases (an empty oracle proves nothing)')
    return doc


def gen_runner(doc):
    blocks = []
    for case in doc['cases']:
        ops = []
        for op in case['ops']:
            name = op['op']
            if name not in doc.get('ops_supported', []):
                raise SystemExit('op %r not in ops_supported — refusing to '
                                 'generate a runner that would print '
                                 '"unsupported"' % name)
            ops.append('            ("%s", "%s", "%s"),'
                       % (name, op.get('k', ''), op.get('v', '')))
        blocks.append(
            '        Case {\n'
            '            name: "%s",\n'
            '            capacity: %d,\n'
            '            ops: vec![\n%s\n            ],\n'
            '        },' % (case['name'], int(case['capacity']),
                        '\n'.join(ops)))
    return RUNNER_TMPL.format(crate='__CRATE__', cases='\n'.join(blocks))


def find_registry_src(crate_at):
    """crate_at 形如 'lru@0.18.5'。只在**本机 cargo registry** 里找，
    找不到就退出（不联网、不 clone —— 抄外部源码进仓是另一件事）。"""
    name, _, ver = crate_at.partition('@')
    if not ver:
        raise SystemExit('--crate needs an explicit version, e.g. lru@0.18.5')
    pattern = REGISTRY_GLOB.format(crate='%s-%s' % (name, ver))
    import glob
    hits = sorted(glob.glob(pattern))
    if not hits:
        raise SystemExit(
            'no vendored copy of %s in the local cargo registry (looked: %s).\n'
            'This tool does not download anything on purpose.' % (crate_at, pattern))
    return hits[-1]


def license_of(src_dir):
    lic = os.path.join(src_dir, 'LICENSE')
    if not os.path.isfile(lic):
        return 'UNKNOWN'
    head = open(lic, encoding='utf-8', errors='replace').read(400)
    for tag in ('MIT License', 'Apache License', 'BSD', 'CC-BY-SA',
                'Mozilla Public License', 'ISC License'):
        if tag.lower() in head.lower():
            return tag
    return 'UNKNOWN'


def run_reference(vectors_path, crate_at, workdir):
    doc = load_vectors(vectors_path)
    src = find_registry_src(crate_at)
    crate_name = crate_at.split('@')[0]
    runner = gen_runner(doc).replace('__CRATE__', crate_name)
    os.makedirs(workdir, exist_ok=True)
    os.makedirs(os.path.join(workdir, 'src'), exist_ok=True)
    with open(os.path.join(workdir, 'Cargo.toml'), 'w', encoding='utf-8') as fh:
        fh.write('[package]\nname = "nt-parity-ref"\nversion = "0.0.0"\n'
                 'edition = "2021"\n\n[dependencies]\n%s = "= %s"\n'
                 % (crate_name, crate_at.split('@')[1]))
    with open(os.path.join(workdir, 'src', 'main.rs'), 'w',
              encoding='utf-8') as fh:
        fh.write(runner)
    proc = subprocess.run(
        ['cargo', 'run', '--quiet', '--offline'],
        cwd=workdir, capture_output=True, text=True, timeout=900)
    if proc.returncode != 0:
        sys.stderr.write('reference run failed rc=%d\n' % proc.returncode)
        sys.stderr.write(proc.stderr[-2500:] + '\n')
        return None
    obs = [l for l in proc.stdout.splitlines() if l.strip()]
    expected = sum(1 + len(c['ops']) for c in doc['cases'])
    if len(obs) != expected:
        sys.stderr.write('reference produced %d observation lines, vectors '
                         'imply %d — refusing to record a partial oracle\n'
                         % (len(obs), expected))
        return None
    return {
        'schema': 'nt-parity/reference/1',
        'generated_by': 'scripts/ops/nt_parity_ref.py',
        'reference_impl': {
            'crate': crate_at,
            'source': 'local cargo registry (vendored dependency, offline)',
            'license': license_of(src),
        },
        'vectors': os.path.relpath(vectors_path, REPO),
        'observations': obs,
    }


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    ap.add_argument('--vectors', required=True)
    ap.add_argument('--crate', default='lru@0.18.5')
    ap.add_argument('--out', default=None)
    ap.add_argument('--check', action='store_true',
                    help='compare against the existing reference, write nothing')
    ap.add_argument('--workdir', default=None)
    args = ap.parse_args(argv[1:])

    vectors = args.vectors if os.path.isabs(args.vectors) \
        else os.path.join(REPO, args.vectors)
    out = args.out or os.path.splitext(vectors)[0] + '.reference.json'
    if not os.path.isabs(out):
        out = os.path.join(REPO, out)

    workdir = args.workdir or tempfile.mkdtemp(prefix='nt-parity-ref-')
    try:
        ref = run_reference(vectors, args.crate, workdir)
    finally:
        if args.workdir is None and os.path.isdir(workdir):
            shutil.rmtree(workdir, ignore_errors=True)
    if ref is None:
        return 2

    text = json.dumps(ref, ensure_ascii=False, indent=2) + '\n'
    if args.check:
        if not os.path.isfile(out):
            sys.stderr.write('no reference oracle at %s — regenerate first\n'
                             % out)
            return 1
        cur = open(out, encoding='utf-8').read()
        if cur != text:
            sys.stderr.write('reference oracle DRIFTED vs a live re-run of %s\n'
                             % args.crate)
            old = json.loads(cur).get('observations', [])
            new = ref['observations']
            for i in range(max(len(old), len(new))):
                a = old[i] if i < len(old) else '<missing>'
                b = new[i] if i < len(new) else '<missing>'
                if a != b:
                    sys.stderr.write('  line %d: stored=%s live=%s\n'
                                     % (i + 1, a, b))
            return 1
        sys.stdout.write('reference oracle matches a live re-run (%s, %s)\n'
                         % (args.crate, ref['reference_impl']['license']))
        return 0

    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(text)
    sys.stdout.write('wrote %d observations -> %s\n'
                     % (len(ref['observations']), out))
    sys.stdout.write('[parity-ref] %s license=%s source=%s\n'
                     % (args.crate, ref['reference_impl']['license'],
                        'local-registry'))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
