use super::HyperAgentArchive;
use rand::Rng;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A variant proposal generated by DGM-style stepping stone sampling.
/// This bridges archive knowledge (HyperAgentRecord scores/novelty) into the
/// ConsciousnessIntegration writeback buffer (DgmhEdit).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VariantProposal {
    pub description: String,
    pub target_subsystem: String,
    pub proposed_change: String,
    pub estimated_gain: f64,
    pub stepping_stone_score: f64,
    pub parent_id: Option<uuid::Uuid>,
}

/// A candidate in the active mutation pool.
/// Tracks acceptance history for priority adjustment.
#[derive(Debug, Clone)]
pub struct CandidateEntry {
    pub target_subsystem: String,
    pub base_gain: f64,
    pub acceptance_count: u64,
    pub rejection_count: u64,
    pub priority: f64,
}

/// DGM-style variant sampler: reads the HyperAgentArchive and produces
/// variant edit proposals targeting known subsystems.
///
/// Architecture: DGM (arXiv:2505.22954) stepping stone sampling.
/// Instead of random mutation, samples archive records proportionally to
/// their stepping stone score (score × novelty_bonus) and maps them to
/// subsystem-specific edit proposals with calibrated gain estimates.
///
/// Phase 17.2: Maintains a cycling mutation pool (3-5 candidates) with
/// round-robin evaluation, acceptance feedback, and priority adjustment.
/// This implements DGM's population-based parallel exploration.
pub struct DgmVariantSampler {
    /// Subsystem target pool and weights (higher = more proposals)
    subsystem_targets: Vec<(String, f64)>,
    /// Base noise level for gain estimation
    noise_level: f64,
    /// Number of variant proposals to generate per cycle
    pub variants_per_cycle: usize,
    /// Minimum stepping stone score to be considered as parent
    min_stepping_stone_score: f64,
    /// Cycle counter for interval gating
    pub cycle: u64,
    // ── Phase 17.2: Parallel mutation pool ──
    /// Active candidate pool (3-5 entries, round-robin cycled)
    candidate_pool: Vec<CandidateEntry>,
    /// Round-robin index into the pool
    pool_index: usize,
    /// Max pool size before eviction
    pool_max_size: usize,
    /// Track which subsystems have been accepted (for priority boosting)
    acceptance_map: HashMap<String, u64>,
}

impl DgmVariantSampler {
    pub fn new() -> Self {
        Self {
            subsystem_targets: vec![
                ("cognitive_load".to_string(), 0.20),
                ("emergent_reasoning".to_string(), 0.25),
                ("personality_matrix".to_string(), 0.10),
                ("valence_axis".to_string(), 0.15),
                ("inner_critic".to_string(), 0.20),
                ("curiosity_drive".to_string(), 0.10),
            ],
            noise_level: 0.05,
            variants_per_cycle: 3,
            min_stepping_stone_score: 0.01,
            cycle: 0,
            // Phase 17.2: Mutation pool
            candidate_pool: Vec::new(),
            pool_index: 0,
            pool_max_size: 5,
            acceptance_map: HashMap::new(),
        }
    }

    /// Sample a target subsystem from the weighted pool.
    fn sample_subsystem(&self) -> &str {
        let total: f64 = self.subsystem_targets.iter().map(|(_, w)| w).sum();
        let mut r = rand::thread_rng().gen::<f64>() * total;
        for (name, weight) in &self.subsystem_targets {
            r -= weight;
            if r <= 0.0 {
                return name;
            }
        }
        self.subsystem_targets.last().map_or("", |(n, _)| n.as_str())
    }

    /// Generate variant proposals from archive stepping stones.
    ///
    /// Reads the archive's stepping stone records, extracts the most
    /// promising patterns, and generates `variants_per_cycle` proposals.
    /// Each proposal targets a random (weighted) subsystem with a gain
    /// estimate derived from archive stepping stone scores.
    ///
    /// Returns empty vec if archive is empty or writeback disabled.
    pub fn propose_variants(
        &mut self,
        archive: &HyperAgentArchive,
        cycle: u64,
    ) -> Vec<VariantProposal> {
        self.cycle = cycle;
        if archive.records.is_empty() {
            return Vec::new();
        }

        let mut rng = rand::thread_rng();
        let mut proposals: Vec<VariantProposal> = Vec::new();

        // Phase 17.2: Mix archive stepping stones with pool mutations
        // Strategy: every other cycle, use pool mutations instead of fresh archives
        let use_pool = !self.candidate_pool.is_empty() && cycle % 2 == 0;

        if use_pool {
            // Refill pool if running low
            self.refill_pool(archive, &mut rng);
            // Generate proposals from pool mutations
            for _ in 0..self.variants_per_cycle {
                if let Some(p) = self.mutate_from_pool(&mut rng) {
                    proposals.push(p);
                }
            }
        } else {
            // Standard: sample stepping stones from archive
            let stones = archive.sample_stepping_stones(self.variants_per_cycle * 2);
            if stones.is_empty() {
                return Vec::new();
            }
            let avg_stone_energy =
                archive.total_stepping_stone_energy() / (archive.records.len() as f64).max(1.0);

            for _ in 0..self.variants_per_cycle {
                let parent = stones[rng.gen_range(0..stones.len())];
                let parent_score = archive.stepping_stone_score();
                if parent_score < self.min_stepping_stone_score {
                    continue;
                }
                let subsystem = self.sample_subsystem().to_string();
                let estimated_gain =
                    (parent_score * 0.15 + rng.gen::<f64>() * self.noise_level).clamp(0.01, 0.3);
                let description = format!(
                    "dgm_variant: {} stepping_stone_score={:.3} archive_energy={:.3}",
                    subsystem, parent_score, avg_stone_energy,
                );
                let proposed_change = format!(
                    "adjust_{}_by_{:.3}_from_stepping_stone",
                    subsystem, estimated_gain,
                );
                proposals.push(VariantProposal {
                    description,
                    target_subsystem: subsystem,
                    proposed_change,
                    estimated_gain,
                    stepping_stone_score: parent_score,
                    parent_id: Some(parent.id),
                });
            }
        }

        // Phse 17.2: Populate pool from proposals for future mutations
        for p in &proposals {
            if !self
                .candidate_pool
                .iter()
                .any(|c| c.target_subsystem == p.target_subsystem)
            {
                if self.candidate_pool.len() < self.pool_max_size {
                    self.candidate_pool.push(CandidateEntry {
                        target_subsystem: p.target_subsystem.clone(),
                        base_gain: p.estimated_gain,
                        acceptance_count: 0,
                        rejection_count: 0,
                        priority: 0.1,
                    });
                }
            }
        }

        proposals
    }

    // ── Phase 17.2: Mutation pool management ──

    /// Record that a proposal targeting `subsystem` was accepted.
    /// Boosts priority for that subsystem in future mutations.
    pub fn record_acceptance(&mut self, subsystem: &str) {
        *self
            .acceptance_map
            .entry(subsystem.to_string())
            .or_insert(0) += 1;
        // Find baseline weight for this subsystem (no self-ref, just inline computation)
        let base = self
            .subsystem_targets
            .iter()
            .find(|(name, _)| name == subsystem)
            .map(|(_, w)| *w)
            .unwrap_or(0.1);
        for c in &mut self.candidate_pool {
            if c.target_subsystem == subsystem {
                c.acceptance_count += 1;
                let accept_bonus = (c.acceptance_count as f64).min(5.0) * 0.1;
                let reject_penalty = (c.rejection_count as f64).min(10.0) * 0.05;
                c.priority = (base + accept_bonus - reject_penalty).max(0.05);
            }
        }
    }

    /// Record that a proposal was rejected.
    pub fn record_rejection(&mut self, subsystem: &str) {
        let base = self
            .subsystem_targets
            .iter()
            .find(|(name, _)| name == subsystem)
            .map(|(_, w)| *w)
            .unwrap_or(0.1);
        for c in &mut self.candidate_pool {
            if c.target_subsystem == subsystem {
                c.rejection_count += 1;
                let accept_bonus = (c.acceptance_count as f64).min(5.0) * 0.1;
                let reject_penalty = (c.rejection_count as f64).min(10.0) * 0.05;
                c.priority = (base + accept_bonus - reject_penalty).max(0.05);
            }
        }
    }

    /// Mutate a proposal from the pool by tweaking its gain estimate.
    /// The pool entry is consumed and re-inserted with a new gain.
    fn mutate_from_pool(&mut self, rng: &mut impl Rng) -> Option<VariantProposal> {
        if self.candidate_pool.is_empty() {
            return None;
        }
        self.pool_index %= self.candidate_pool.len();
        let entry = &self.candidate_pool[self.pool_index];
        self.pool_index = (self.pool_index + 1) % self.candidate_pool.len();

        let gain_shift = (rng.gen::<f64>() - 0.5) * 0.1; // ±0.05 shift
        let new_gain = (entry.base_gain + gain_shift).clamp(0.01, 0.3);

        Some(VariantProposal {
            description: format!(
                "dgm_mutation: {} gain={:.3} base={:.3} priority={:.3}",
                entry.target_subsystem, new_gain, entry.base_gain, entry.priority,
            ),
            target_subsystem: entry.target_subsystem.clone(),
            proposed_change: format!(
                "adjust_{}_by_{:.3}_from_pool",
                entry.target_subsystem, new_gain
            ),
            estimated_gain: new_gain,
            stepping_stone_score: entry.priority,
            parent_id: None,
        })
    }

    /// Sync the acceptance map into the archive by recording successful
    /// subsystem targets as stepping stone feedback.
    pub fn acceptance_report(&self) -> String {
        if self.acceptance_map.is_empty() {
            return "acceptance_map: empty".to_string();
        }
        let parts: Vec<String> = self
            .acceptance_map
            .iter()
            .map(|(sub, count)| format!("{}:{}", sub, count))
            .collect();
        format!("acceptance_map: [{}]", parts.join(", "))
    }

    /// Refill the pool from archive stepping stones when it runs low.
    fn refill_pool(&mut self, archive: &HyperAgentArchive, rng: &mut impl Rng) {
        let need = self.pool_max_size.saturating_sub(self.candidate_pool.len());
        if need == 0 {
            return;
        }
        let stones = archive.sample_stepping_stones(need * 2);
        for _parent in &stones {
            if self.candidate_pool.len() >= self.pool_max_size {
                break;
            }
            let subsystem = self.sample_subsystem().to_string();
            let base_gain = (archive.stepping_stone_score() * 0.15
                + rng.gen::<f64>() * self.noise_level)
                .clamp(0.01, 0.3);
            let entry = CandidateEntry {
                target_subsystem: subsystem,
                base_gain,
                acceptance_count: 0,
                rejection_count: 0,
                priority: 0.1,
            };
            self.candidate_pool.push(entry);
        }
    }

    /// Number of variants proposed this cycle.
    pub fn pending_count(&self) -> usize {
        self.variants_per_cycle
    }
}

impl Default for DgmVariantSampler {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::neotrix::nt_mind::self_iterating::{
        HyperAgentArchive, HyperAgentRecord, ModificationTarget, SafetyCheckResult,
        SelectionConfig, SelfModificationProposal,
    };

    fn make_record(score: f64, novelty: f64) -> HyperAgentRecord {
        HyperAgentRecord {
            id: uuid::Uuid::new_v4(),
            parent_id: None,
            diffs_applied: Vec::new(),
            score: Some(score),
            novelty_score: novelty,
            latent_snapshot: vec![score],
            generation: 0,
            proposal: SelfModificationProposal {
                target: ModificationTarget::TaskAgent,
                diffs: Vec::new(),
                expected_impact: "test".into(),
                safety_check: SafetyCheckResult::Passed,
            },
        }
    }

    #[test]
    fn test_empty_archive_returns_empty() {
        let archive = HyperAgentArchive::new(SelectionConfig::default());
        let mut sampler = DgmVariantSampler::new();
        let proposals = sampler.propose_variants(&archive, 0);
        assert!(proposals.is_empty());
    }

    #[test]
    fn test_proposes_variants_from_archive() {
        let mut archive = HyperAgentArchive::new(SelectionConfig::default());
        for i in 0..5 {
            archive.add_record(make_record(0.3 + i as f64 * 0.1, 0.2));
        }
        let mut sampler = DgmVariantSampler::new();
        let proposals = sampler.propose_variants(&archive, 0);
        assert!(!proposals.is_empty());
        assert!(proposals.len() <= sampler.variants_per_cycle);
        for p in &proposals {
            assert!(p.estimated_gain > 0.0);
            assert!(!p.target_subsystem.is_empty());
            assert!(p.parent_id.is_some());
        }
    }

    #[test]
    fn test_gain_is_calibrated() {
        let mut archive = HyperAgentArchive::new(SelectionConfig::default());
        archive.add_record(make_record(0.9, 0.5));
        let mut sampler = DgmVariantSampler::new();
        let proposals = sampler.propose_variants(&archive, 0);
        for p in &proposals {
            assert!(p.estimated_gain >= 0.01);
            assert!(p.estimated_gain <= 0.3);
        }
    }

    #[test]
    fn test_subystem_pool_is_valid() {
        let sampler = DgmVariantSampler::new();
        let valid = [
            "cognitive_load",
            "emergent_reasoning",
            "personality_matrix",
            "valence_axis",
            "inner_critic",
            "curiosity_drive",
        ];
        for _ in 0..20 {
            let s = sampler.sample_subsystem();
            assert!(valid.contains(&s), "unknown subsystem: {}", s);
        }
    }

    #[test]
    fn test_default_config() {
        let sampler = DgmVariantSampler::default();
        assert_eq!(sampler.variants_per_cycle, 3);
    }
}
