use std::path::{Path, PathBuf};
use std::fs;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use walkdir::WalkDir;
use syn::{Attribute, File, Item, Meta};

#[derive(Debug)]
pub struct TestModule {
    pub file: PathBuf,
    pub mod_name: String,
    pub test_fns: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct NtSuite {
    pub name: String,
    pub description: String,
    pub tests: Vec<NtTest>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct NtTest {
    pub name: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imports: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub setup: Option<String>,
    pub code: String,
}

/// Parse a Rust file, find a #[test] function by name, and return
/// (imports_from_parent_module, setup_code_before_assertions, code_body).
pub fn extract_test_code(file_path: &Path, fn_name: &str) -> Result<(Vec<String>, Option<String>, String)> {
    let content = fs::read_to_string(file_path)
        .with_context(|| format!("Failed to read {}", file_path.display()))?;
    let parsed: File = syn::parse_file(&content)
        .with_context(|| format!("Failed to parse {}", file_path.display()))?;

    for item in &parsed.items {
        if let Item::Mod(m) = item {
            if !has_cfg_test(&m.attrs) && m.ident != "tests" {
                continue;
            }
            let items = m.content.as_ref()
                .map(|(_, items)| items)
                .context(format!("Module '{}' has no body (out-of-line)", m.ident))?;

            let imports = extract_import_paths(items);

            let found = items.iter().any(|inner| {
                if let Item::Fn(f) = inner {
                    is_test_fn(&f.attrs) && f.sig.ident == fn_name
                } else {
                    false
                }
            });

            if found {
                let body = extract_function_body(&content, fn_name)?;
                let (setup, code) = split_body_text(&body);
                return Ok((imports, setup, code));
            }
        }
    }

    anyhow::bail!("Test function '{}' not found in {}", fn_name, file_path.display());
}

pub fn build_nt_suite(file: &Path, mod_name: &str) -> Result<NtSuite> {
    let content = fs::read_to_string(file)
        .with_context(|| format!("Failed to read {}", file.display()))?;
    let parsed: File = syn::parse_file(&content)
        .with_context(|| format!("Failed to parse {}", file.display()))?;

    for item in &parsed.items {
        if let Item::Mod(m) = item {
            if m.ident != mod_name {
                continue;
            }
            let items = m.content.as_ref()
                .map(|(_, items)| items)
                .context(format!("Module '{}' has no body (out-of-line)", mod_name))?;

            let module_imports = extract_import_paths(items);
            let suite_name = derive_suite_name(file, mod_name);
            let mut tests = Vec::new();

            for inner in items {
                if let Item::Fn(f) = inner {
                    if is_test_fn(&f.attrs) {
                        let fn_name = f.sig.ident.to_string();
                        let body = extract_function_body(&content, &fn_name)?;
                        let (setup, code) = split_body_text(&body);
                        tests.push(NtTest {
                            name: fn_name.clone(),
                            description: fn_name_to_description(&fn_name),
                            imports: Some(module_imports.clone()),
                            setup,
                            code,
                        });
                    }
                }
            }

            return Ok(NtSuite {
                name: suite_name,
                description: format!("{} — auto-generated by nt-migrate", mod_name),
                tests,
            });
        }
    }

    anyhow::bail!("Test module '{}' not found in {}", mod_name, file.display());
}

pub fn extract_function_body(source: &str, fn_name: &str) -> Result<String> {
    let pattern = format!("fn {}(", fn_name);
    let fn_start = source.find(&pattern)
        .ok_or_else(|| anyhow::anyhow!("Function '{}' not found in source", fn_name))?;

    let after_fn = &source[fn_start..];
    let brace_open = after_fn.find('{')
        .ok_or_else(|| anyhow::anyhow!("No body for function '{}'", fn_name))?;
    let body_start = fn_start + brace_open + 1;

    let mut depth: i32 = 1;
    let mut body_end = body_start;
    for (i, c) in source[body_start..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    body_end = body_start + i;
                    break;
                }
            }
            _ => {}
        }
    }

    if depth != 0 {
        anyhow::bail!("Unmatched braces in function '{}'", fn_name);
    }

    Ok(source[body_start..body_end].to_string())
}

pub fn clean_body_text(body: &str) -> String {
    let body = body.trim_start_matches('\n').trim_start_matches('\r');

    let lines: Vec<&str> = body.lines().collect();
    if lines.is_empty() {
        return String::new();
    }

    let min_indent = lines.iter()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);

    if min_indent == 0 {
        return body.trim_end().to_string();
    }

    lines.iter()
        .map(|l| {
            if l.len() >= min_indent {
                &l[min_indent..]
            } else {
                l.trim()
            }
        })
        .collect::<Vec<&str>>()
        .join("\n")
        .trim_end()
        .to_string()
}

pub fn split_body_text(body: &str) -> (Option<String>, String) {
    let body = clean_body_text(body);
    let mut setup_lines: Vec<&str> = Vec::new();
    let mut code_lines: Vec<&str> = Vec::new();
    let mut found_assertion = false;

    for line in body.lines() {
        let trimmed = line.trim();
        if !found_assertion && !trimmed.is_empty() && trimmed.contains("assert") {
            found_assertion = true;
        }
        if found_assertion {
            code_lines.push(line);
        } else {
            setup_lines.push(line);
        }
    }

    if !found_assertion && !setup_lines.is_empty() {
        code_lines = setup_lines;
        setup_lines = Vec::new();
    }

    let setup = if setup_lines.is_empty() {
        None
    } else {
        Some(setup_lines.join("\n"))
    };

    (setup, code_lines.join("\n"))
}

pub fn extract_import_paths(items: &[syn::Item]) -> Vec<String> {
    items.iter()
        .filter_map(|item| {
            if let Item::Use(u) = item {
                let s = quote::quote!(#u).to_string();
                let s = s.trim().to_string();
                let path = s
                    .strip_prefix("use ")
                    .unwrap_or(&s)
                    .strip_suffix(';')
                    .unwrap_or(&s)
                    .trim()
                    .to_string();
                Some(normalize_import_path(&path))
            } else {
                None
            }
        })
        .collect()
}

pub fn normalize_import_path(path: &str) -> String {
    let parts: Vec<&str> = path.split("::").collect();
    let normalized: Vec<String> = parts.iter()
        .map(|s| {
            let s = s.trim();
            if s.starts_with('{') && s.ends_with('}') {
                let inner = &s[1..s.len()-1];
                let items: Vec<String> = inner.split(',')
                    .map(|i| i.trim().to_string())
                    .collect();
                format!("{{{}}}", items.join(", "))
            } else {
                s.to_string()
            }
        })
        .collect();
    normalized.join("::")
}

pub fn has_cfg_test(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        if !attr.path().is_ident("cfg") {
            return false;
        }
        if let Meta::List(list) = &attr.meta {
            list.tokens.to_string().contains("test")
        } else {
            false
        }
    })
}

pub fn is_test_fn(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().segments.last()
            .map(|s| s.ident == "test")
            .unwrap_or(false)
    })
}

pub fn extract_test_fns_from_items(items: &[Item]) -> Vec<String> {
    let mut fns = Vec::new();
    for item in items {
        match item {
            Item::Fn(f) if is_test_fn(&f.attrs) => {
                fns.push(f.sig.ident.to_string());
            }
            Item::Mod(m) => {
                if let Some((_, nested)) = &m.content {
                    fns.extend(extract_test_fns_from_items(nested));
                }
            }
            _ => {}
        }
    }
    fns
}

pub fn fn_name_to_description(name: &str) -> String {
    let name = name.strip_prefix("test_").unwrap_or(name);
    let words: Vec<&str> = name.split('_').collect();
    if words.is_empty() {
        return String::new();
    }
    let mut result = String::new();
    for (i, w) in words.iter().enumerate() {
        if i > 0 {
            result.push(' ');
        }
        if w.len() <= 4 && w.chars().all(|c| c.is_ascii_uppercase()) {
            result.push_str(w);
        } else if i == 0 {
            let mut chars = w.chars();
            match chars.next() {
                None => {}
                Some(c) => {
                    result.push(c.to_ascii_uppercase());
                    result.push_str(chars.as_str());
                }
            }
        } else {
            result.push_str(w);
        }
    }
    result
}

pub fn derive_suite_name(file: &Path, mod_name: &str) -> String {
    if let Some(stem) = file.file_stem() {
        let stem = stem.to_string_lossy();
        stem.replace('-', "_")
    } else {
        mod_name.to_string()
    }
}

pub fn find_suites_dir() -> Result<PathBuf> {
    let candidates = [
        Path::new("neotrix-core/test_suites"),
        Path::new("../neotrix-core/test_suites"),
    ];
    for c in &candidates {
        if c.is_dir() {
            return Ok(c.to_path_buf());
        }
    }
    anyhow::bail!("Cannot find test_suites/ directory (looked: {:?}). Run from workspace root.", candidates);
}

pub fn get_pos_arg<'a>(args: &'a [String], idx: usize) -> Option<&'a Path> {
    args.get(idx).map(Path::new)
}

pub fn parse_key_value_args(args: &[String], key: &str) -> Result<(PathBuf, String)> {
    if args.len() < 3 || args[1] != key {
        anyhow::bail!("Usage: nt-migrate ... <file.rs> {} <mod_name>", key);
    }
    Ok((PathBuf::from(&args[0]), args[2].clone()))
}

pub fn parse_named_arg<'a>(args: &'a [String], key: &str) -> Option<&'a str> {
    args.iter()
        .position(|a| a == key)
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
}

pub fn scan_for_test_modules(path: &Path) -> Result<Vec<TestModule>> {
    let mut modules = Vec::new();

    for entry in WalkDir::new(path).into_iter().filter_entry(|e| {
        !e.file_name().to_string_lossy().starts_with('.')
    }) {
        let entry = entry.with_context(|| "Error walking directory")?;
        if !entry.file_type().is_file() {
            continue;
        }
        let p = entry.path();
        if p.extension().map(|ext| ext == "rs").unwrap_or(false) {
            let content = match fs::read_to_string(p) {
                Ok(c) => c,
                Err(_) => continue,
            };
            let parsed: File = match syn::parse_file(&content) {
                Ok(f) => f,
                Err(_) => continue,
            };

            for item in &parsed.items {
                if let Item::Mod(m) = item {
                    if has_cfg_test(&m.attrs) || m.ident == "tests" {
                        let test_fns = extract_test_fns_from_items(
                            m.content.as_ref().map(|(_, items)| items).unwrap_or(&vec![])
                        );
                        if !test_fns.is_empty() {
                            modules.push(TestModule {
                                file: p.to_path_buf(),
                                mod_name: m.ident.to_string(),
                                test_fns,
                            });
                        }
                    }
                }
            }

            let free_fns: Vec<String> = parsed.items.iter()
                .filter_map(|item| {
                    if let Item::Fn(f) = item {
                        if is_test_fn(&f.attrs) {
                            Some(f.sig.ident.to_string())
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                })
                .collect();

            if !free_fns.is_empty() {
                modules.push(TestModule {
                    file: p.to_path_buf(),
                    mod_name: "(root)".to_string(),
                    test_fns: free_fns,
                });
            }
        }
    }

    Ok(modules)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── clean_body_text ─────────────────────────────────

    #[test]
    fn test_clean_body_text_empty() {
        assert_eq!(clean_body_text(""), "");
    }

    #[test]
    fn test_clean_body_text_no_indent() {
        let body = "let x = 1;\nassert_eq!(x, 1);";
        let cleaned = clean_body_text(body);
        assert_eq!(cleaned, body);
    }

    #[test]
    fn test_clean_body_text_removes_common_indent() {
        let body = "    let x = 1;\n    assert_eq!(x, 1);";
        let cleaned = clean_body_text(body);
        assert_eq!(cleaned, "let x = 1;\nassert_eq!(x, 1);");
    }

    #[test]
    fn test_clean_body_text_mixed_indent() {
        let body = "        let x = 1;\n            assert_eq!(x, 1);";
        let cleaned = clean_body_text(body);
        // min indent = 8 (first line), strips 8 from both lines
        assert_eq!(cleaned, "let x = 1;\n    assert_eq!(x, 1);");
    }

    #[test]
    fn test_clean_body_text_skips_empty_lines() {
        let body = "    let x = 1;\n\n    assert_eq!(x, 1);";
        let cleaned = clean_body_text(body);
        assert_eq!(cleaned, "let x = 1;\n\nassert_eq!(x, 1);");
    }

    #[test]
    fn test_clean_body_trims_trailing_newlines() {
        let body = "    hello\n    world\n\n\n";
        let cleaned = clean_body_text(body);
        assert_eq!(cleaned, "hello\nworld");
    }

    #[test]
    fn test_clean_strips_leading_newlines() {
        let body = "\n\n\n    hello\n    world";
        let cleaned = clean_body_text(body);
        assert_eq!(cleaned, "hello\nworld");
    }

    // ── split_body_text ─────────────────────────────────

    #[test]
    fn test_split_body_text_basic() {
        let body = "let x = 1;\nassert_eq!(x, 1);";
        let (setup, code) = split_body_text(body);
        assert_eq!(setup, Some("let x = 1;".into()));
        assert_eq!(code, "assert_eq!(x, 1);");
    }

    #[test]
    fn test_split_body_text_no_assertion() {
        let body = "let x = 1;\nlet y = 2;";
        let (setup, code) = split_body_text(body);
        assert_eq!(setup, None);
        assert_eq!(code, "let x = 1;\nlet y = 2;");
    }

    #[test]
    fn test_split_body_text_empty() {
        let (setup, code) = split_body_text("");
        assert_eq!(setup, None);
        assert_eq!(code, "");
    }

    #[test]
    fn test_split_body_text_assertion_in_setup() {
        let body = "let v = vec![1, 2];\nassert!(!v.is_empty());\nlet result = v[0];";
        let (setup, code) = split_body_text(body);
        assert_eq!(setup, Some("let v = vec![1, 2];".into()));
        assert_eq!(code, "assert!(!v.is_empty());\nlet result = v[0];");
    }

    // ── normalize_import_path ───────────────────────────

    #[test]
    fn test_normalize_simple_path() {
        assert_eq!(normalize_import_path("std::collections::HashMap"), "std::collections::HashMap");
    }

    #[test]
    fn test_normalize_braced_path() {
        let result = normalize_import_path("std::collections::{HashMap, HashSet}");
        assert_eq!(result, "std::collections::{HashMap, HashSet}");
    }

    #[test]
    fn test_normalize_triple_brace() {
        let result = normalize_import_path("serde::{Deserialize, Serialize}");
        assert_eq!(result, "serde::{Deserialize, Serialize}");
    }

    // ── fn_name_to_description ──────────────────────────

    #[test]
    fn test_fn_name_to_description_basic() {
        assert_eq!(fn_name_to_description("test_hello_world"), "Hello world");
    }

    #[test]
    fn test_fn_name_to_description_no_prefix() {
        assert_eq!(fn_name_to_description("hello_world"), "Hello world");
    }

    #[test]
    fn test_fn_name_to_description_single_word() {
        assert_eq!(fn_name_to_description("test_basic"), "Basic");
    }

    #[test]
    fn test_fn_name_to_description_acronym() {
        // First word is capitalized only, acronym check only for i>0 words
        assert_eq!(fn_name_to_description("test_json_roundtrip"), "Json roundtrip");
    }

    #[test]
    fn test_fn_name_to_description_empty() {
        assert_eq!(fn_name_to_description(""), "");
    }

    #[test]
    fn test_fn_name_to_description_short_lowercase() {
        assert_eq!(fn_name_to_description("test_is_ok"), "Is ok");
    }

    // ── derive_suite_name ───────────────────────────────

    #[test]
    fn test_derive_suite_name_with_stem() {
        let path = Path::new("src/lib.rs");
        assert_eq!(derive_suite_name(path, "tests"), "lib");
    }

    #[test]
    fn test_derive_suite_name_hyphen_to_underscore() {
        let path = Path::new("src/my-module.rs");
        assert_eq!(derive_suite_name(path, "tests"), "my_module");
    }

    #[test]
    fn test_derive_suite_name_no_stem() {
        let path = Path::new("/");
        assert_eq!(derive_suite_name(path, "my_mod"), "my_mod");
    }

    // ── extract_function_body ───────────────────────────

    #[test]
    fn test_extract_function_body_simple() {
        let source = "fn foo() {\n    let x = 1;\n    assert_eq!(x, 1);\n}";
        let body = extract_function_body(source, "foo").unwrap();
        assert_eq!(body, "\n    let x = 1;\n    assert_eq!(x, 1);\n");
    }

    #[test]
    fn test_extract_function_body_nested_braces() {
        let source = "fn bar() {\n    if true {\n        let y = 2;\n    }\n    assert_eq!(1, 1);\n}";
        let body = extract_function_body(source, "bar").unwrap();
        assert!(body.contains("if true {"));
        assert!(body.contains("assert_eq!(1, 1);"));
    }

    #[test]
    fn test_extract_function_body_no_braces() {
        let source = "fn empty() {}";
        let body = extract_function_body(source, "empty").unwrap();
        assert_eq!(body, "");
    }

    #[test]
    fn test_extract_function_body_not_found() {
        let source = "fn foo() {}";
        let result = extract_function_body(source, "nonexistent");
        assert!(result.is_err());
    }

    #[test]
    fn test_extract_function_body_unmatched_braces() {
        let source = "fn broken() {\n    if true {\n        let x = 1;\n    assert!(!x);\n";
        let result = extract_function_body(source, "broken");
        assert!(result.is_err());
    }

    // ── extract_test_code ───────────────────────────────

    fn write_temp_rs(content: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "nt_migrate_test_{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("test_file.rs");
        std::fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn test_extract_test_code_found() {
        let content = r#"
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello() {
        let map = std::collections::HashMap::<String, String>::new();
        assert!(map.is_empty());
    }

    #[test]
    fn test_world() {
        let x = 1;
        assert_eq!(x, 1);
    }
}
"#;
        let path = write_temp_rs(content);
        let (imports, setup, code) = extract_test_code(&path, "test_hello").unwrap();
        assert_eq!(imports, vec!["super::*"]);
        assert!(setup.as_deref().unwrap().contains("HashMap"));
        assert!(code.contains("assert!(map.is_empty())"));

        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn test_extract_test_code_not_found() {
        let content = r#"
#[cfg(test)]
mod tests {
    #[test]
    fn test_existing() {}
}
"#;
        let path = write_temp_rs(content);
        let result = extract_test_code(&path, "test_missing");
        assert!(result.is_err());

        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    // ── build_nt_suite ──────────────────────────────────

    #[test]
    fn test_build_nt_suite() {
        let content = r#"
use std::vec::Vec;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add() {
        let a = 1;
        assert_eq!(a + 1, 2);
    }

    #[test]
    fn test_sub() {
        let b = 5;
        assert_eq!(b - 3, 2);
    }
}
"#;
        let path = write_temp_rs(content);
        let suite = build_nt_suite(&path, "tests").unwrap();
        assert_eq!(suite.name, "test_file");
        assert_eq!(suite.tests.len(), 2);
        assert_eq!(suite.tests[0].name, "test_add");
        assert_eq!(suite.tests[1].name, "test_sub");
        assert!(suite.tests[0].imports.as_ref().unwrap().contains(&"super::*".into()));

        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn test_build_nt_suite_module_not_found() {
        let content = "fn main() {}";
        let path = write_temp_rs(content);
        let result = build_nt_suite(&path, "nonexistent");
        assert!(result.is_err());

        let _ = std::fs::remove_dir_all(path.parent().unwrap());
    }

    // ── scan_for_test_modules ───────────────────────────

    fn write_temp_dir(files: &[(&str, &str)]) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "nt_migrate_scan_{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        for (name, content) in files {
            std::fs::write(dir.join(name), content).unwrap();
        }
        dir
    }

    #[test]
    fn test_scan_for_test_modules_finds_tests() {
        let dir = write_temp_dir(&[
            ("lib.rs", r#"
#[cfg(test)]
mod tests {
    #[test]
    fn test_a() {}
    #[test]
    fn test_b() {}
}
"#),
            ("other.rs", r#"
fn helper() {}
"#),
        ]);
        let modules = scan_for_test_modules(&dir).unwrap();
        assert_eq!(modules.len(), 1);
        assert_eq!(modules[0].mod_name, "tests");
        assert_eq!(modules[0].test_fns, vec!["test_a", "test_b"]);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_scan_for_test_modules_empty_dir() {
        let dir = write_temp_dir(&[]);
        let modules = scan_for_test_modules(&dir).unwrap();
        assert!(modules.is_empty());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_scan_for_test_modules_no_tests() {
        let dir = write_temp_dir(&[
            ("lib.rs", "pub fn add(a: i32, b: i32) -> i32 { a + b }"),
            ("mod.rs", "pub mod lib;"),
        ]);
        let modules = scan_for_test_modules(&dir).unwrap();
        assert!(modules.is_empty());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_scan_for_test_modules_free_fns() {
        let dir = write_temp_dir(&[
            ("tests.rs", r#"
#[test]
fn integration_test() {
    assert_eq!(2, 2);
}
"#),
        ]);
        let modules = scan_for_test_modules(&dir).unwrap();
        let has_root = modules.iter().any(|m| m.mod_name == "(root)" && m.test_fns == vec!["integration_test"]);
        assert!(has_root, "free-standing test functions should be found as root");

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ── NtSuite / NtTest serde ──────────────────────────

    #[test]
    fn test_nt_suite_yaml_roundtrip() {
        let suite = NtSuite {
            name: "my_module".into(),
            description: "Tests for my_module".into(),
            tests: vec![
                NtTest {
                    name: "test_a".into(),
                    description: "Test A".into(),
                    imports: Some(vec!["std::collections::HashMap".into()]),
                    setup: Some("let map = HashMap::new();".into()),
                    code: "assert!(map.is_empty());".into(),
                },
            ],
        };
        let yaml = serde_yaml::to_string(&suite).unwrap();
        let deserialized: NtSuite = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(deserialized.name, "my_module");
        assert_eq!(deserialized.tests.len(), 1);
        assert_eq!(deserialized.tests[0].name, "test_a");
        assert_eq!(deserialized.tests[0].imports, Some(vec!["std::collections::HashMap".into()]));
    }

    #[test]
    fn test_nt_test_skip_optional_fields() {
        let test = NtTest {
            name: "test_b".into(),
            description: "Test B".into(),
            imports: None,
            setup: None,
            code: "assert!(true);".into(),
        };
        let yaml = serde_yaml::to_string(&test).unwrap();
        assert!(!yaml.contains("imports"));
        assert!(!yaml.contains("setup"));
        let deserialized: NtTest = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(deserialized.name, "test_b");
        assert!(deserialized.imports.is_none());
    }
}
