//! 能力路由表 `CAPABILITY_ROUTES` + 指令拆解入口（由 `dispatch.rs` 纯搬移拆分，行为零变更）

use super::nt_dispatch_types::ConsciousTask;

// ─── 能力路由表 ──────────────────────────────────────────────────────────────

const CAPABILITY_ROUTES: &[(&str, &str, &str, &str)] = &[
    ("excel", "xlsx_consolidation", "NT-ACT", "CodeAnalyzer"),
    ("表格", "xlsx_consolidation", "NT-ACT", "CodeAnalyzer"),
    ("价格表", "xlsx_consolidation", "NT-ACT", "CodeAnalyzer"),
    ("统一", "xlsx_consolidation", "NT-ACT", "CodeAnalyzer"),
    ("合并", "data_merge", "NT-ACT", "KnowledgeIntegrator"),
    ("文件", "file_parsing", "NT-WORLD", "CodeAnalyzer"),
    ("解析", "file_parsing", "NT-WORLD", "CodeAnalyzer"),
    ("提取", "content_extraction", "NT-WORLD", "CodeAnalyzer"),
    ("pdf编辑", "pdf_edit", "NT-ACT", "CodeAnalyzer"),
    ("pdf编辑:", "pdf_edit", "NT-ACT", "CodeAnalyzer"),
    ("编辑pdf", "pdf_edit", "NT-ACT", "CodeAnalyzer"),
    ("图片转换", "image_convert", "NT-ACT", "CodeAnalyzer"),
    ("图像转换", "image_convert", "NT-ACT", "CodeAnalyzer"),
    ("格式转换", "image_convert", "NT-ACT", "CodeAnalyzer"),
    ("提取目录", "dir_extract", "NT-WORLD", "CodeAnalyzer"),
    ("目录提取", "dir_extract", "NT-WORLD", "CodeAnalyzer"),
    ("批量提取", "dir_extract", "NT-WORLD", "CodeAnalyzer"),
    ("合并pdf", "pdf_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并PDF", "pdf_merge", "NT-ACT", "CodeAnalyzer"),
    ("pdf合并", "pdf_merge", "NT-ACT", "CodeAnalyzer"),
    ("PDF合并", "pdf_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并文档", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("文档合并", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并word", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并docx", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并ppt", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("合并pptx", "doc_merge", "NT-ACT", "CodeAnalyzer"),
    ("检索", "hybrid_retrieval", "NT-MEMORY", "KnowledgeRetriever"),
    ("查询", "hybrid_retrieval", "NT-MEMORY", "KnowledgeRetriever"),
    ("搜索", "hybrid_retrieval", "NT-MEMORY", "KnowledgeRetriever"),
    ("吸收", "skill_crystallize", "NT-MIND", "KnowledgeIntegrator"),
    ("蒸馏", "skill_crystallize", "NT-MIND", "KnowledgeIntegrator"),
    ("测试", "tdd", "NT-MIND", "Planner"),
    ("重构", "code_refactor", "NT-ACT", "CodeAnalyzer"),
    ("审查", "security_audit", "NT-SHIELD", "RiskAssessor"),
    ("审计", "security_audit", "NT-SHIELD", "RiskAssessor"),
    ("安全", "security_governance", "NT-SHIELD", "RiskAssessor"),
    ("架构", "architecture_decision", "NT-CORE", "Planner"),
    ("设计", "architecture_decision", "NT-CORE", "Planner"),
    ("意识", "consciousness_tree", "NT-CORE", "ReflectionEngine"),
    ("元认知", "meta_cognition", "NT-META", "MetaCognitionAnalyst"),
    ("复盘", "meta_cognition", "NT-META", "MetaCognitionAnalyst"),
    ("反思", "meta_cognition", "NT-META", "MetaCognitionAnalyst"),
    ("诊断", "root_cause_method", "NT-REPAIR", "AnomalyDetector"),
    ("报错", "root_cause_method", "NT-REPAIR", "AnomalyDetector"),
    ("构建失败", "build_hygiene", "NT-REPAIR", "AnomalyDetector"),
    ("爬虫", "unified_crawler", "NT-WORLD", "PatternMatcher"),
    ("抓取", "unified_crawler", "NT-WORLD", "PatternMatcher"),
    ("前端", "frontend_ui", "NT-IO", "CreativityGenerator"),
    ("界面", "frontend_ui", "NT-IO", "CreativityGenerator"),
    ("经验", "experience_absorb", "NT-MEMORY", "KnowledgeIntegrator"),
    ("智能合并", "collection_merge", "NT-ACT", "CodeAnalyzer"),
    ("混合合并", "collection_merge", "NT-ACT", "CodeAnalyzer"),
    ("编辑表格", "xlsx_edit", "NT-ACT", "CodeAnalyzer"),
    ("单元格", "xlsx_edit", "NT-ACT", "CodeAnalyzer"),
    ("读取结构", "structured_read", "NT-WORLD", "CodeAnalyzer"),
    ("读取json", "structured_read", "NT-WORLD", "CodeAnalyzer"),
    ("读取yaml", "structured_read", "NT-WORLD", "CodeAnalyzer"),
    ("写入json", "json_write", "NT-ACT", "CodeAnalyzer"),
    ("保存json", "json_write", "NT-ACT", "CodeAnalyzer"),
    ("pdf图片统计", "pdf_image_stats", "NT-WORLD", "CodeAnalyzer"),
    ("pdf图像信息", "pdf_image_stats", "NT-WORLD", "CodeAnalyzer"),
    ("pdf提取图片", "pdf_extract_images", "NT-ACT", "CodeAnalyzer"),
    ("进化", "seal_iterate", "NT-MIND", "KnowledgeIntegrator"),
    ("迭代", "seal_iterate", "NT-MIND", "KnowledgeIntegrator"),
    ("seal_distill", "seal_distill", "NT-MIND", "KnowledgeIntegrator"),
    ("seal_iterate", "seal_iterate", "NT-MIND", "KnowledgeIntegrator"),
    ("pipeline", "seal_distill", "NT-MIND", "KnowledgeIntegrator"),
    ("自我评估", "self_model_tick", "NT-CORE", "ReflectionEngine"),
    ("能力评估", "self_model_tick", "NT-CORE", "ReflectionEngine"),
    ("认知健康", "metacog_evaluate", "NT-CORE", "ReflectionEngine"),
    ("self_model_tick", "self_model_tick", "NT-CORE", "ReflectionEngine"),
    ("self", "self_model_tick", "NT-CORE", "ReflectionEngine"),
    ("model", "self_model_tick", "NT-CORE", "ReflectionEngine"),
    ("元观察", "meta_observe", "NT-META", "MetaCognitionAnalyst"),
    ("质量扫描", "sentrux_scan", "NT-META", "MetaCognitionAnalyst"),
    ("代码质量", "sentrux_scan", "NT-META", "MetaCognitionAnalyst"),
    ("构建健康", "build_watchdog", "NT-META", "MetaCognitionAnalyst"),
    ("构建检查", "build_watchdog", "NT-META", "MetaCognitionAnalyst"),
    ("meta_observe", "meta_observe", "NT-META", "MetaCognitionAnalyst"),
    ("observe", "meta_observe", "NT-META", "MetaCognitionAnalyst"),
    ("monitor", "meta_observe", "NT-META", "MetaCognitionAnalyst"),
    ("安全审计", "shield_audit", "NT-SHIELD", "RiskAssessor"),
    ("攻击检测", "shield_audit", "NT-SHIELD", "RiskAssessor"),
    ("漏洞扫描", "agentic_scan", "NT-SHIELD", "RiskAssessor"),
    ("安全扫描", "agentic_scan", "NT-SHIELD", "RiskAssessor"),
    ("shield_audit", "shield_audit", "NT-SHIELD", "RiskAssessor"),
    ("shield", "shield_audit", "NT-SHIELD", "RiskAssessor"),
    ("security", "shield_audit", "NT-SHIELD", "RiskAssessor"),
    ("隐私", "privacy_mask", "NT-SHIELD", "RiskAssessor"),
    ("脱敏", "privacy_mask", "NT-SHIELD", "RiskAssessor"),
    ("隐私遮罩", "privacy_mask", "NT-SHIELD", "RiskAssessor"),
    ("privacy_mask", "privacy_mask", "NT-SHIELD", "RiskAssessor"),
    ("证据扫描", "evidence_scan", "NT-SHIELD", "RiskAssessor"),
    ("证据安全", "evidence_scan", "NT-SHIELD", "RiskAssessor"),
    ("evidence_scan", "evidence_scan", "NT-SHIELD", "RiskAssessor"),
    ("技能进化", "skill_evolution", "NT-MIND", "KnowledgeIntegrator"),
    ("技能演进", "skill_evolution", "NT-MIND", "KnowledgeIntegrator"),
    ("skill_evolution", "skill_evolution", "NT-MIND", "KnowledgeIntegrator"),
    ("经验桥接", "experience_bridge", "NT-MEMORY", "KnowledgeIntegrator"),
    ("经验知识", "experience_bridge", "NT-MEMORY", "KnowledgeIntegrator"),
    ("experience_bridge", "experience_bridge", "NT-MEMORY", "KnowledgeIntegrator"),
    ("视觉一致性", "visual_consistency", "NT-CORE", "ReflectionEngine"),
    ("visual_consistency", "visual_consistency", "NT-CORE", "ReflectionEngine"),
    ("风格分析", "style_harmonization", "NT-CORE", "ReflectionEngine"),
    ("风格统一", "style_harmonization", "NT-CORE", "ReflectionEngine"),
    ("style_harmonization", "style_harmonization", "NT-CORE", "ReflectionEngine"),
    ("叙事结构", "narrative_structuring", "NT-CORE", "ReflectionEngine"),
    ("分镜拆解", "narrative_structuring", "NT-CORE", "ReflectionEngine"),
    ("narrative_structuring", "narrative_structuring", "NT-CORE", "ReflectionEngine"),
    ("模型选择", "model_selection", "NT-CORE", "ReflectionEngine"),
    ("选模型", "model_selection", "NT-CORE", "ReflectionEngine"),
    ("model_selection", "model_selection", "NT-CORE", "ReflectionEngine"),
    ("时序连续", "temporal_continuity", "NT-ACT", "CodeAnalyzer"),
    ("帧间连续", "temporal_continuity", "NT-ACT", "CodeAnalyzer"),
    ("镜头衔接", "temporal_continuity", "NT-ACT", "CodeAnalyzer"),
    ("temporal_continuity", "temporal_continuity", "NT-ACT", "CodeAnalyzer"),
    ("shot_continuity", "temporal_continuity", "NT-ACT", "CodeAnalyzer"),
    ("资源预算", "resource_budget", "NT-ACT", "CodeAnalyzer"),
    ("成本控制", "resource_budget", "NT-ACT", "CodeAnalyzer"),
    ("token预算", "resource_budget", "NT-ACT", "CodeAnalyzer"),
    ("resource_budget", "resource_budget", "NT-ACT", "CodeAnalyzer"),
    ("cost_manager", "resource_budget", "NT-ACT", "CodeAnalyzer"),
    ("并行任务", "parallel_task", "NT-ACT", "CodeAnalyzer"),
    ("任务调度", "parallel_task", "NT-ACT", "CodeAnalyzer"),
    ("gpu调度", "parallel_task", "NT-ACT", "CodeAnalyzer"),
    ("parallel_task", "parallel_task", "NT-ACT", "CodeAnalyzer"),
    ("task_scheduler", "parallel_task", "NT-ACT", "CodeAnalyzer"),
    ("检查点", "checkpoint_persistence", "NT-ACT", "CodeAnalyzer"),
    ("断点续传", "checkpoint_persistence", "NT-ACT", "CodeAnalyzer"),
    ("状态快照", "checkpoint_persistence", "NT-ACT", "CodeAnalyzer"),
    ("checkpoint_persistence", "checkpoint_persistence", "NT-ACT", "CodeAnalyzer"),
    ("checkpoint", "checkpoint_persistence", "NT-ACT", "CodeAnalyzer"),
    ("知识库", "knowledge_base", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb操作", "knowledge_base", "NT-MEMORY", "KnowledgeRetriever"),
    ("knowledge_base", "knowledge_base", "NT-MEMORY", "KnowledgeRetriever"),
    ("数据库", "knowledge_base", "NT-MEMORY", "KnowledgeRetriever"),
    ("记忆整合", "memory_consolidation", "NT-MIND", "KnowledgeIntegrator"),
    ("记忆压缩", "memory_consolidation", "NT-MIND", "KnowledgeIntegrator"),
    ("记忆巩固", "memory_consolidation", "NT-MIND", "KnowledgeIntegrator"),
    ("memory_consolidation", "memory_consolidation", "NT-MIND", "KnowledgeIntegrator"),
    ("consolidate", "memory_consolidation", "NT-MIND", "KnowledgeIntegrator"),
    ("流式优化", "streaming_optimization", "NT-IO", "CreativityGenerator"),
    ("流式传输", "streaming_optimization", "NT-IO", "CreativityGenerator"),
    ("streaming_optimization", "streaming_optimization", "NT-IO", "CreativityGenerator"),
    ("stream", "streaming_optimization", "NT-IO", "CreativityGenerator"),
    ("流式", "streaming_optimization", "NT-IO", "CreativityGenerator"),
    ("模型路由", "model_routing", "NT-IO", "CreativityGenerator"),
    ("模型选择", "model_routing", "NT-IO", "CreativityGenerator"),
    ("provider", "model_routing", "NT-IO", "CreativityGenerator"),
    ("model_routing", "model_routing", "NT-IO", "CreativityGenerator"),
    ("负载均衡", "model_routing", "NT-IO", "CreativityGenerator"),
    ("人脸一致", "face_consistency", "NT-CORE", "ReflectionEngine"),
    ("面部一致", "face_consistency", "NT-CORE", "ReflectionEngine"),
    ("face_consistency", "face_consistency", "NT-CORE", "ReflectionEngine"),
    ("分镜提取", "storyboard_extract", "NT-CORE", "ReflectionEngine"),
    ("分镜生成", "storyboard_extract", "NT-CORE", "ReflectionEngine"),
    ("storyboard", "storyboard_extract", "NT-CORE", "ReflectionEngine"),
    ("验证器", "verifier_agent", "NT-META", "MetaCognitionAnalyst"),
    ("vlm验证", "verifier_agent", "NT-META", "MetaCognitionAnalyst"),
    ("验证循环", "verifier_agent", "NT-META", "MetaCognitionAnalyst"),
    ("verifier", "verifier_agent", "NT-META", "MetaCognitionAnalyst"),
    ("分层qa", "layered_qa", "NT-META", "MetaCognitionAnalyst"),
    ("分层质检", "layered_qa", "NT-META", "MetaCognitionAnalyst"),
    ("质量检查", "layered_qa", "NT-META", "MetaCognitionAnalyst"),
    ("layered_qa", "layered_qa", "NT-META", "MetaCognitionAnalyst"),
    ("质量控制", "quality_control", "NT-META", "MetaCognitionAnalyst"),
    ("审核流水线", "quality_control", "NT-META", "MetaCognitionAnalyst"),
    ("quality_control", "quality_control", "NT-META", "MetaCognitionAnalyst"),
    ("质量门禁", "quality_gate", "NT-META", "MetaCognitionAnalyst"),
    ("发布门禁", "quality_gate", "NT-META", "MetaCognitionAnalyst"),
    ("quality_gate", "quality_gate", "NT-META", "MetaCognitionAnalyst"),
    ("模板标签", "template_tags", "NT-META", "MetaCognitionAnalyst"),
    ("模板管理", "template_tags", "NT-META", "MetaCognitionAnalyst"),
    ("template_tags", "template_tags", "NT-META", "MetaCognitionAnalyst"),
    ("模型适配", "model_adapter", "NT-IO", "CreativityGenerator"),
    ("lora适配", "model_adapter", "NT-IO", "CreativityGenerator"),
    ("adapter", "model_adapter", "NT-IO", "CreativityGenerator"),
    ("model_adapter", "model_adapter", "NT-IO", "CreativityGenerator"),
    ("参考生", "reference_generation", "NT-IO", "CreativityGenerator"),
    ("风格迁移", "reference_generation", "NT-IO", "CreativityGenerator"),
    ("图生图", "reference_generation", "NT-IO", "CreativityGenerator"),
    ("reference_generation", "reference_generation", "NT-IO", "CreativityGenerator"),
    ("平台网关", "platform_gateway", "NT-IO", "CreativityGenerator"),
    ("平台适配", "platform_gateway", "NT-IO", "CreativityGenerator"),
    ("comfyui", "platform_gateway", "NT-IO", "CreativityGenerator"),
    ("platform_gateway", "platform_gateway", "NT-IO", "CreativityGenerator"),
    ("批量生产", "production_pipeline", "NT-ACT", "CodeAnalyzer"),
    ("生产流水线", "production_pipeline", "NT-ACT", "CodeAnalyzer"),
    ("production_pipeline", "production_pipeline", "NT-ACT", "CodeAnalyzer"),
    ("发布网关", "publish_gateway", "NT-ACT", "CodeAnalyzer"),
    ("多平台发布", "publish_gateway", "NT-ACT", "CodeAnalyzer"),
    ("youtube发布", "publish_gateway", "NT-ACT", "CodeAnalyzer"),
    ("publish_gateway", "publish_gateway", "NT-ACT", "CodeAnalyzer"),
    ("工作流编排", "production_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("任务编排", "production_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("production_orchestrator", "production_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("运行手册", "operator_runbook", "NT-ACT", "CodeAnalyzer"),
    ("操作手册", "operator_runbook", "NT-ACT", "CodeAnalyzer"),
    ("runbook", "operator_runbook", "NT-ACT", "CodeAnalyzer"),
    ("operator_runbook", "operator_runbook", "NT-ACT", "CodeAnalyzer"),
    ("音频编排", "audio_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("音效混合", "audio_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("tts编排", "audio_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("audio_orchestrator", "audio_orchestrator", "NT-ACT", "CodeAnalyzer"),
    ("视频拼接", "video_stitcher", "NT-ACT", "CodeAnalyzer"),
    ("视频剪辑", "video_stitcher", "NT-ACT", "CodeAnalyzer"),
    ("时间线编辑", "video_stitcher", "NT-ACT", "CodeAnalyzer"),
    ("video_stitcher", "video_stitcher", "NT-ACT", "CodeAnalyzer"),
    ("媒体资产", "media_asset_registry", "NT-WORLD", "PatternMatcher"),
    ("资产库", "media_asset_registry", "NT-WORLD", "PatternMatcher"),
    ("角色资产", "media_asset_registry", "NT-WORLD", "PatternMatcher"),
    ("media_asset_registry", "media_asset_registry", "NT-WORLD", "PatternMatcher"),
    ("动态记忆", "dynamic_memory_bank", "NT-WORLD", "PatternMatcher"),
    ("实体记忆", "dynamic_memory_bank", "NT-WORLD", "PatternMatcher"),
    ("跨镜头记忆", "dynamic_memory_bank", "NT-WORLD", "PatternMatcher"),
    ("dynamic_memory_bank", "dynamic_memory_bank", "NT-WORLD", "PatternMatcher"),
    ("图像超分", "image_super_resolution", "NT-ACT", "CodeAnalyzer"),
    ("超分辨率", "image_super_resolution", "NT-ACT", "CodeAnalyzer"),
    ("esrgan", "image_super_resolution", "NT-ACT", "CodeAnalyzer"),
    ("image_super_resolution", "image_super_resolution", "NT-ACT", "CodeAnalyzer"),
    // universal_model — 统一模型接口
    ("universal_model", "universal_model", "NT-IO", "CreativityGenerator"),
    ("统一模型", "universal_model", "NT-IO", "CreativityGenerator"),
    ("模型接口", "universal_model", "NT-IO", "CreativityGenerator"),
    ("llm接口", "universal_model", "NT-IO", "CreativityGenerator"),
    // file_enhance — 文件增强能力
    ("file_enhance", "file_enhance", "NT-ACT", "CodeAnalyzer"),
    ("文件增强", "file_enhance", "NT-ACT", "CodeAnalyzer"),
    ("增强文件", "file_enhance", "NT-ACT", "CodeAnalyzer"),
    ("pdf增强", "file_enhance", "NT-ACT", "CodeAnalyzer"),
    ("pdf清晰度", "file_enhance", "NT-ACT", "CodeAnalyzer"),
    // kb_governance — KB 治理层
    ("kb_governance", "kb_governance", "NT-MEMORY", "KnowledgeRetriever"),
    ("知识库治理", "kb_governance", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb治理", "kb_governance", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb清理", "kb_governance", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb整理", "kb_governance", "NT-MEMORY", "KnowledgeRetriever"),
    // seal_process — SEAL 流水线处理
    ("seal_process", "seal_process", "NT-MIND", "KnowledgeIntegrator"),
    ("seal流水线", "seal_process", "NT-MIND", "KnowledgeIntegrator"),
    ("seal处理", "seal_process", "NT-MIND", "KnowledgeIntegrator"),
    ("流水线处理", "seal_process", "NT-MIND", "KnowledgeIntegrator"),
    ("执行流水线", "seal_process", "NT-MIND", "KnowledgeIntegrator"),
    // crawl4ai — 异步爬虫架构
    ("crawl4ai", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    ("异步爬虫", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    ("异步抓取", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    ("async_crawl", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    ("网页爬取", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    ("网站爬取", "crawl4ai", "NT-WORLD", "PatternMatcher"),
    // seal_genstep — SEAL 阶段可组合管道
    ("seal_genstep", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    ("SEAL阶段", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    ("seal管道", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    ("seal组合", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    ("进化阶段", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    ("genstep", "seal_genstep", "NT-MIND", "KnowledgeIntegrator"),
    // self_test_t3 — 技能有效性度量
    ("self_test_t3", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    ("T3测试", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    ("技能有效", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    ("能力度量", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    ("self_test", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    ("技能测试", "self_test_t3", "NT-META", "MetaCognitionAnalyst"),
    // kb_governance_ostrom — KB 治理分级制裁
    ("kb_governance_ostrom", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    ("ostrom治理", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    ("分级制裁", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb制裁", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb合规", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    ("知识库制裁", "kb_governance_ostrom", "NT-MEMORY", "KnowledgeRetriever"),
    // visual_explainer — 可视化输出适配器
    ("visual_explainer", "visual_explainer", "NT-IO", "CreativityGenerator"),
    ("可视化解释", "visual_explainer", "NT-IO", "CreativityGenerator"),
    ("可视化输出", "visual_explainer", "NT-IO", "CreativityGenerator"),
    ("图表生成", "visual_explainer", "NT-IO", "CreativityGenerator"),
    ("图解说明", "visual_explainer", "NT-IO", "CreativityGenerator"),
    // deer_flow — 网关+嵌入运行时
    ("deer_flow", "deer_flow", "NT-IO", "CreativityGenerator"),
    ("deerflow", "deer_flow", "NT-IO", "CreativityGenerator"),
    ("网关嵌入", "deer_flow", "NT-IO", "CreativityGenerator"),
    ("deer flow", "deer_flow", "NT-IO", "CreativityGenerator"),
    ("嵌入运行时", "deer_flow", "NT-IO", "CreativityGenerator"),
    // crawl4ai_stealth — 异步浏览器池
    ("crawl4ai_stealth", "crawl4ai_stealth", "NT-WORLD", "PatternMatcher"),
    ("stealth爬虫", "crawl4ai_stealth", "NT-WORLD", "PatternMatcher"),
    ("隐身爬取", "crawl4ai_stealth", "NT-WORLD", "PatternMatcher"),
    ("浏览器池", "crawl4ai_stealth", "NT-WORLD", "PatternMatcher"),
    ("反检测爬取", "crawl4ai_stealth", "NT-WORLD", "PatternMatcher"),
    // procedural_gen — 过程生成管线
    ("procedural_gen", "procedural_gen", "NT-ACT", "CodeAnalyzer"),
    ("过程生成", "procedural_gen", "NT-ACT", "CodeAnalyzer"),
    ("程序化生成", "procedural_gen", "NT-ACT", "CodeAnalyzer"),
    ("生成管线", "procedural_gen", "NT-ACT", "CodeAnalyzer"),
    ("算法生成", "procedural_gen", "NT-ACT", "CodeAnalyzer"),
    // rogue_elements — GenStep 异常元素检测管线
    ("rogue_elements", "rogue_elements", "NT-MIND", "KnowledgeIntegrator"),
    ("异常元素", "rogue_elements", "NT-MIND", "KnowledgeIntegrator"),
    ("rogue", "rogue_elements", "NT-MIND", "KnowledgeIntegrator"),
    ("pipeline异常", "rogue_elements", "NT-MIND", "KnowledgeIntegrator"),
    ("genstep异常", "rogue_elements", "NT-MIND", "KnowledgeIntegrator"),
    // tile_pyramid — KB 瓦片金字塔可视化浏览器
    ("tile_pyramid", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    ("瓦片金字塔", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    ("KB浏览", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    ("知识库浏览", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    ("KB可视化", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    ("tile_pyramid", "tile_pyramid", "NT-MEMORY", "KnowledgeRetriever"),
    // emotion_blending — 情感状态平滑过渡
    ("emotion_blending", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    ("情绪混合", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    ("情感过渡", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    ("状态平滑", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    ("情绪融合", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    ("emotion_blend", "emotion_blending", "NT-CORE", "ReflectionEngine"),
    // with_without_baseline — 技能效果对照基线度量
    ("with_without_baseline", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    ("对照基线", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    ("技能效果对比", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    ("有无对比", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    ("baseline", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    ("效果度量", "with_without_baseline", "NT-META", "MetaCognitionAnalyst"),
    // second_brain — 组织知识分层隔离
    ("second_brain", "second_brain", "NT-MEMORY", "KnowledgeIntegrator"),
    ("第二大脑", "second_brain", "NT-MEMORY", "KnowledgeIntegrator"),
    ("知识分层", "second_brain", "NT-MEMORY", "KnowledgeIntegrator"),
    ("组织知识", "second_brain", "NT-MEMORY", "KnowledgeIntegrator"),
    ("知识隔离", "second_brain", "NT-MEMORY", "KnowledgeIntegrator"),
    // regression_test — experience-tree 回归测试
    ("regression_test", "regression_test", "NT-MIND", "MetaCognitionAnalyst"),
    ("回归测试", "regression_test", "NT-MIND", "MetaCognitionAnalyst"),
    ("经验回归", "regression_test", "NT-MIND", "MetaCognitionAnalyst"),
    ("experience regression", "regression_test", "NT-MIND", "MetaCognitionAnalyst"),
    // declarative_knowledge — SEAL 陈述性知识
    ("declarative_knowledge", "declarative_knowledge", "NT-MIND", "KnowledgeIntegrator"),
    ("陈述性知识", "declarative_knowledge", "NT-MIND", "KnowledgeIntegrator"),
    ("声明知识", "declarative_knowledge", "NT-MIND", "KnowledgeIntegrator"),
    ("事实知识", "declarative_knowledge", "NT-MIND", "KnowledgeIntegrator"),
    // procedural_recipes — SEAL 过程性配方
    ("procedural_recipes", "procedural_recipes", "NT-MIND", "KnowledgeIntegrator"),
    ("过程配方", "procedural_recipes", "NT-MIND", "KnowledgeIntegrator"),
    ("操作配方", "procedural_recipes", "NT-MIND", "KnowledgeIntegrator"),
    ("技能配方", "procedural_recipes", "NT-MIND", "KnowledgeIntegrator"),
    ("how-to", "procedural_recipes", "NT-MIND", "KnowledgeIntegrator"),
    // honeyroute — 对抗性 LLM 检测
    ("honeyroute", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    ("蜜罐路由", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    ("对抗检测", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    ("llm对抗", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    ("honey", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    ("adversarial", "honeyroute", "NT-SHIELD", "RiskAssessor"),
    // knowledge_reasoning_sep — 知识/推理分离
    ("knowledge_reasoning_sep", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    ("知识推理分离", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    ("推理分离", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    ("知识推理拆分", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    ("reasoning_sep", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    ("kr_sep", "knowledge_reasoning_sep", "NT-MIND", "KnowledgeIntegrator"),
    // dependency_graph — KB 依赖追踪
    ("dependency_graph", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("依赖图", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("依赖追踪", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb依赖", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("dep_graph", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("依赖关系", "dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    // regression_enrichment — experience-tree 回归富化
    ("regression_enrichment", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    ("回归富化", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    ("经验回归富化", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    ("回归增强", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    ("enrichment", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    ("经验富化", "regression_enrichment", "NT-MIND", "MetaCognitionAnalyst"),
    // adversarial_router — 对抗性请求检测
    ("adversarial_router", "adversarial_router", "NT-SHIELD", "RiskAssessor"),
    ("对抗路由", "adversarial_router", "NT-SHIELD", "RiskAssessor"),
    ("请求检测", "adversarial_router", "NT-SHIELD", "RiskAssessor"),
    ("adversarial", "adversarial_router", "NT-SHIELD", "RiskAssessor"),
    ("攻击路由", "adversarial_router", "NT-SHIELD", "RiskAssessor"),
    // kb_dependency_graph — KB 依赖追踪图
    ("kb_dependency_graph", "kb_dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("知识库依赖图", "kb_dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("kb依赖图", "kb_dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("知识依赖", "kb_dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    ("dep_kb", "kb_dependency_graph", "NT-MEMORY", "KnowledgeRetriever"),
    // experience_regression — experience-tree 回归测试
    ("experience_regression", "experience_regression", "NT-MIND", "MetaCognitionAnalyst"),
    ("经验回归测试", "experience_regression", "NT-MIND", "MetaCognitionAnalyst"),
    ("经验树回归", "experience_regression", "NT-MIND", "MetaCognitionAnalyst"),
    ("exp_regression", "experience_regression", "NT-MIND", "MetaCognitionAnalyst"),
    ("回归验证", "experience_regression", "NT-MIND", "MetaCognitionAnalyst"),
    // knowledge_compilation — 知识编译管线
    ("knowledge_compilation", "knowledge_compilation", "NT-MIND", "KnowledgeIntegrator"),
    ("知识编译", "knowledge_compilation", "NT-MIND", "KnowledgeIntegrator"),
    ("知识管线", "knowledge_compilation", "NT-MIND", "KnowledgeIntegrator"),
    ("compile_knowledge", "knowledge_compilation", "NT-MIND", "KnowledgeIntegrator"),
    ("编译知识", "knowledge_compilation", "NT-MIND", "KnowledgeIntegrator"),
    // knowledge_distillation — 知识蒸馏管线
    ("knowledge_distillation", "knowledge_distillation", "NT-MIND", "KnowledgeIntegrator"),
    ("知识蒸馏", "knowledge_distillation", "NT-MIND", "KnowledgeIntegrator"),
    ("蒸馏管线", "knowledge_distillation", "NT-MIND", "KnowledgeIntegrator"),
    ("模型蒸馏", "knowledge_distillation", "NT-MIND", "KnowledgeIntegrator"),
    ("teacher_student", "knowledge_distillation", "NT-MIND", "KnowledgeIntegrator"),
    // experience_crystallization — 经验结晶
    ("experience_crystallization", "experience_crystallization", "NT-MEMORY", "KnowledgeIntegrator"),
    ("经验结晶", "experience_crystallization", "NT-MEMORY", "KnowledgeIntegrator"),
    ("结晶经验", "experience_crystallization", "NT-MEMORY", "KnowledgeIntegrator"),
    ("经验固化", "experience_crystallization", "NT-MEMORY", "KnowledgeIntegrator"),
    ("crystallize", "experience_crystallization", "NT-MEMORY", "KnowledgeIntegrator"),
    // skill_transfer — 跨模型技能迁移
    ("skill_transfer", "skill_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("技能迁移", "skill_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("跨模型迁移", "skill_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("技能转移", "skill_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("transfer_skill", "skill_transfer", "NT-MIND", "KnowledgeIntegrator"),
    // emotional_regulation — 情感调节
    ("emotional_regulation", "emotional_regulation", "NT-FEEL", "ReflectionEngine"),
    ("情感调节", "emotional_regulation", "NT-FEEL", "ReflectionEngine"),
    ("情绪调节", "emotional_regulation", "NT-FEEL", "ReflectionEngine"),
    ("情感管控", "emotional_regulation", "NT-FEEL", "ReflectionEngine"),
    ("regulate_emotion", "emotional_regulation", "NT-FEEL", "ReflectionEngine"),
    // memory_pruning — 记忆剪枝与衰减
    ("memory_pruning", "memory_pruning", "NT-MEMORY", "KnowledgeRetriever"),
    ("记忆剪枝", "memory_pruning", "NT-MEMORY", "KnowledgeRetriever"),
    ("记忆衰减", "memory_pruning", "NT-MEMORY", "KnowledgeRetriever"),
    ("衰减清理", "memory_pruning", "NT-MEMORY", "KnowledgeRetriever"),
    ("prune_memory", "memory_pruning", "NT-MEMORY", "KnowledgeRetriever"),
    // skill_versioning — 技能版本控制
    ("skill_versioning", "skill_versioning", "NT-MIND", "KnowledgeIntegrator"),
    ("技能版本", "skill_versioning", "NT-MIND", "KnowledgeIntegrator"),
    ("技能控制", "skill_versioning", "NT-MIND", "KnowledgeIntegrator"),
    ("版本控制", "skill_versioning", "NT-MIND", "KnowledgeIntegrator"),
    ("version_skill", "skill_versioning", "NT-MIND", "KnowledgeIntegrator"),
    // emotional_memory — 情感记忆标签
    ("emotional_memory", "emotional_memory", "NT-FEEL", "ReflectionEngine"),
    ("情感记忆", "emotional_memory", "NT-FEEL", "ReflectionEngine"),
    ("情绪记忆", "emotional_memory", "NT-FEEL", "ReflectionEngine"),
    ("记忆标签", "emotional_memory", "NT-FEEL", "ReflectionEngine"),
    ("emotion_memory", "emotional_memory", "NT-FEEL", "ReflectionEngine"),
    // confidence_calibration — 置信度校准
    ("confidence_calibration", "confidence_calibration", "NT-META", "MetaCognitionAnalyst"),
    ("置信度校准", "confidence_calibration", "NT-META", "MetaCognitionAnalyst"),
    ("置信度", "confidence_calibration", "NT-META", "MetaCognitionAnalyst"),
    ("校准置信", "confidence_calibration", "NT-META", "MetaCognitionAnalyst"),
    ("calibrate_confidence", "confidence_calibration", "NT-META", "MetaCognitionAnalyst"),
    // analogical_transfer — 类比迁移引擎
    ("analogical_transfer", "analogical_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("类比迁移", "analogical_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("类比推理", "analogical_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("迁移类比", "analogical_transfer", "NT-MIND", "KnowledgeIntegrator"),
    ("analogy", "analogical_transfer", "NT-MIND", "KnowledgeIntegrator"),
    // ethical_reasoning — 伦理推理框架
    ("ethical_reasoning", "ethical_reasoning", "NT-CORE", "ReflectionEngine"),
    ("伦理推理", "ethical_reasoning", "NT-CORE", "ReflectionEngine"),
    ("伦理评估", "ethical_reasoning", "NT-CORE", "ReflectionEngine"),
    ("道德判断", "ethical_reasoning", "NT-CORE", "ReflectionEngine"),
    ("ethics", "ethical_reasoning", "NT-CORE", "ReflectionEngine"),
    // wisdom_crystallization — 智慧结晶
    ("wisdom_crystallization", "wisdom_crystallization", "NT-MIND", "KnowledgeIntegrator"),
    ("智慧结晶", "wisdom_crystallization", "NT-MIND", "KnowledgeIntegrator"),
    ("经验升华", "wisdom_crystallization", "NT-MIND", "KnowledgeIntegrator"),
    ("智慧提炼", "wisdom_crystallization", "NT-MIND", "KnowledgeIntegrator"),
    ("crystallize_wisdom", "wisdom_crystallization", "NT-MIND", "KnowledgeIntegrator"),
    // cognitive_bias_detection — 认知偏差检测
    ("cognitive_bias_detection", "cognitive_bias_detection", "NT-META", "MetaCognitionAnalyst"),
    ("认知偏差", "cognitive_bias_detection", "NT-META", "MetaCognitionAnalyst"),
    ("偏差检测", "cognitive_bias_detection", "NT-META", "MetaCognitionAnalyst"),
    ("思维偏差", "cognitive_bias_detection", "NT-META", "MetaCognitionAnalyst"),
    ("bias_detection", "cognitive_bias_detection", "NT-META", "MetaCognitionAnalyst"),
    // strategy_selection — 认知策略选择
    ("strategy_selection", "strategy_selection", "NT-CORE", "ReflectionEngine"),
    ("策略选择", "strategy_selection", "NT-CORE", "ReflectionEngine"),
    ("认知策略", "strategy_selection", "NT-CORE", "ReflectionEngine"),
    ("选择策略", "strategy_selection", "NT-CORE", "ReflectionEngine"),
    ("select_strategy", "strategy_selection", "NT-CORE", "ReflectionEngine"),
    // error_detection — 认知错误检测
    ("error_detection", "error_detection", "NT-META", "MetaCognitionAnalyst"),
    ("错误检测", "error_detection", "NT-META", "MetaCognitionAnalyst"),
    ("认知错误", "error_detection", "NT-META", "MetaCognitionAnalyst"),
    ("推理错误", "error_detection", "NT-META", "MetaCognitionAnalyst"),
    ("detect_error", "error_detection", "NT-META", "MetaCognitionAnalyst"),
    // learning_optimization — 学习优化
    ("learning_optimization", "learning_optimization", "NT-MIND", "KnowledgeIntegrator"),
    ("学习优化", "learning_optimization", "NT-MIND", "KnowledgeIntegrator"),
    ("优化学习", "learning_optimization", "NT-MIND", "KnowledgeIntegrator"),
    ("学习策略", "learning_optimization", "NT-MIND", "KnowledgeIntegrator"),
    ("optimize_learning", "learning_optimization", "NT-MIND", "KnowledgeIntegrator"),
    // pattern_recognition — 模式识别
    ("pattern_recognition", "pattern_recognition", "NT-CORE", "ReflectionEngine"),
    ("模式识别", "pattern_recognition", "NT-CORE", "ReflectionEngine"),
    ("识别模式", "pattern_recognition", "NT-CORE", "ReflectionEngine"),
    ("发现模式", "pattern_recognition", "NT-CORE", "ReflectionEngine"),
    ("recognize_pattern", "pattern_recognition", "NT-CORE", "ReflectionEngine"),
];

pub fn decompose_instruction(instruction: &str) -> Vec<ConsciousTask> {
    let segments: Vec<&str> = instruction
        .split(['。', '；', ';', '\n', '，', ','])
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    let mut tasks: Vec<ConsciousTask> = Vec::new();
    for seg in segments {
        let lower = seg.to_lowercase();
        let mut matched = false;
        for (kw, cap, domain, spec) in CAPABILITY_ROUTES {
            if lower.contains(kw.to_lowercase().as_str()) {
                tasks.push(ConsciousTask {
                    id: format!("task_{}", tasks.len() + 1),
                    summary: seg.to_string(),
                    capability_tag: cap.to_string(),
                    domain: domain.to_string(),
                    specialist: spec.to_string(),
                    priority: 5,
                });
                matched = true;
                break;
            }
        }
        if !matched {
            tasks.push(ConsciousTask {
                id: format!("task_{}", tasks.len() + 1),
                summary: seg.to_string(),
                capability_tag: "orchestration".to_string(),
                domain: "NT-CORE".to_string(),
                specialist: "Orchestrator".to_string(),
                priority: 3,
            });
        }
    }
    if tasks.is_empty() {
        tasks.push(ConsciousTask {
            id: "task_1".to_string(),
            summary: instruction.to_string(),
            capability_tag: "orchestration".to_string(),
            domain: "NT-CORE".to_string(),
            specialist: "Orchestrator".to_string(),
            priority: 3,
        });
    }
    tasks
}
