mod core;
mod dgmh;
mod handlers_all;
mod handlers_core;
mod handlers_memory;
mod handlers_meta;
mod handlers_research;
mod handlers_safety;
mod layer_manager;
mod modules_a2a;
mod modules_adversarial;
mod modules_agent;
mod modules_audio;
mod modules_avsad;
mod modules_consciousness_bench;
mod modules_core;
mod modules_e8;
mod modules_hcube;
mod modules_identity;
mod modules_inference;
mod modules_jepa;
mod modules_kb;
mod modules_persist;
mod modules_self_modify;
mod modules_spatial;
mod modules_storage;
mod modules_storm;
mod modules_vision;
// modules_canvas replaced by event‑driven canvas_new_chain / canvas_flush_final on BackgroundLoop
mod consciousness_handle_impl;
mod modules;
mod self_inspect;
mod stats;
mod tool_executor_impl;
pub use tool_executor_impl::NeotrixToolExecutor;
pub(crate) mod types;
pub mod types_consciousness;
pub(crate) mod types_evolution;
pub(crate) mod types_research;
mod vsa;

pub use types::ConsciousnessIntegration;
pub use types_consciousness::ExperienceStats;
