// Generated by nt-lang. DO NOT EDIT.
// Source: neotrix-core/test_suites/cross_modal.nt

use neotrix::l2_perception::nt_core_hcube::cross_modal::CrossModalAligner;
use neotrix::l2_perception::nt_core_hcube::vsa_quantized::VSA_DIM;

#[test]
fn align_text_deterministic() {
    let aligner = CrossModalAligner::new(VSA_DIM, 42);
    let v1 = aligner.text_to_vsa("hello world");
    let v2 = aligner.text_to_vsa("hello world");
    assert_eq!(v1, v2, "deterministic text → VSA");
}

#[test]
fn align_image_projection_dim() {
    let aligner = CrossModalAligner::new(VSA_DIM, 42);
    let embed: Vec<f32> = (0..512).map(|i| (i as f32).sin()).collect();
    let vsa = aligner.image_embed_to_vsa(&embed);
    assert_eq!(vsa.len(), VSA_DIM);
}

#[test]
fn align_cross_similarity_symmetric() {
    let aligner = CrossModalAligner::new(VSA_DIM, 42);
    let embed: Vec<f32> = (0..512).map(|i| (i as f32).sin()).collect();
    let v = aligner.image_embed_to_vsa(&embed);
    let sim_ab = CrossModalAligner::cross_modal_similarity(&v, &v);
    let sim_ba = CrossModalAligner::cross_modal_similarity(&v, &v);
    assert!((sim_ab - sim_ba).abs() < 1e-12);
}

#[test]
fn align_modality_tags_distinct() {
    let aligner = CrossModalAligner::new(VSA_DIM, 42);
    let t1 = aligner.modality_tag("text");
    let t2 = aligner.modality_tag("image");
    let t3 = aligner.modality_tag("audio");
    assert_ne!(t1, t2);
    assert_ne!(t2, t3);
    assert_ne!(t1, t3);
}

#[test]
fn align_empty_text_returns_zero() {
    let aligner = CrossModalAligner::new(VSA_DIM, 42);
    let v = aligner.text_to_vsa("");
    assert_eq!(v.len(), VSA_DIM);
    assert!(v.iter().all(|&x| x == 0));
}
