// Generated by nt-lang. DO NOT EDIT.
// Source: neotrix-core/test_suites/vsa_engine.nt

use neotrix::l2_perception::nt_core_hcube::vsa::VSAEngine;
use neotrix::l2_perception::nt_core_hcube::vsa::VsaBackend;

#[test]
fn engine_bind_different_from_inputs() {
    let engine = VSAEngine::new(4096);
    let a: Vec<f64> = (0..4096).map(|i| (i as f64).sin()).collect();
    let b: Vec<f64> = (0..4096).map(|i| (i as f64).cos()).collect();
    let c = engine.bind(&a, &b);
    let sim_a = engine.similarity(&c, &a);
    let sim_b = engine.similarity(&c, &b);
    assert!(sim_a.abs() < 0.1);
    assert!(sim_b.abs() < 0.1);
}

#[test]
fn engine_bundle_similar_to_components() {
    let engine = VSAEngine::new(4096);
    let a: Vec<f64> = (0..4096).map(|i| (i as f64).sin()).collect();
    let b: Vec<f64> = (0..4096).map(|i| (i as f64).cos()).collect();
    let c = engine.bundle(&[&a, &b]);
    assert!(engine.similarity(&c, &a) > 0.5);
    assert!(engine.similarity(&c, &b) > 0.5);
}

#[test]
fn engine_permute_reversible() {
    let engine = VSAEngine::new(4096);
    let v: Vec<f64> = (0..4096).map(|i| (i as f64).sin()).collect();
    let p = engine.permute(&v, 100);
    let r = engine.permute(&p, -100);
    let sim = engine.similarity(&r, &v);
    assert!((sim - 1.0).abs() < 1e-10);
}

#[test]
fn engine_self_similarity_one() {
    let engine = VSAEngine::new(4096);
    let v: Vec<f64> = (0..4096).map(|i| (i as f64).sin()).collect();
    let sim = engine.similarity(&v, &v);
    assert!((sim - 1.0).abs() < 1e-10);
}

#[test]
fn engine_dimensions() {
    let engine = VSAEngine::new(1024);
    assert_eq!(engine.dimensions(), 1024);
}
