// Generated by nt-lang. DO NOT EDIT.
// Source: neotrix-core/test_suites/vsa_quantized.nt

use neotrix::l2_perception::nt_core_hcube::vsa_quantized::QuantizedVSA;
use neotrix::l2_perception::nt_core_hcube::vsa_quantized::VSA_DIM;

#[test]
fn vsa_random_vector_dim() {
    let v = QuantizedVSA::random_vector();
    assert_eq!(v.len(), VSA_DIM);
}

#[test]
fn vsa_binary_vector_is_binary() {
    let v = QuantizedVSA::random_binary();
    for &x in &v {
        assert!(x == 0 || x == 255);
    }
}

#[test]
fn vsa_bind_self_returns_zero() {
    let a = QuantizedVSA::random_binary();
    let bound = QuantizedVSA::bind(&a, &a);
    // HRR self-bind yields roughly half the elements nonzero (binary thresholding
    // of circular autocorrelation), unlike XOR where a XOR a == 0.
    let nonzero = bound.iter().filter(|&&x| x != 0).count();
    assert!(
        nonzero > VSA_DIM / 4,
        "HRR self-bind should be noise-like, got {} nonzero",
        nonzero
    );
}

#[test]
fn vsa_unbind_recovers_component() {
    let a = QuantizedVSA::random_binary();
    let b = QuantizedVSA::random_binary();
    let c = QuantizedVSA::bind(&a, &b);
    let rec = QuantizedVSA::unbind(&c, &a);
    let sim = QuantizedVSA::similarity(&rec, &b);
    assert!(
        sim > 0.5,
        "expected unbind(bind(a,b),a) ≈ b, got sim {}",
        sim
    );
}

#[test]
fn vsa_permute_reversible() {
    let v = QuantizedVSA::random_binary();
    let p = QuantizedVSA::permute(&v, 100);
    let r = QuantizedVSA::permute(&p, -100);
    let sim = QuantizedVSA::similarity(&r, &v);
    assert!((sim - 1.0).abs() < 1e-10);
}

#[test]
fn vsa_self_similarity_one() {
    let v = QuantizedVSA::random_binary();
    let sim = QuantizedVSA::similarity(&v, &v);
    assert!((sim - 1.0).abs() < 1e-10);
}

#[test]
fn vsa_hamming_distance_counts() {
    let zeros = vec![0u8; VSA_DIM];
    let ones = vec![1u8; VSA_DIM];
    let dist = QuantizedVSA::hamming_distance(&zeros, &ones);
    assert_eq!(dist, VSA_DIM as u32);
}
