//! TikTok Extractor
//!
//! # Anti-Detection: X-Gnarly Signature
//!
//! TikTok requires a cryptographic signature (`X-Gnarly`) for most API endpoints.
//! This signature is generated by obfuscated JavaScript running in the browser.
//!
//! **Current status**: Feed endpoint returns HTTP 403 without signature.
//! **TODO**: Integrate `deno_core` to execute the X-Gnarly signing JS.
//!
//! Workaround: Use fxtwitter-like proxy services or scrape via browser automation.

use super::super::traits::{SocialPlatformAdapter, SessionEntry, FeedResult, TrendingTopic, AuthFlow, SocialAccessError};

pub struct TikTokExtractor;

impl TikTokExtractor {
    pub fn new() -> Self {
        Self
    }
}

impl SocialPlatformAdapter for TikTokExtractor {
    fn id(&self) -> String { "tiktok".into() }
    fn name(&self) -> &'static str { "TikTok" }
    fn auth_flow(&self) -> AuthFlow { AuthFlow::OAuth2PKCE }
    fn api_base_url(&self) -> &'static str { "https://tiktok.com" }
    fn channel_name(&self) -> Option<&'static str> { Some("tiktok") }

    fn get_recommended(&self, _session: &SessionEntry, _limit: usize) -> Result<FeedResult, SocialAccessError> {
        Ok(FeedResult { items: vec![], total: 0 })
    }
    fn get_following(&self, _session: &SessionEntry, _limit: usize) -> Result<FeedResult, SocialAccessError> {
        Ok(FeedResult { items: vec![], total: 0 })
    }
    fn get_trending(&self) -> Result<Vec<TrendingTopic>, SocialAccessError> {
        Ok(vec![])
    }
}
