use sha2::{Digest, Sha256};

/// ArmorGenerator — wraps compiled Rust payloads with compile-time encryption
/// and runtime self-decryption to resist static analysis / reverse engineering.
///
/// Flow:
///   1. Codegen produces Rust source (plaintext)
///   2. ArmorGenerator encrypts the source with a compile-time key
///   3. Generates a self-decrypting wrapper binary that:
///      - Embeds the encrypted payload as a `&[u8]` constant
///      - At runtime: decrypts with an embedded or derived key
///      - Writes decrypted source to a temp file, compiles with rustc, runs, cleans up
///
/// Security level: Level 1 — stops casual reading (strings, grep) but not
/// determined reverse engineering. Good enough for Stage 0 seed protection.
pub struct ArmorGenerator;

impl ArmorGenerator {
    /// Derive an N-byte key from a u64 seed using SHA-256.
    pub fn derive_key(seed: u64, len: usize) -> Vec<u8> {
        let mut key = Vec::with_capacity(len);
        let mut counter: u64 = 0;
        while key.len() < len {
            let mut hasher = Sha256::new();
            hasher.update(seed.to_le_bytes());
            hasher.update(counter.to_le_bytes());
            let hash = hasher.finalize();
            key.extend_from_slice(&hash);
            counter += 1;
        }
        key.truncate(len);
        key
    }

    /// Encrypt plaintext using XOR with a key derived from `key_seed`.
    /// Returns (ciphertext, derived_key).
    /// The derived key is returned so the caller can store/embed it separately
    /// from the encryption step (e.g. key in env var, ciphertext in binary).
    pub fn encrypt(data: &[u8], key_seed: u64) -> (Vec<u8>, Vec<u8>) {
        let key = Self::derive_key(key_seed, data.len());
        let ciphertext: Vec<u8> = data.iter().zip(key.iter()).map(|(a, b)| a ^ b).collect();
        (ciphertext, key)
    }

    /// Decrypt XOR-encrypted ciphertext with the derived key.
    pub fn decrypt(ciphertext: &[u8], key: &[u8]) -> Vec<u8> {
        ciphertext
            .iter()
            .zip(key.iter())
            .map(|(a, b)| a ^ b)
            .collect()
    }

    /// Encrypt with an explicit key slice (instead of deriving from seed).
    /// Returns (ciphertext, key_used) where key_used is the same as input key
    /// (padded/truncated to match data length).
    pub fn encrypt_with_key(data: &[u8], key: &[u8]) -> (Vec<u8>, Vec<u8>) {
        let effective_key: Vec<u8> = key.iter().copied().cycle().take(data.len()).collect();
        let ciphertext: Vec<u8> = data
            .iter()
            .zip(effective_key.iter())
            .map(|(a, b)| a ^ b)
            .collect();
        (ciphertext, effective_key)
    }

    /// Generate a self-decrypting Rust wrapper binary.
    ///
    /// The wrapper:
    /// 1. Embeds the encrypted source as a `&[u8]` constant
    /// 2. Embeds the XOR key as a separate `&[u8]` constant
    /// 3. At runtime: decrypts, writes to a temp file, compiles with rustc,
    ///    runs the resulting binary, and cleans up all temp files.
    ///
    /// Returns the complete Rust source for the wrapper binary (including main()).
    pub fn generate_armored_binary(plain_source: &str, key_seed: u64) -> String {
        let (ciphertext, key) = Self::encrypt(plain_source.as_bytes(), key_seed);

        let ct_bytes: Vec<String> = ciphertext.iter().map(|b| format!("{b}")).collect();
        let ct_literal = ct_bytes.join(", ");

        let key_bytes: Vec<String> = key[..32.min(key.len())]
            .iter()
            .map(|b| format!("{b}"))
            .collect();
        let key_literal = key_bytes.join(", ");

        let ct_len = ciphertext.len();
        let key_len = key.len().min(32);

        format!(
            r###"// Generated by ArmorGenerator — DO NOT EDIT
// Self-decrypting wrapper. Encrypted payload: Stage 0 seed compiler.

const ENCRYPTED: &[u8] = &[{ct_literal}];
const XOR_KEY: &[u8] = &[{key_literal}];
const CT_LEN: usize = {ct_len};
const KEY_LEN: usize = {key_len};

fn decrypt() -> Vec<u8> {{
    let key = if XOR_KEY.len() >= CT_LEN {{
        XOR_KEY[..CT_LEN].to_vec()
    }} else {{
        let mut k = Vec::with_capacity(CT_LEN);
        while k.len() < CT_LEN {{
            k.extend_from_slice(XOR_KEY);
        }}
        k.truncate(CT_LEN);
        k
    }};
    ENCRYPTED.iter().zip(key.iter()).map(|(a, b)| a ^ b).collect()
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let plaintext = decrypt();
    let source = String::from_utf8(plaintext)?;

    // Write to temp file
    let tmp_dir = std::env::temp_dir();
    let src_path = tmp_dir.join("armor_stage0.rs");
    let bin_path = tmp_dir.join(if cfg!(windows) {{ "armor_stage0.exe" }} else {{ "armor_stage0" }});

    std::fs::write(&src_path, &source)?;

    // Compile with rustc
    let status = std::process::Command::new("rustc")
        .arg(&src_path)
        .arg("-o")
        .arg(&bin_path)
        .status()?;

    if !status.success() {{
        log::error!("Armor: rustc compilation failed");
        let _ = std::fs::remove_file(&src_path);
        return Err("rustc compilation failed".into());
    }}

    // Run the compiled binary
    let output = std::process::Command::new(&bin_path)
        .status()?;

    // Clean up temp files
    let _ = std::fs::remove_file(&src_path);
    let _ = std::fs::remove_file(&bin_path);

    // Zero out decrypted memory
    drop(source);
    drop(plaintext);

    std::process::exit(output.code().unwrap_or(0));
}}
"###
        )
    }

    /// Generate an armored binary with an externally provided key (split-key mode).
    /// The XOR_KEY constant in the wrapper will be all zeros; the actual key must
    /// be provided at runtime via `ARMOR_KEY` env var or a key file.
    pub fn generate_armored_binary_split_key(plain_source: &str, key_seed: u64) -> String {
        let (ciphertext, _key) = Self::encrypt(plain_source.as_bytes(), key_seed);

        let ct_bytes: Vec<String> = ciphertext.iter().map(|b| format!("{b}")).collect();
        let ct_literal = ct_bytes.join(", ");

        let ct_len = ciphertext.len();

        format!(
            r###"// Generated by ArmorGenerator — Split-Key Mode — DO NOT EDIT
// The XOR key is NOT embedded. Supply via ARMOR_KEY env var (hex-encoded, 32+ bytes).

const ENCRYPTED: &[u8] = &[{ct_literal}];
const CT_LEN: usize = {ct_len};

fn load_key() -> Result<Vec<u8>, Box<dyn std::error::Error>> {{
    let hex_key = std::env::var("ARMOR_KEY")?;
    let key_bytes = hex::decode(&hex_key)?;
    let mut k = Vec::with_capacity(CT_LEN);
    while k.len() < CT_LEN {{
        k.extend_from_slice(&key_bytes);
    }}
    k.truncate(CT_LEN);
    Ok(k)
}}

fn decrypt(key: &[u8]) -> Vec<u8> {{
    ENCRYPTED.iter().zip(key.iter()).map(|(a, b)| a ^ b).collect()
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let key = load_key()?;
    let plaintext = decrypt(&key);
    let source = String::from_utf8(plaintext)?;

    let tmp_dir = std::env::temp_dir();
    let src_path = tmp_dir.join("armor_stage0.rs");
    let bin_path = tmp_dir.join(if cfg!(windows) {{ "armor_stage0.exe" }} else {{ "armor_stage0" }});

    std::fs::write(&src_path, &source)?;

    let status = std::process::Command::new("rustc")
        .arg(&src_path)
        .arg("-o")
        .arg(&bin_path)
        .status()?;

    if !status.success() {{
        log::error!("Armor: rustc compilation failed");
        let _ = std::fs::remove_file(&src_path);
        return Err("rustc compilation failed".into());
    }}

    let output = std::process::Command::new(&bin_path)
        .status()?;

    let _ = std::fs::remove_file(&src_path);
    let _ = std::fs::remove_file(&bin_path);
    drop(source);
    drop(plaintext);

    std::process::exit(output.code().unwrap_or(0));
}}
"###
        )
    }

    /// Generate an armored binary that reads key from a file at runtime.
    pub fn generate_armored_binary_keyfile(
        plain_source: &str,
        key_seed: u64,
        keyfile_path: &str,
    ) -> String {
        let (ciphertext, _key) = Self::encrypt(plain_source.as_bytes(), key_seed);

        let ct_bytes: Vec<String> = ciphertext.iter().map(|b| format!("{b}")).collect();
        let ct_literal = ct_bytes.join(", ");
        let ct_len = ciphertext.len();

        format!(
            r###"// Generated by ArmorGenerator — Keyfile Mode — DO NOT EDIT

const ENCRYPTED: &[u8] = &[{ct_literal}];
const CT_LEN: usize = {ct_len};
const KEYFILE_PATH: &str = "{keyfile_path}";

fn load_key_from_file() -> Result<Vec<u8>, Box<dyn std::error::Error>> {{
    let hex_key = std::fs::read_to_string(KEYFILE_PATH)?;
    let hex_key = hex_key.trim();
    let key_bytes = hex::decode(hex_key)?;
    let mut k = Vec::with_capacity(CT_LEN);
    while k.len() < CT_LEN {{
        k.extend_from_slice(&key_bytes);
    }}
    k.truncate(CT_LEN);
    Ok(k)
}}

fn decrypt(key: &[u8]) -> Vec<u8> {{
    ENCRYPTED.iter().zip(key.iter()).map(|(a, b)| a ^ b).collect()
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let key = load_key_from_file()?;
    let plaintext = decrypt(&key);
    let source = String::from_utf8(plaintext)?;

    let tmp_dir = std::env::temp_dir();
    let src_path = tmp_dir.join("armor_stage0.rs");
    let bin_path = tmp_dir.join(if cfg!(windows) {{ "armor_stage0.exe" }} else {{ "armor_stage0" }});

    std::fs::write(&src_path, &source)?;
    let status = std::process::Command::new("rustc")
        .arg(&src_path)
        .arg("-o")
        .arg(&bin_path)
        .status()?;

    if !status.success() {{
        log::error!("Armor: rustc compilation failed");
        let _ = std::fs::remove_file(&src_path);
        return Err("rustc compilation failed".into());
    }}

    let output = std::process::Command::new(&bin_path)
        .status()?;

    let _ = std::fs::remove_file(&src_path);
    let _ = std::fs::remove_file(&bin_path);
    drop(source);
    drop(plaintext);

    std::process::exit(output.code().unwrap_or(0));
}}
"###
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_roundtrip_encrypt_decrypt() {
        let data = b"Hello, NeoTrix! This is secret Stage 0 seed code.";
        let seed: u64 = 0xDEAD_BEEF_CAFE_1234;
        let (ct, key) = ArmorGenerator::encrypt(data, seed);
        assert_ne!(ct, data, "ciphertext must differ from plaintext");
        assert_eq!(
            ct.len(),
            data.len(),
            "ciphertext length must match plaintext"
        );
        assert_eq!(
            key.len(),
            data.len(),
            "derived key length must match data length"
        );

        let decrypted = ArmorGenerator::decrypt(&ct, &key);
        assert_eq!(decrypted, data, "roundtrip must recover original plaintext");
    }

    #[test]
    fn test_different_seeds_produce_different_ciphertext() {
        let data = b"same plaintext";
        let (ct1, _) = ArmorGenerator::encrypt(data, 42);
        let (ct2, _) = ArmorGenerator::encrypt(data, 999);
        assert_ne!(
            ct1, ct2,
            "different seeds must produce different ciphertext"
        );
    }

    #[test]
    fn test_armored_binary_wrapper_contains_main() {
        let source = r#"fn main() { println!("hello"); }"#;
        let wrapper = ArmorGenerator::generate_armored_binary(source, 0x1234);
        assert!(
            wrapper.contains("fn main()"),
            "wrapper must have a main function"
        );
        assert!(
            wrapper.contains("ENCRYPTED"),
            "wrapper must embed encrypted bytes"
        );
        assert!(
            wrapper.contains("XOR_KEY"),
            "wrapper must embed the XOR key"
        );
        assert!(wrapper.contains("rustc"), "wrapper must invoke rustc");
        assert!(
            wrapper.contains("decrypt"),
            "wrapper must have a decrypt function"
        );
    }

    #[test]
    fn test_armored_binary_split_key_no_key_embedded() {
        let source = r#"fn main() { println!("hello"); }"#;
        let wrapper = ArmorGenerator::generate_armored_binary_split_key(source, 0x5678);
        assert!(wrapper.contains("fn main()"), "wrapper must have main");
        assert!(
            wrapper.contains("ENCRYPTED"),
            "wrapper must embed encrypted bytes"
        );
        assert!(
            !wrapper.contains("XOR_KEY"),
            "split-key wrapper must NOT embed key"
        );
        assert!(
            wrapper.contains("ARMOR_KEY"),
            "split-key wrapper must read from env"
        );
    }

    #[test]
    fn test_armored_binary_keyfile_mode() {
        let source = r#"fn main() { println!("hello"); }"#;
        let wrapper =
            ArmorGenerator::generate_armored_binary_keyfile(source, 0x9ABC, "/tmp/my.key");
        assert!(wrapper.contains("fn main()"), "wrapper must have main");
        assert!(
            wrapper.contains("ENCRYPTED"),
            "wrapper must embed encrypted bytes"
        );
        assert!(
            wrapper.contains("KEYFILE_PATH"),
            "keyfile wrapper must have path const"
        );
        assert!(
            wrapper.contains("/tmp/my.key"),
            "keyfile wrapper must reference path"
        );
    }

    #[test]
    fn test_encrypt_with_explicit_key() {
        let data = b"explicit key test data";
        let key = b"my-secret-key-32-bytes-long!!!!!";
        let (ct, used_key) = ArmorGenerator::encrypt_with_key(data, key);
        assert_eq!(
            used_key.len(),
            data.len(),
            "effective key must match data length"
        );
        let decrypted = ArmorGenerator::decrypt(&ct, &used_key);
        assert_eq!(decrypted, data, "explicit key roundtrip must work");
        assert_eq!(used_key[..key.len()], key[..]);
        assert_eq!(used_key[key.len()..], key[..data.len() - key.len()]);
    }

    #[test]
    fn test_derive_key_deterministic() {
        let k1 = ArmorGenerator::derive_key(42, 64);
        let k2 = ArmorGenerator::derive_key(42, 64);
        assert_eq!(k1, k2, "derive_key must be deterministic");

        let k3 = ArmorGenerator::derive_key(99, 64);
        assert_ne!(k1, k3, "different seeds must produce different keys");
    }

    #[test]
    fn test_encrypt_empty_data() {
        let data = b"";
        let (ct, key) = ArmorGenerator::encrypt(data, 0);
        assert!(ct.is_empty(), "empty data produces empty ciphertext");
        assert!(key.is_empty(), "empty data produces empty key");

        let decrypted = ArmorGenerator::decrypt(&ct, &key);
        assert!(decrypted.is_empty(), "empty roundtrip");
    }

    #[test]
    fn test_armored_wrapper_is_standalone_binary() {
        let source = r#"fn main() { println!("armor test ok"); }"#;
        let wrapper = ArmorGenerator::generate_armored_binary(source, 0xABCD);

        assert!(wrapper.contains("fn main()"));
        assert!(wrapper.contains("fn decrypt()"));
        assert!(wrapper.starts_with("// Generated by ArmorGenerator"));
        assert!(wrapper.contains("std::process::Command::new(\"rustc\")"));
        assert!(wrapper.contains("std::fs::write"));
        assert!(wrapper.contains("std::fs::remove_file"));
    }
}
