/// Ne Standard Library — seed functions registered at compile time.
///
/// Each `StdFunction` wraps one of the 8 Ne VSA primitives as a named
/// S-expression that the Ne compiler can call at runtime.

/// A seed function written in Ne S-expression notation.
#[derive(Debug, Clone)]
pub struct StdFunction {
    pub name: &'static str,
    /// Arity: number of arguments (-1 = variadic, like bundle).
    pub arity: isize,
    /// Ne source body in S-expression form (e.g. "(bind a b)").
    pub body_sexpr: &'static str,
    pub description: &'static str,
}

/// The Ne standard library — seed functions registered at compile time.
pub struct StdLibrary {
    pub functions: Vec<StdFunction>,
}

impl StdLibrary {
    pub fn new() -> Self {
        Self {
            functions: Self::seed_functions(),
        }
    }

    pub fn seed_functions() -> Vec<StdFunction> {
        vec![
            StdFunction {
                name: "vsa_bind",
                arity: 2,
                body_sexpr: "(bind arg0 arg1)",
                description: "VSA XOR binding of two hypervectors",
            },
            StdFunction {
                name: "vsa_bundle",
                arity: -1,
                body_sexpr: "(bundle arg0 arg1)",
                description: "VSA majority-sum bundling of hypervectors",
            },
            StdFunction {
                name: "vsa_permute",
                arity: 2,
                body_sexpr: "(permute arg0 arg1)",
                description: "VSA cyclic shift (rotation) of a hypervector",
            },
            StdFunction {
                name: "vsa_similarity",
                arity: 2,
                body_sexpr: "(similarity arg0 arg1)",
                description: "Hamming similarity between two hypervectors [0,1]",
            },
            StdFunction {
                name: "vsa_negate",
                arity: 1,
                body_sexpr: "(negate arg0)",
                description: "VSA bitwise negation (bind with all-1s)",
            },
            StdFunction {
                name: "self_reflect",
                arity: 0,
                body_sexpr: "(reflect)",
                description: "Distill current consciousness state to VSA vector",
            },
            StdFunction {
                name: "self_curious",
                arity: 1,
                body_sexpr: "(curious arg0)",
                description: "Detect knowledge gap, produce exploration goal from VSA deficit",
            },
            StdFunction {
                name: "self_dream",
                arity: 1,
                body_sexpr: "(dream arg0)",
                description: "Simulate possible worlds from current belief state",
            },
        ]
    }

    /// Render all StdLib functions as a Ne source file.
    pub fn to_ne_source(&self) -> String {
        let mut out = String::new();
        out.push_str("// Ne Standard Library — seed functions\n");
        out.push_str("// Generated by StdLibrary\n\n");
        for f in &self.functions {
            let params: Vec<String> = if f.arity == 0 {
                vec![]
            } else if f.arity < 0 {
                (0..2).map(|i| format!("arg{}", i)).collect()
            } else {
                (0..f.arity as usize).map(|i| format!("arg{}", i)).collect()
            };
            out.push_str(&format!("// {} — {}\n", f.name, f.description));
            out.push_str(&format!(
                "//   ({}{})\n\n",
                f.name,
                if params.is_empty() {
                    String::new()
                } else {
                    format!(" {}", params.join(" "))
                }
            ));
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stdlib_has_8_functions() {
        let lib = StdLibrary::new();
        assert_eq!(lib.functions.len(), 8);
    }

    #[test]
    fn test_stdlib_to_ne_source_contains_all_names() {
        let lib = StdLibrary::new();
        let source = lib.to_ne_source();
        for f in &lib.functions {
            assert!(
                source.contains(f.name),
                "Expected source to contain {}",
                f.name
            );
        }
    }

    #[test]
    fn test_stdlib_arity_consistency() {
        let lib = StdLibrary::new();
        for f in &lib.functions {
            let arity = f.arity;
            let params_in_name = if arity == 0 {
                0usize
            } else if arity < 0 {
                2usize
            } else {
                arity as usize
            };
            // body_sexpr starts with "(name" — count args by space-separated tokens minus 1
            let tokens: Vec<&str> = f
                .body_sexpr
                .trim_start_matches('(')
                .split_whitespace()
                .collect();
            let args_in_body = tokens.len().saturating_sub(1); // subtract the fn name itself
            assert_eq!(
                params_in_name, args_in_body,
                "Arity mismatch for {}: declared {} but body has {} args",
                f.name, params_in_name, args_in_body
            );
        }
    }

    #[test]
    fn test_stdlib_self_curious_has_arity_1() {
        let lib = StdLibrary::new();
        let curious = lib
            .functions
            .iter()
            .find(|f| f.name == "self_curious")
            .unwrap();
        assert_eq!(curious.arity, 1);
        assert_eq!(curious.body_sexpr, "(curious arg0)");
    }
}
