export const styles = {
  primary: 'var(--dsw-alias-label-primary)',
  secondary: 'var(--dsw-alias-label-secondary)',
  tertiary: 'var(--dsw-alias-label-tertiary)',
  dimmed: 'var(--dsw-alias-label-dimmed)',
  borderL2: 'var(--dsw-alias-border-l2)',
  borderL3: 'var(--dsw-alias-border-l3)',
  borderL4: 'var(--dsw-alias-border-l4)',
  // 宿主未定义 --dsw-alias-border-weak，保留官方插件页原本的 fallback（否则 border-color 会落到 currentColor）。
  borderWeak: 'var(--dsw-alias-border-weak, rgba(127, 127, 127, 0.2))',
  brand: 'var(--dsw-alias-brand-primary)',
  business: 'var(--dsw-alias-state-business-primary)',
  layer1: 'var(--dsw-alias-bg-layer-1)',
  layer3: 'var(--dsw-alias-bg-layer-3)',
  modulePlatform: 'var(--dsw-alias-bg-module-platform)',
  font: 'var(--dsw-font-family)',
  hover: 'var(--dsw-alias-interactive-bg-hover)',
  active: 'var(--dsw-alias-interactive-bg-active)',
  hoverSolid: 'var(--dsw-alias-interactive-bg-hover-solid)',
  hoverDanger: 'var(--dsw-alias-interactive-bg-hover-danger)',
  error: 'var(--dsw-alias-state-error-primary)',
  success: 'var(--dsw-alias-state-success-primary)',
  warn: 'var(--dsw-alias-state-warn-primary)',
  idle: 'var(--dsw-alias-state-idle-primary)',
  primaryFill: 'var(--dsw-alias-button-primary-fill)',
  primaryHover: 'var(--dsw-alias-button-primary-hover)',
  primaryFg: 'var(--dsw-alias-label-primary-foreground)',
  focusRing: {
    boxShadow: '0 0 0 2px var(--dsw-alias-border-l3)',
    outline: 'none',
  },
} as const
