#!/bin/bash
# Untracked-asset gate — "a clean clone must contain every real asset".
#
# Why this is a SEPARATE gate (2026-09-29):
#   R-EXIST-1 (RUST-STANDARDS.md §17.8) records that I twice asserted an asset
#   was "lost / never committed" after running ONLY `git log --all`. Both times
#   the file was sitting on disk, intact. One of them was a 1445-line design
#   doc that a P0 item depended on; the audit that followed found 78 docs + 82
#   non-doc assets (including 26 integration tests) that a clean clone would
#   simply not have.
#
#   This gate is the automatable half of that lesson: it re-detects the whole
#   class of problem, so the next agent does not have to remember to look.
#
# ⛔ READ-ONLY BY CONSTRUCTION (R-EXIST-2 / R-SCAN-4):
#   The only git plumbing used is `git ls-files` (read-only). There is no
#   `add`, no `clean`, no `-C`, no redirection into the repo, no `rm`.
#   If you ever add a mutating command to this file you break the rule that
#   makes it safe to run unattended.
#
# Exit codes:
#   0  no untracked real assets  (clean clone is complete)
#   1  untracked real assets found (clean clone would be INCOMPLETE)
#   2  misconfigured / not run inside a git work tree

set -uo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || {
  echo "FAIL: not inside a git work tree" >&2
  exit 2
}

# Dirs whose contents must exist in a clean clone. A file here that is neither
# tracked nor gitignored is a knowledge-loss risk (R-EXIST-1).
PROTECTED=(
  docs
  crates
  scripts
  skills
  sessions
  evals
  config
  neotrix-core/src
  neotrix-core/tests
  neotrix-core/examples
  neotrix-core/benches
)

# Names that are legitimately untracked. Keep this list explicit and short —
# every entry here is a place where a real asset could hide by accident.
#   * build/runtime artifacts ....... regenerated by cargo / the runtime
#   * *.bak-* ........................ manual backups
#   * *.disabled .................... tests deliberately turned off
#   * worktree-salvage/ ............. safety-net patches, not source
#   * __pycache__ / .DS_Store ....... tool litter
is_exempt() {
  case "$1" in
    *.rlib|*.rmeta|*.so|*.dylib|*.d) return 0 ;;
    *.db|*.db-journal|*.db-wal)     return 0 ;;
    *.bak|*.bak-*|*.orig|*.rej)      return 0 ;;
    *.disabled)                     return 0 ;;
    */__pycache__/*|*/.DS_Store)     return 0 ;;
    */worktree-salvage/*)           return 0 ;;
    *':memory:.lock')               return 0 ;;
    neotrix-core/config/crystal.toml) return 0 ;;  # holds real API keys
  esac
  return 1
}

total=0
report=""

for d in "${PROTECTED[@]}"; do
  [ -d "$d" ] || continue
  # --others --exclude-standard: untracked AND not ignored by .gitignore.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    is_exempt "$f" && continue
    lines=$(wc -l <"$f" 2>/dev/null | tr -d ' ')
    report+="  ${f}  (${lines:-?} lines)"$'\n'
    total=$((total + 1))
  done < <(git ls-files --others --exclude-standard -- "$d")
done

if [ "$total" -eq 0 ]; then
  echo "PASS: 0 untracked real assets — a clean clone is complete"
  exit 0
fi

echo "FAIL: $total untracked real asset(s) in protected dirs"
echo "       a clean clone would NOT contain these. See R-EXIST-1."
echo "$report" | sed '$d'
echo
echo "Per-file triage before 'git add' (R-EXIST-3):"
echo "  1. git check-ignore -v <file>   # should be NOT ignored"
echo "  2. inspect content              # any key/token => never add"
echo "  3. exempt? move it to the allowlist in this script, with a reason"
exit 1
