#!/usr/bin/env python3
"""gate_gen.py — 生成统一门面 `src-tauri/src/commands/_gate_table.rs`

输入 /tmp/eligible.json（name -> {module, async, args, ret}）。
输出 match 文件:
    "module" => {
        match action {
            "cmd" => { let p = gstr(args.get("p")); let out = super::cmd(p)?;
                       Ok(serde_json::to_value(out).map_err(|e| e.to_string())?) }
            ...
        }
    }
"""
import json, re, sys

EL = '/tmp/eligible.json'
OUT = 'src-tauri/src/commands/_gate_table.rs'
CAT_OUT = 'src-tauri/src/commands/_catalog_table.rs'

el = json.load(open(EL))

BUILTIN = {'String', 'usize', 'u32', 'u16', 'u8', 'u64', 'f64', 'bool',
           'Vec', 'serde_json::Value', 'Value'}

def split_args(raw_items):
    raw = ', '.join(raw_items)
    parts, depth, cur = [], 0, ''
    for ch in raw:
        if ch == '<': depth += 1
        elif ch == '>': depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += ch
    if cur.strip(): parts.append(cur)
    out = []
    for p in parts:
        p = p.strip()
        if not p: continue
        m = re.match(r'([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.+)', p)
        if m: out.append((m.group(1).strip(), m.group(2).strip()))
        else: out.append((p, '?'))
    return out

def is_struct_ty(t):
    t = t.strip()
    if t in BUILTIN: return False
    if t.startswith('Option<'): return is_struct_ty(t[7:-1])
    if t.startswith('Vec<'): return False
    if t.startswith('serde_json'): return False
    return bool(re.match(r'[A-Z][A-Za-z0-9_]*$', t))

def extract_holds(parsed):
    holds, call_args = [], []
    for pn, pt in parsed:
        t = pt.strip()
        if t == 'String':
            holds.append(f'let {pn} = gstr(args.get("{pn}"));')
        elif t == 'Option<String>':
            holds.append(f'let {pn} = goptstr(args.get("{pn}"));')
        elif t == 'usize':
            holds.append(f'let {pn} = gus(args.get("{pn}"));')
        elif t == 'u32':
            holds.append(f'let {pn} = gu32(args.get("{pn}"));')
        elif t == 'u16':
            holds.append(f'let {pn} = gu16(args.get("{pn}"));')
        elif t == 'u8':
            holds.append(f'let {pn} = gu8(args.get("{pn}"));')
        elif t == 'f64':
            holds.append(f'let {pn} = gf64(args.get("{pn}"));')
        elif t == 'bool':
            holds.append(f'let {pn} = gb(args.get("{pn}"));')
        elif t == 'Option<bool>':
            holds.append(f'let {pn} = gob(args.get("{pn}"));')
        elif t == 'Option<u32>':
            holds.append(f'let {pn} = gopt_u32(args.get("{pn}"));')
        elif t == 'Option<usize>':
            holds.append(f'let {pn} = gopt_usize(args.get("{pn}"));')
        elif t == 'Option<u64>':
            holds.append(f'let {pn} = gopt_u64(args.get("{pn}"));')
        elif t == 'Vec<String>':
            holds.append(f'let {pn} = gvec(args.get("{pn}"));')
        elif t == 'Option<Vec<String>>':
            holds.append(f'let {pn} = gopt_vec(args.get("{pn}"));')
        elif t == 'serde_json::Value' or t == 'Value':
            holds.append(f'let {pn} = gjson(args.get("{pn}"));')
        elif t == 'Option<serde_json::Value>':
            holds.append(f'let {pn} = gopt_json(args.get("{pn}"));')
        elif t.startswith('Option<') and t.endswith('>') and is_struct_ty(t[7:-1]):
            inner = t[7:-1]
            holds.append(
                f'let {pn} = {{\n'
                f'                let v = args.get("{pn}");\n'
                f'                if v.map_or(true, |x| x.is_null()) {{ None }}\n'
                f'                else {{ Some(serde_json::from_value::<{inner}>(v.cloned().unwrap_or(Value::Null)).map_err(|e| e.to_string())?) }}\n'
                f'            }};'
            )
        elif is_struct_ty(t):
            holds.append(f'let {pn} = serde_json::from_value::<{t}>(gjson(args.get("{pn}"))).map_err(|e| e.to_string())?;')
        else:
            raise ValueError(f'unsupported param type {t} for {pn}')
        call_args.append(pn)
    return holds, call_args

def main():
    out = ['// AUTO-GENERATED by gate_gen.py — 统一门面匹配表。请勿手改。',
           'match module {']
    by_mod, skipped = {}, []
    skipped_names = set()
    for name, m in el.items():
        if m['async']:
            skipped.append(name)
            continue
        by_mod.setdefault(m['module'], []).append(name)

    for mod in sorted(by_mod):
        out.append(f'    "{mod}" => {{')
        out.append('        match action {')
        for name in sorted(by_mod[mod]):
            m = el[name]
            parsed = split_args(m['args'])
            ret = m['ret']
            try:
                holds, call_args = extract_holds(parsed)
            except ValueError:
                skipped.append(name)
                skipped_names.add(name)
                continue
            call = f'super::{name}({", ".join(call_args)})'
            out.append(f'            "{name}" => {{')
            for h in holds:
                out.append(f'                {h}')
            if 'Result' in ret:
                out.append(f'                match {call} {{')
                out.append('                    Ok(v) => Ok(serde_json::to_value(v).map_err(|e| e.to_string())?),')
                out.append('                    Err(e) => Err(e.to_string()),')
                out.append('                }')
            else:
                out.append(f'                Ok(serde_json::to_value(&{call}).map_err(|e| e.to_string())?)')
            out.append('            }')
        out.append(f'            _ => Err(format!("unified_invoke: {mod}: 未知 action: {{}}", action))')
        out.append('        }')
        out.append('    }')
    out.append('    _ => Err("unified_invoke: 未知 module".into())')
    out.append('}')

    open(OUT, 'w').write('\n'.join(out) + '\n')

    cat_lines = ['// AUTO-GENERATED catalog table. 请勿手改。',
                 'vec![']
    for mod in sorted(by_mod):
        for name in sorted(by_mod[mod]):
            if name in skipped_names:
                continue
            cat_lines.append(f'    json!{{{{"module": "{mod}", "action": "{name}"}}}},')
    cat_lines.append(']')
    open(CAT_OUT, 'w').write('\n'.join(cat_lines) + '\n')
    n = sum(len(v) for v in by_mod.values())
    print(f'generated {n} commands / {len(by_mod)} modules; skipped(sync/struct不兼容): {len(skipped)}')

if __name__ == '__main__':
    sys.exit(main())