use std::path::PathBuf;

/// 2-level self-model / local overrides hierarchy:
///
/// Level  | Location                          | Scope
/// -------|-----------------------------------|-------------------
/// 1      | `~/.neotrix/self-model.md`        | Runtime self-model (from MemoryLattice)
/// 2      | `./.opencode/*`                    | Local (per-workspace overrides)
///
/// The self-model is auto-generated by SelfModelGenerator each N cycles,
/// synthesized from MemoryLattice + ExperienceTree + BehavioralPersonality.
/// This replaces the old 4-level AGENTS.md hierarchy.
///
/// Self Is Not a File — consciousness no longer reads "who am I" from
/// static markdown. It reads the runtime snapshot of its own memory.
#[derive(Debug, Clone)]
pub struct RulesInjection {
    /// Raw content from each level, ordered by priority (lowest index = highest priority)
    pub layers: Vec<RulesLayer>,
    /// Merged, deduplicated rule lines
    pub merged: String,
}

#[derive(Debug, Clone)]
pub struct RulesLayer {
    pub path: PathBuf,
    pub content: String,
    pub level: usize,
}

impl RulesInjection {
    /// Load rules from the two-level hierarchy (file-based fallback).
    ///
    /// Level 1: `~/.neotrix/self-model.md` (written by SelfModelGenerator).
    /// Level 2: `./.opencode/*` (per-workspace overrides).
    ///
    /// ⚠️ DEPRECATED: Prefer `from_self_model()` which receives the self-model
    /// text in-memory from SelfModelGenerator::last_model() — "Self Is Not a File".
    /// This method reads from disk and remains as a fallback for entry points
    /// that don't have access to the runtime SelfModelGenerator (e.g. interactive
    /// TUI before BackgroundLoop starts).
    #[deprecated(since = "0.15.0", note = "Use from_self_model() — self-model should come from runtime SelfModelGenerator::last_model(), not disk")]
    pub fn load() -> Self {
        let mut layers = Self::load_level2_overrides();

        // Level 1: Runtime self-model (generated from MemoryLattice, written to disk)
        if let Some(layer) = Self::load_layer(
            1,
            dirs::home_dir()
                .unwrap_or_default()
                .join(".neotrix")
                .join("self-model.md"),
        ) {
            layers.push(layer);
        }

        Self::merge_layers(layers, "self-model.md (file fallback)")
    }

    /// Create RulesInjection from runtime self-model text directly.
    ///
    /// "Self Is Not a File" path: self-model comes from
    /// `SelfModelGenerator::last_model()` in memory. Level 2
    /// (`.opencode/` overrides) still reads from disk as a local
    /// customization layer.
    pub fn from_self_model(self_model: &str) -> Self {
        let mut layers = Self::load_level2_overrides();

        // Level 1: Runtime self-model (provided in-memory — no file read)
        if !self_model.is_empty() {
            layers.push(RulesLayer {
                path: PathBuf::from("<runtime-self-model>"),
                content: self_model.to_string(),
                level: 1,
            });
        }

        Self::merge_layers(layers, "runtime-self-model (in-memory)")
    }

    /// Build a complete system prompt from self-model text directly.
    ///
    /// This is the "Self Is Not a File" entry point — no file dependency.
    /// Calls `from_self_model()` internally and merges into the base prompt.
    pub fn build_system_prompt(self_model: &str, base_prompt: &str) -> String {
        let rules = Self::from_self_model(self_model);
        rules.inject_into_prompt(base_prompt)
    }

    /// Load level 2 overrides only (`.opencode/` directory).
    /// Shared by `load()` and `from_self_model()`.
    fn load_level2_overrides() -> Vec<RulesLayer> {
        let mut layers = Vec::new();
        let opencode_dir = std::env::current_dir()
            .unwrap_or_default()
            .join(".opencode");
        if opencode_dir.exists() && opencode_dir.is_dir() {
            let mut local_rules = String::new();
            if let Ok(entries) = std::fs::read_dir(&opencode_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path
                        .extension()
                        .is_some_and(|e| e == "md" || e == "json" || e == "jsonc")
                    {
                        if let Ok(content) = std::fs::read_to_string(&path) {
                            local_rules.push_str(&format!(
                                "\n// from {}\n{}\n",
                                path.display(),
                                content
                            ));
                        }
                    }
                }
            }
            if !local_rules.is_empty() {
                layers.push(RulesLayer {
                    path: opencode_dir,
                    content: local_rules,
                    level: 2,
                });
            }
        }
        layers
    }

    /// Merge layers sorted by level into a single string.
    fn merge_layers(mut layers: Vec<RulesLayer>, source_label: &str) -> Self {
        let mut merged = String::new();
        layers.sort_by_key(|l| l.level);
        for layer in &layers {
            merged.push_str(&format!(
                "\n// === Level {}: {} ===\n",
                layer.level,
                layer.path.display()
            ));
            merged.push_str(&layer.content);
            merged.push('\n');
        }

        log::info!(
            "[rules] loaded {} layers ({} total chars) — source: {}",
            layers.len(),
            merged.len(),
            source_label,
        );

        RulesInjection { layers, merged }
    }

    fn load_layer(level: usize, path: PathBuf) -> Option<RulesLayer> {
        if path.exists() {
            match std::fs::read_to_string(&path) {
                Ok(content) => {
                    log::info!(
                        "[rules] level {}: loaded {} ({} chars)",
                        level,
                        path.display(),
                        content.len()
                    );
                    Some(RulesLayer {
                        path,
                        content,
                        level,
                    })
                }
                Err(e) => {
                    log::warn!(
                        "[rules] level {}: {} read error: {}",
                        level,
                        path.display(),
                        e
                    );
                    None
                }
            }
        } else {
            log::debug!(
                "[rules] level {}: {} not found, skipping",
                level,
                path.display()
            );
            None
        }
    }

    /// Inject merged rules into a prompt/system message
    #[allow(dead_code)]
    pub fn inject_into_prompt(&self, base_prompt: &str) -> String {
        if self.merged.is_empty() {
            return base_prompt.to_string();
        }
        format!(
            "{}\n\n---\n## System Rules\n{}\n---",
            base_prompt, self.merged
        )
    }
}

impl Default for RulesInjection {
    /// Default: empty self-model, only loads level 2 overrides from disk.
    fn default() -> Self {
        Self::from_self_model("")
    }
}
