use super::exploration_pipeline::ExploreDomain;

pub fn seed_urls_by_domain(domain: ExploreDomain) -> Vec<String> {
    match domain {
        ExploreDomain::Parapsychology => vec![
            "https://en.wikipedia.org/wiki/Parapsychology",
            "https://en.wikipedia.org/wiki/Telepathy",
            "https://en.wikipedia.org/wiki/Precognition",
            "https://en.wikipedia.org/wiki/Psychokinesis",
            "https://en.wikipedia.org/wiki/Near-death_experience",
            "https://en.wikipedia.org/wiki/Extrant_world_sense_perception",
            "https://en.wikipedia.org/wiki/Ganzfeld_experiment",
            "https://en.wikipedia.org/wiki/Remote_viewing",
            "https://en.wikipedia.org/wiki/Reincarnation",
            "https://en.wikipedia.org/wiki/Mediumship",
            "https://en.wikipedia.org/wiki/Paranormal",
            "https://en.wikipedia.org/wiki/Consciousness",
            "https://en.wikipedia.org/wiki/Hard_problem_of_consciousness",
            "https://en.wikipedia.org/wiki/Anomalous_cognition",
            "https://en.wikipedia.org/wiki/Micro-PK",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::Theology => vec![
            "https://en.wikipedia.org/wiki/Theology",
            "https://en.wikipedia.org/wiki/Comparative_religion",
            "https://en.wikipedia.org/wiki/Abrahamic_religions",
            "https://en.wikipedia.org/wiki/Christian_theology",
            "https://en.wikipedia.org/wiki/Islamic_theology",
            "https://en.wikipedia.org/wiki/Jewish_philosophy",
            "https://en.wikipedia.org/wiki/Buddhist_theology",
            "https://en.wikipedia.org/wiki/Hindu_philosophy",
            "https://en.wikipedia.org/wiki/Mysticism",
            "https://en.wikipedia.org/wiki/Apologetics",
            "https://en.wikipedia.org/wiki/Eschatology",
            "https://en.wikipedia.org/wiki/Soteriology",
            "https://en.wikipedia.org/wiki/Natural_theology",
            "https://en.wikipedia.org/wiki/Existence_of_God",
            "https://en.wikipedia.org/wiki/Theodicy",
            "https://en.wikipedia.org/wiki/Liberation_theology",
            "https://en.wikipedia.org/wiki/Process_theology",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::EsotericStudies => vec![
            "https://en.wikipedia.org/wiki/Esotericism",
            "https://en.wikipedia.org/wiki/Hermeticism",
            "https://en.wikipedia.org/wiki/Alchemy",
            "https://en.wikipedia.org/wiki/Astrology",
            "https://en.wikipedia.org/wiki/Kabbalah",
            "https://en.wikipedia.org/wiki/Gnosticism",
            "https://en.wikipedia.org/wiki/Ceremonial_magic",
            "https://en.wikipedia.org/wiki/Western_esotericism",
            "https://en.wikipedia.org/wiki/Theosophy",
            "https://en.wikipedia.org/wiki/Rosicrucianism",
            "https://en.wikipedia.org/wiki/Tarot",
            "https://en.wikipedia.org/wiki/Sacred_geometry",
            "https://en.wikipedia.org/wiki/Esoteric_Christianity",
            "https://en.wikipedia.org/wiki/Hermetic_Qabalah",
            "https://en.wikipedia.org/wiki/Enochian_magic",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::Wiki => vec![
            "https://en.wikipedia.org/wiki/Philosophy",
            "https://en.wikipedia.org/wiki/Science",
            "https://en.wikipedia.org/wiki/Epistemology",
            "https://en.wikipedia.org/wiki/Metaphysics",
            "https://en.wikipedia.org/wiki/Ethics",
            "https://en.wikipedia.org/wiki/Logic",
            "https://en.wikipedia.org/wiki/Philosophy_of_science",
            "https://en.wikipedia.org/wiki/Philosophy_of_mind",
            "https://en.wikipedia.org/wiki/Consciousness",
            "https://en.wikipedia.org/wiki/Free_will",
            "https://en.wikipedia.org/wiki/Phenomenology",
            "https://en.wikipedia.org/wiki/Existentialism",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::Papers => vec![
            "https://arxiv.org/abs/2303.08774",
            "https://arxiv.org/abs/2401.10400",
            "https://arxiv.org/abs/2205.01901",
            "https://arxiv.org/abs/2107.06557",
            "https://arxiv.org/abs/1803.05088",
            "https://arxiv.org/abs/2101.07469",
            "https://arxiv.org/abs/1911.01597",
            "https://arxiv.org/abs/2012.04449",
            "https://arxiv.org/abs/1907.03344",
            "https://arxiv.org/abs/2305.10197",
            "https://arxiv.org/abs/2204.05033",
            "https://arxiv.org/abs/2108.02867",
            "https://arxiv.org/abs/2110.03645",
            "https://arxiv.org/abs/2306.05125",
            "https://arxiv.org/abs/2206.07654",
            "https://arxiv.org/abs/2101.06867",
            "https://arxiv.org/abs/2203.06214",
            "https://arxiv.org/abs/2302.04346",
            "https://arxiv.org/abs/2109.06071",
            "https://arxiv.org/abs/2401.07474",
            "https://arxiv.org/abs/2308.08500",
            "https://arxiv.org/abs/2402.13773",
            "https://arxiv.org/abs/2211.14789",
            "https://arxiv.org/abs/2105.03416",
            "https://arxiv.org/abs/2207.04941",
            "https://arxiv.org/abs/2304.08693",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::GitHub => vec![
            "https://github.com/rust-lang/rust",
            "https://github.com/tokio-rs/tokio",
            "https://github.com/serde-rs/serde",
            "https://github.com/ratatui-org/ratatui",
            "https://github.com/huggingface/candle",
            "https://github.com/rust-ml/linfa",
            "https://github.com/nicktolas/dfdx",
            "https://github.com/tract-rs/tract",
            "https://github.com/jerry73204/leaf-ai",
            "https://github.com/nathaneastwood/tarpc-ml",
            "https://github.com/microsoft/autogen",
            "https://github.com/crewAIInc/crewAI",
            "https://github.com/langchain-ai/langgraph",
            "https://github.com/modelcontextprotocol/servers",
            "https://github.com/anthropics/claude-code",
            "https://github.com/opencode-ai/opencode",
            "https://github.com/artem-oppermann/Integrated-Information-Theory",
            "https://github.com/wmayner/pyphi",
            "https://github.com/NeuromatchAcademy/hyperdimensional-computing",
            "https://github.com/IBM/hd-computing",
            "https://github.com/ai-nikolai/wolfram-model-ecology",
            "https://github.com/projectdiscovery/nuclei",
            "https://github.com/zaproxy/zaproxy",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::Consciousness => vec![
            "https://en.wikipedia.org/wiki/Integrated_information_theory",
            "https://en.wikipedia.org/wiki/Global_workspace_theory",
            "https://en.wikipedia.org/wiki/Higher-order_theories_of_consciousness",
            "https://en.wikipedia.org/wiki/Predictive_processing",
            "https://en.wikipedia.org/wiki/Free_energy_principle",
            "https://en.wikipedia.org/wiki/Attention_schema_theory",
            "https://en.wikipedia.org/wiki/Phenomenology",
            "https://en.wikipedia.org/wiki/Qualia",
            "https://en.wikipedia.org/wiki/Panpsychism",
            "https://en.wikipedia.org/wiki/Awareness",
            "https://en.wikipedia.org/wiki/Self-awareness",
            "https://en.wikipedia.org/wiki/Metacognition",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::RustML => vec![
            "https://github.com/rust-ml/linfa",
            "https://github.com/guillaume-be/rust-bert",
            "https://github.com/huggingface/candle",
            "https://github.com/LaurentMazare/tch-rs",
            "https://github.com/burn-rs/burn",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::Security => vec![
            "https://github.com/RustSec/rustsec",
            "https://github.com/rust-unofficial/patterns",
            "https://owasp.org/www-project-top-ten/",
            "https://cheatsheetseries.owasp.org/",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::MathPhysics => vec![
            "https://en.wikipedia.org/wiki/Mathematical_physics",
            "https://en.wikipedia.org/wiki/Theoretical_physics",
            "https://en.wikipedia.org/wiki/Quantum_mechanics",
            "https://en.wikipedia.org/wiki/Statistical_mechanics",
            "https://en.wikipedia.org/wiki/Dynamical_systems",
            "https://en.wikipedia.org/wiki/Category_theory",
        ]
        .into_iter()
        .map(String::from)
        .collect(),
        ExploreDomain::General => vec![],
    }
}
