//! # Speculative Decoding Engine
//!
//! Inspired by GPT-5.6's speculative decoding technique that uses a smaller
//! draft model to propose tokens, which are then verified by the primary model
//! in parallel. This reduces expensive sequential computation.
//!
//! ## Design Principles
//! - Draft-then-verify: Small model proposes, large model verifies
//! - Parallel verification: Verify multiple tokens in one forward pass
//! - Acceptance tracking: Monitor draft acceptance rates
//! - Adaptive drafting: Adjust draft length based on acceptance
//! - Efficiency metrics: Track speedup and cost savings

use serde::{Deserialize, Serialize};


/// Draft model configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DraftModelConfig {
    pub model_id: String,
    pub model_name: String,
    pub parameters: u64,       // Number of parameters
    pub max_draft_length: u32, // Maximum tokens to draft
    pub temperature: f32,
    pub top_k: u32,
    pub top_p: f32,
}

/// Target model configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TargetModelConfig {
    pub model_id: String,
    pub model_name: String,
    pub parameters: u64,
    pub max_sequence_length: u32,
    pub temperature: f32,
}

/// Speculative decoding request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpeculativeRequest {
    pub id: String,
    pub prompt: String,
    pub max_tokens: u32,
    pub draft_config: DraftModelConfig,
    pub target_config: TargetModelConfig,
    pub verification_strategy: VerificationStrategy,
}

/// Verification strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum VerificationStrategy {
    /// Standard verification: verify all drafted tokens
    Standard,
    /// Hierarchical verification: early-exit for fast rejection (HiSpec pattern)
    Hierarchical,
    /// Pipeline verification: overlap drafting and verification (SPD pattern)
    Pipeline,
    /// Adaptive: adjust based on acceptance rate
    Adaptive,
}

/// Draft token with metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DraftToken {
    pub token_id: u32,
    pub token_text: String,
    pub probability: f32,
    pub draft_position: u32,
    pub hidden_state: Option<Vec<f32>>, // For hidden-state based drafting
}

/// Verification result for a single token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenVerification {
    pub draft_token: DraftToken,
    pub target_token_id: u32,
    pub target_probability: f32,
    pub accepted: bool,
    pub rejection_reason: Option<String>,
    pub verification_latency_ms: u64,
}

/// Speculative decoding result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpeculativeResult {
    pub request_id: String,
    pub output_tokens: Vec<OutputToken>,
    pub draft_tokens: Vec<DraftToken>,
    pub verification_results: Vec<TokenVerification>,
    pub metrics: SpeculativeMetrics,
    pub strategy_used: VerificationStrategy,
}

/// Output token (final accepted token)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputToken {
    pub token_id: u32,
    pub token_text: String,
    pub probability: f32,
    pub position: u32,
    pub source: TokenSource,
}

/// Source of the token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TokenSource {
    /// Token came from draft model and was accepted
    DraftAccepted,
    /// Token came from target model (draft was rejected)
    TargetGenerated,
    /// Token was generated by target model directly (no draft)
    TargetDirect,
}

/// Speculative decoding metrics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpeculativeMetrics {
    pub total_draft_tokens: u32,
    pub accepted_draft_tokens: u32,
    pub rejected_draft_tokens: u32,
    pub acceptance_rate: f32,
    pub total_target_verifications: u32,
    pub avg_verification_latency_ms: f64,
    pub total_generation_time_ms: u64,
    pub tokens_per_second: f64,
    pub speedup_factor: f64, // vs standard autoregressive decoding
    pub cost_savings: f64,   // Estimated cost savings
}

/// Speculative Decoding Engine
pub struct SpeculativeDecodingEngine {
    draft_models: Vec<DraftModelConfig>,
    target_models: Vec<TargetModelConfig>,
    history: Vec<SpeculativeResult>,
}

impl SpeculativeDecodingEngine {
    pub fn new() -> Self {
        let draft_models = vec![
            DraftModelConfig {
                model_id: "gpt-5.6-luna".into(),
                model_name: "GPT-5.6 Luna".into(),
                parameters: 50_000_000_000, // 50B
                max_draft_length: 8,
                temperature: 0.7,
                top_k: 40,
                top_p: 0.9,
            },
            DraftModelConfig {
                model_id: "deepseek-r1:7b".into(),
                model_name: "DeepSeek R1 7B".into(),
                parameters: 7_000_000_000, // 7B
                max_draft_length: 6,
                temperature: 0.7,
                top_k: 40,
                top_p: 0.9,
            },
            DraftModelConfig {
                model_id: "qwen2.5-coder:7b".into(),
                model_name: "Qwen2.5 Coder 7B".into(),
                parameters: 7_000_000_000, // 7B
                max_draft_length: 8,
                temperature: 0.7,
                top_k: 40,
                top_p: 0.9,
            },
        ];

        let target_models = vec![
            TargetModelConfig {
                model_id: "gpt-5.6-sol".into(),
                model_name: "GPT-5.6 Sol".into(),
                parameters: 500_000_000_000, // 500B
                max_sequence_length: 128_000,
                temperature: 0.7,
            },
            TargetModelConfig {
                model_id: "claude-opus-4-20250514".into(),
                model_name: "Claude Opus 4".into(),
                parameters: 500_000_000_000, // 500B
                max_sequence_length: 200_000,
                temperature: 0.7,
            },
            TargetModelConfig {
                model_id: "claude-sonnet-4-20250514".into(),
                model_name: "Claude Sonnet 4".into(),
                parameters: 200_000_000_000, // 200B
                max_sequence_length: 200_000,
                temperature: 0.7,
            },
        ];

        Self {
            draft_models,
            target_models,
            history: Vec::new(),
        }
    }

    /// Generate tokens using speculative decoding
    pub fn generate(&mut self, request: &SpeculativeRequest) -> SpeculativeResult {
        let start_time = std::time::Instant::now();

        // Simulate draft generation
        let draft_tokens = self.generate_draft_tokens(request);

        // Simulate verification
        let verification_results = self.verify_draft_tokens(request, &draft_tokens);

        // Collect accepted tokens
        let mut output_tokens = Vec::new();
        let mut accepted_count = 0;
        let mut rejected_count = 0;

        for verification in &verification_results {
            if verification.accepted {
                output_tokens.push(OutputToken {
                    token_id: verification.draft_token.token_id,
                    token_text: verification.draft_token.token_text.clone(),
                    probability: verification.draft_token.probability,
                    position: verification.draft_token.draft_position,
                    source: TokenSource::DraftAccepted,
                });
                accepted_count += 1;
            } else {
                // Generate token from target model
                output_tokens.push(OutputToken {
                    token_id: verification.target_token_id,
                    token_text: format!("target_{}", verification.target_token_id),
                    probability: verification.target_probability,
                    position: verification.draft_token.draft_position,
                    source: TokenSource::TargetGenerated,
                });
                rejected_count += 1;
            }
        }

        let total_time_ms = start_time.elapsed().as_millis() as u64;
        let total_tokens = output_tokens.len() as u32;
        let tokens_per_second = if total_time_ms > 0 {
            (total_tokens as f64 / total_time_ms as f64) * 1000.0
        } else {
            0.0
        };

        // Calculate speedup vs standard autoregressive decoding
        // Standard: 1 token per forward pass
        // Speculative: Multiple tokens per verification pass
        let verification_count = verification_results.len() as f64;
        let speedup_factor = if verification_count > 0.0 {
            total_tokens as f64 / verification_count
        } else {
            1.0
        };

        // Estimate cost savings
        // Draft model is ~10x cheaper than target model
        let draft_cost_per_token = 0.0001; // Example
        let target_cost_per_token = 0.001; // Example
        let draft_cost = total_tokens as f64 * draft_cost_per_token;
        let target_cost = total_tokens as f64 * target_cost_per_token;
        let cost_savings = (target_cost - draft_cost) / target_cost;

        let metrics = SpeculativeMetrics {
            total_draft_tokens: draft_tokens.len() as u32,
            accepted_draft_tokens: accepted_count,
            rejected_draft_tokens: rejected_count,
            acceptance_rate: if draft_tokens.len() > 0 {
                accepted_count as f32 / draft_tokens.len() as f32
            } else {
                0.0
            },
            total_target_verifications: verification_results.len() as u32,
            avg_verification_latency_ms: verification_results
                .iter()
                .map(|v| v.verification_latency_ms)
                .sum::<u64>() as f64
                / verification_results.len() as f64,
            total_generation_time_ms: total_time_ms,
            tokens_per_second,
            speedup_factor,
            cost_savings,
        };

        let result = SpeculativeResult {
            request_id: request.id.clone(),
            output_tokens,
            draft_tokens,
            verification_results,
            metrics,
            strategy_used: request.verification_strategy.clone(),
        };

        self.history.push(result.clone());
        result
    }

    /// Generate draft tokens (simulated)
    fn generate_draft_tokens(&self, request: &SpeculativeRequest) -> Vec<DraftToken> {
        let max_draft = request.draft_config.max_draft_length;
        let mut draft_tokens = Vec::new();

        for i in 0..max_draft {
            draft_tokens.push(DraftToken {
                token_id: 1000 + i,
                token_text: format!("draft_{}", i),
                probability: 0.8 - (i as f32 * 0.05), // Probability decreases with position
                draft_position: i,
                hidden_state: Some(vec![0.1; 64]), // Simulated hidden state
            });
        }

        draft_tokens
    }

    /// Verify draft tokens against target model (simulated)
    fn verify_draft_tokens(
        &self,
        _request: &SpeculativeRequest,
        draft_tokens: &[DraftToken],
    ) -> Vec<TokenVerification> {
        let mut results = Vec::new();

        for draft_token in draft_tokens {
            // Simulate verification: accept with decreasing probability
            let acceptance_probability = 0.9 - (draft_token.draft_position as f32 * 0.1);
            let accepted = rand::random::<f32>() < acceptance_probability;

            results.push(TokenVerification {
                draft_token: draft_token.clone(),
                target_token_id: if accepted {
                    draft_token.token_id
                } else {
                    draft_token.token_id + 100 // Different token
                },
                target_probability: if accepted {
                    draft_token.probability
                } else {
                    0.7
                },
                accepted,
                rejection_reason: if accepted {
                    None
                } else {
                    Some("Token mismatch".into())
                },
                verification_latency_ms: 10 + (draft_token.draft_position as u64 * 2),
            });
        }

        results
    }

    /// Get acceptance rate statistics
    pub fn get_acceptance_stats(&self) -> AcceptanceStats {
        if self.history.is_empty() {
            return AcceptanceStats {
                avg_acceptance_rate: 0.0,
                min_acceptance_rate: 0.0,
                max_acceptance_rate: 0.0,
                total_requests: 0,
                avg_speedup: 0.0,
            };
        }

        let rates: Vec<f32> = self
            .history
            .iter()
            .map(|r| r.metrics.acceptance_rate)
            .collect();

        let speedups: Vec<f64> = self
            .history
            .iter()
            .map(|r| r.metrics.speedup_factor)
            .collect();

        AcceptanceStats {
            avg_acceptance_rate: rates.iter().sum::<f32>() / rates.len() as f32,
            min_acceptance_rate: rates.iter().cloned().fold(f32::INFINITY, f32::min),
            max_acceptance_rate: rates.iter().cloned().fold(f32::NEG_INFINITY, f32::max),
            total_requests: self.history.len() as u32,
            avg_speedup: speedups.iter().sum::<f64>() / speedups.len() as f64,
        }
    }

    /// Get optimal draft length based on history
    pub fn get_optimal_draft_length(&self) -> u32 {
        if self.history.is_empty() {
            return 4; // Default
        }

        // Find draft length with highest acceptance rate
        let mut best_length = 4;
        let mut best_rate = 0.0;

        for result in &self.history {
            let length = result.draft_tokens.len() as u32;
            let rate = result.metrics.acceptance_rate;

            if rate > best_rate {
                best_rate = rate;
                best_length = length;
            }
        }

        best_length
    }

    /// Select best draft model for a given target model
    pub fn select_draft_model(&self, target_model_id: &str) -> Option<&DraftModelConfig> {
        // Simple heuristic: match by parameter ratio
        let target_params = self
            .target_models
            .iter()
            .find(|m| m.model_id == target_model_id)
            .map(|m| m.parameters)
            .unwrap_or(100_000_000_000);

        // Find draft model with ~10% of target parameters
        self.draft_models.iter().min_by_key(|d| {
            let ratio = d.parameters as f64 / target_params as f64;
            ((ratio - 0.1).abs() * 1000.0) as u64
        })
    }
}

/// Acceptance statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AcceptanceStats {
    pub avg_acceptance_rate: f32,
    pub min_acceptance_rate: f32,
    pub max_acceptance_rate: f32,
    pub total_requests: u32,
    pub avg_speedup: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_speculative_decoding() {
        let mut engine = SpeculativeDecodingEngine::new();
        let request = SpeculativeRequest {
            id: "test-1".into(),
            prompt: "Hello, world!".into(),
            max_tokens: 100,
            draft_config: DraftModelConfig {
                model_id: "deepseek-r1:7b".into(),
                model_name: "DeepSeek R1 7B".into(),
                parameters: 7_000_000_000,
                max_draft_length: 6,
                temperature: 0.7,
                top_k: 40,
                top_p: 0.9,
            },
            target_config: TargetModelConfig {
                model_id: "gpt-5.6-sol".into(),
                model_name: "GPT-5.6 Sol".into(),
                parameters: 500_000_000_000,
                max_sequence_length: 128_000,
                temperature: 0.7,
            },
            verification_strategy: VerificationStrategy::Standard,
        };

        let result = engine.generate(&request);
        assert!(!result.output_tokens.is_empty());
        assert!(result.metrics.speedup_factor > 1.0);
    }

    #[test]
    fn test_acceptance_stats() {
        let mut engine = SpeculativeDecodingEngine::new();

        // Run multiple requests
        for i in 0..5 {
            let request = SpeculativeRequest {
                id: format!("test-{}", i),
                prompt: "Test prompt".into(),
                max_tokens: 50,
                draft_config: DraftModelConfig {
                    model_id: "deepseek-r1:7b".into(),
                    model_name: "DeepSeek R1 7B".into(),
                    parameters: 7_000_000_000,
                    max_draft_length: 4,
                    temperature: 0.7,
                    top_k: 40,
                    top_p: 0.9,
                },
                target_config: TargetModelConfig {
                    model_id: "gpt-5.6-sol".into(),
                    model_name: "GPT-5.6 Sol".into(),
                    parameters: 500_000_000_000,
                    max_sequence_length: 128_000,
                    temperature: 0.7,
                },
                verification_strategy: VerificationStrategy::Standard,
            };

            engine.generate(&request);
        }

        let stats = engine.get_acceptance_stats();
        assert_eq!(stats.total_requests, 5);
        assert!(stats.avg_acceptance_rate > 0.0);
    }
}
