use std::collections::BTreeMap;
use std::path::Path;
use std::sync::Arc;
use std::time::SystemTime;
use tokio::sync::RwLock;

use crate::cli::commands::types::{CliCommand, CommandOutput};
use crate::neotrix::nt_memory_kb::KnowledgeBase;
use crate::neotrix::nt_mind::SelfIteratingBrain;

pub struct WikiCmd;

impl CliCommand for WikiCmd {
    fn name(&self) -> &str {
        "/wiki"
    }

    fn description(&self) -> &str {
        "Wiki: generate AGENTS.md | sync docs to KB | graph | search"
    }
    fn is_primary(&self) -> bool { false }


    fn execute(
        &self,
        args: &[String],
        _brain: Option<&Arc<RwLock<SelfIteratingBrain>>>,
    ) -> CommandOutput {
        if args.is_empty() {
            return CommandOutput::ok(
                "Wiki commands:\n  /wiki generate       AGENTS.md auto-gen\n  /wiki status         AGENTS.md status\n  /wiki sync [dir]     sync docs/ -> KB wiki\n  /wiki graph [file]   generate wiki graph HTML\n  /wiki query <text>   search KB wiki pages",
            );
        }
        match args[0].as_str() {
            "generate" => cmd_generate(),
            "status" => cmd_status(),
            "sync" => cmd_sync(args),
            "graph" => cmd_graph(args),
            "query" => cmd_query(args),
            _ => CommandOutput::err(&format!("Unknown subcommand: {}", args[0])),
        }
    }
}

fn cmd_sync(args: &[String]) -> CommandOutput {
    let dir = args.get(1).map(|s| s.as_str()).unwrap_or("docs");
    let dir_path = Path::new(dir);
    if !dir_path.exists() {
        return CommandOutput::err(&format!("Directory not found: {}", dir));
    }
    let kb = match KnowledgeBase::open(None) {
        Ok(kb) => kb,
        Err(e) => return CommandOutput::err(&format!("Cannot open KB: {}", e)),
    };
    match kb.wiki_sync(dir_path, dir) {
        Ok(report) => {
            let mut msg = format!("Wiki sync: {} pages, {} edges", report.synced, report.edges_created);
            if !report.errors.is_empty() {
                msg.push_str(&format!(" ({} errors)", report.errors.len()));
                for (stem, err) in report.errors.iter().take(5) {
                    msg.push_str(&format!("\n  {}: {}", stem, err));
                }
            }
            CommandOutput::ok(&msg)
        }
        Err(e) => CommandOutput::err(&format!("Wiki sync failed: {}", e)),
    }
}

fn cmd_graph(args: &[String]) -> CommandOutput {
    let output = args.get(1).map(|s| s.as_str()).unwrap_or("wiki-graph.html");
    let kb = match KnowledgeBase::open(None) {
        Ok(kb) => kb,
        Err(e) => return CommandOutput::err(&format!("Cannot open KB: {}", e)),
    };
    match kb.wiki_graph_html() {
        Ok(html) => match std::fs::write(output, &html) {
            Ok(()) => CommandOutput::ok(&format!("Wiki graph written to {}", output)),
            Err(e) => CommandOutput::err(&format!("Failed to write {}: {}", output, e)),
        },
        Err(e) => CommandOutput::err(&format!("Wiki graph failed: {}", e)),
    }
}

fn cmd_query(args: &[String]) -> CommandOutput {
    if args.len() < 2 {
        return CommandOutput::err("Usage: /wiki query <text>");
    }
    let query = args[1..].join(" ");
    let kb = match KnowledgeBase::open(None) {
        Ok(kb) => kb,
        Err(e) => return CommandOutput::err(&format!("Cannot open KB: {}", e)),
    };
    match kb.wiki_query(&query, 20) {
        Ok(results) => {
            if results.is_empty() {
                return CommandOutput::ok("No wiki pages found.");
            }
            let mut msg = format!("Wiki results for \"{}\":\n", query);
            for (i, r) in results.iter().enumerate() {
                let s = if r.summary.len() > 80 { format!("{}...", &r.summary[..77]) } else { r.summary.clone() };
                msg.push_str(&format!("  {}. {} (score: {:.2})\n     {}\n", i + 1, r.title, r.score, s));
            }
            CommandOutput::ok(&msg)
        }
        Err(e) => CommandOutput::err(&format!("Wiki query failed: {}", e)),
    }
}

// ---- Existing /wiki generate and /wiki status (unchanged) ----

fn cmd_generate() -> CommandOutput {
    let root = Path::new(".");
    let project_name = detect_project_name(root);
    let src_dir = root.join("neotrix-core").join("src");
    let stats = match collect_stats(&src_dir) {
        Ok(s) => s,
        Err(e) => return CommandOutput::err(&format!("Failed to scan source tree: {}", e)),
    };
    let mut md = String::new();
    md.push_str(&format!("# {} — Wiki (Auto-generated)\n\n", project_name));
    md.push_str(&format!("> Auto-generated by `/wiki generate` on {}\n\n", chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));
    md.push_str("## Codebase Overview\n\n| Metric | Value |\n|--------|-------|\n");
    md.push_str(&format!("| Total `.rs` files | {} |\n", stats.file_count));
    md.push_str(&format!("| Total lines of code | {} |\n", stats.total_lines));
    md.push_str(&format!("| Modules (subdirectories with mod.rs) | {} |\n", stats.module_count));
    md.push_str(&format!("| Source root | `{}` |\n", src_dir.display()));
    md.push('\n');
    md.push_str("## Layer Architecture\n\n| Layer | Directory | Files | Lines |\n|-------|-----------|-------|-------|\n");
    for (layer, info) in &stats.layers {
        md.push_str(&format!("| `{}` | `{}` | {} | {} |\n", layer, info.path, info.files, info.lines));
    }
    md.push('\n');
    md.push_str("## Project Structure\n\n```\n");
    md.push_str(&build_tree(root, 0, 3));
    md.push_str("```\n\n");
    md.push_str("## Build & Test\n\n```bash\ncargo build -p neotrix\ncargo build --features full --lib -p neotrix\ncargo test -p neotrix --lib\ncargo check --lib -p neotrix\n```\n\n");
    md.push_str("## Architecture Domains\n\n| Domain | Prefix | Files | Lines |\n|--------|--------|-------|-------|\n");
    for (domain, info) in &stats.domains {
        md.push_str(&format!("| {} | `{}` | {} | {} |\n", domain, info.path, info.files, info.lines));
    }
    md.push('\n');
    if !stats.key_types.is_empty() {
        md.push_str("## Key Types & Traits\n\n| Type/Trait | File | Kind |\n|------------|------|------|\n");
        for kt in &stats.key_types {
            md.push_str(&format!("| `{}` | `{}` | {} |\n", kt.name, kt.file, kt.kind));
        }
        md.push('\n');
    }
    if !stats.cli_commands.is_empty() {
        md.push_str("## CLI Commands\n\n| Command | Description |\n|---------|-------------|\n");
        for cmd in &stats.cli_commands {
            md.push_str(&format!("| `{}` | {} |\n", cmd.name, cmd.description));
        }
        md.push('\n');
    }
    match std::fs::write(root.join("AGENTS.md"), &md) {
        Ok(()) => CommandOutput::ok(&format!("AGENTS.md written: {} bytes, {} files, {} lines", md.len(), stats.file_count, stats.total_lines)),
        Err(e) => CommandOutput::err(&format!("Failed to write AGENTS.md: {}", e)),
    }
}

fn cmd_status() -> CommandOutput {
    let path = Path::new("AGENTS.md");
    if !path.exists() {
        return CommandOutput::not_found("AGENTS.md does not exist");
    }
    let meta = match path.metadata() {
        Ok(m) => m,
        Err(e) => return CommandOutput::err(&format!("Cannot read metadata: {}", e)),
    };
    let size = meta.len();
    let modified = meta.modified().ok();
    let age_str = modified
        .and_then(|m| SystemTime::now().duration_since(m).ok())
        .map(|d| {
            let secs = d.as_secs();
            if secs < 60 { format!("{}s ago", secs) }
            else if secs < 3600 { format!("{}m {}s ago", secs / 60, secs % 60) }
            else if secs < 86400 { format!("{}h {}m ago", secs / 3600, (secs % 3600) / 60) }
            else { format!("{}d {}h ago", secs / 86400, (secs % 86400) / 3600) }
        })
        .unwrap_or_else(|| "unknown".to_string());
    CommandOutput::ok(&format!("AGENTS.md: {} bytes, modified {}", size, age_str))
}

// ---- Stats collection (unchanged) ----

#[derive(Default)]
struct CodebaseStats { file_count: usize, total_lines: usize, module_count: usize, layers: BTreeMap<String, LayerInfo>, domains: BTreeMap<String, DomainInfo>, key_types: Vec<TypeInfo>, cli_commands: Vec<CmdInfo> }
struct LayerInfo { path: String, files: usize, lines: usize }
struct DomainInfo { path: String, files: usize, lines: usize }
struct TypeInfo { name: String, file: String, kind: String }
struct CmdInfo { name: String, description: String }

fn detect_project_name(root: &Path) -> String {
    let cargo = root.join("Cargo.toml");
    if cargo.exists() {
        if let Ok(content) = std::fs::read_to_string(&cargo) {
            for line in content.lines() {
                let trimmed = line.trim();
                if let Some(name) = trimmed.strip_prefix("name = \"") {
                    if let Some(end) = name.find('"') {
                        return name[..end].to_string();
                    }
                }
            }
        }
    }
    "NeoTrix".to_string()
}

fn collect_stats(src_dir: &Path) -> Result<CodebaseStats, String> {
    let mut stats = CodebaseStats::default();
    if !src_dir.exists() { return Err(format!("Source dir not found: {}", src_dir.display())); }
    let mut dirs_to_scan: Vec<std::path::PathBuf> = vec![src_dir.to_path_buf()];
    let mut seen_dirs = std::collections::HashSet::new();
    let mut key_types_seen = std::collections::HashSet::new();
    while let Some(dir) = dirs_to_scan.pop() {
        if !seen_dirs.insert(dir.clone()) { continue; }
        let entries = match std::fs::read_dir(&dir) { Ok(e) => e, Err(_) => continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() { dirs_to_scan.push(path.clone()); }
            else if path.extension().is_some_and(|ext| ext == "rs") {
                let relative = path.strip_prefix(src_dir.parent().unwrap_or(Path::new("."))).unwrap_or(&path).display().to_string();
                let content = match std::fs::read_to_string(&path) { Ok(c) => c, Err(_) => continue };
                let line_count = content.lines().count();
                stats.file_count += 1; stats.total_lines += line_count;
                let path_str = path.display().to_string();
                for (layer_key, layer_prefix) in &[("L0 Substrate","l0_substrate"),("L1 Body","l1_body"),("L2 World","l2_world"),("L3 Memory","l3_memory"),("L4 Cognition","l4_cognition"),("L5 Consciousness","l5_consciousness"),("L6 Self","l6_self"),("L7 Capability","l7_capability"),("L8 Autonomic","l8_autonomic"),("L9 Transcendent","l9_transcendent")] {
                    if path_str.contains(layer_prefix) {
                        let entry = stats.layers.entry(layer_key.to_string()).or_insert_with(|| LayerInfo { path: format!("src/{}", layer_prefix), files: 0, lines: 0 });
                        entry.files += 1; entry.lines += line_count; break;
                    }
                }
                for component in path.components() {
                    if let std::path::Component::Normal(name) = component {
                        let name_str = name.to_string_lossy();
                        if name_str.starts_with("nt_") && name_str.contains('_') {
                            let entry = stats.domains.entry(name_str.to_string()).or_insert_with(|| DomainInfo { path: relative.clone(), files: 0, lines: 0 });
                            entry.files += 1; entry.lines += line_count; break;
                        }
                    }
                }
                for line in content.lines() {
                    let trimmed = line.trim();
                    for prefix in ["pub struct ", "struct ", "pub trait ", "trait ", "pub enum ", "enum "] {
                        if let Some(name) = trimmed.strip_prefix(prefix) {
                            if let Some(end) = name.find(|c: char| !c.is_alphanumeric() && c != '_') {
                                let type_name = name[..end].to_string();
                                if key_types_seen.insert(type_name.clone()) {
                                    let kind = if prefix.contains("struct") { "struct" } else if prefix.contains("trait") { "trait" } else { "enum" };
                                    stats.key_types.push(TypeInfo { name: type_name, file: relative.clone(), kind: kind.to_string() });
                                }
                            }
                        }
                    }
                }
                if path_str.contains("cli/commands") && !path_str.ends_with("mod.rs") && !path_str.ends_with("types.rs") && !path_str.ends_with("registry.rs") {
                    for line in content.lines() {
                        let trimmed = line.trim();
                        if let Some(rest) = trimmed.strip_prefix("fn name(&self) -> &str {") {
                            let cmd_name = rest.trim().trim_matches(|c: char| c == ' ' || c == '"' || c == '{' || c == '}').to_string();
                            if !cmd_name.is_empty() {
                                let desc_text = content.lines().find_map(|l| {
                                    let t = l.trim();
                                    t.strip_prefix("fn description(&self) -> &str {").and_then(|s| {
                                        let clean = s.trim().trim_matches(|c: char| c == ' ' || c == '"' || c == '{' || c == '}').to_string();
                                        if !clean.is_empty() { Some(clean) } else { None }
                                    })
                                }).unwrap_or_default();
                                stats.cli_commands.push(CmdInfo { name: format!("/{}", cmd_name), description: desc_text });
                                break;
                            }
                        }
                    }
                }
            }
        }
    }
    let mut mod_dirs = std::collections::HashSet::new();
    let mut scan_dirs: Vec<std::path::PathBuf> = vec![src_dir.to_path_buf()];
    while let Some(dir) = scan_dirs.pop() {
        if dir.join("mod.rs").exists() { mod_dirs.insert(dir.clone()); }
        if let Ok(entries) = std::fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() { scan_dirs.push(path); }
            }
        }
    }
    stats.module_count = mod_dirs.len();
    stats.key_types.sort_by(|a, b| a.name.cmp(&b.name));
    stats.key_types.truncate(50);
    Ok(stats)
}

fn build_tree(root: &Path, depth: usize, max_depth: usize) -> String {
    if depth > max_depth { return String::new(); }
    let mut out = String::new();
    let entries = match std::fs::read_dir(root) { Ok(e) => e, Err(_) => return out };
    let mut items: Vec<_> = entries.flatten().filter(|e| {
        let name = e.file_name(); let name_str = name.to_string_lossy();
        !name_str.starts_with('.') && !name_str.starts_with("target") && !name_str.starts_with("node_modules") && name_str != "Cargo.lock"
    }).collect();
    items.sort_by_key(|e| (!e.file_type().map(|t| t.is_dir()).unwrap_or(false), e.file_name().to_string_lossy().to_string()));
    for item in &items {
        let name = item.file_name().to_string_lossy().to_string();
        let indent = "  ".repeat(depth);
        if item.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            out.push_str(&format!("{}{}/\n", indent, name));
            out.push_str(&build_tree(&item.path(), depth + 1, max_depth));
        } else if name.ends_with(".rs") || name == "Cargo.toml" || name.ends_with(".md") {
            out.push_str(&format!("{}{}\n", indent, name));
        }
    }
    out
}
