//! Integrated Information Theory (IIT) Φ 度量
//!
//! 基于 Tononi (2004) / Chalmers (2023):
//!   Φ = 系统的不可约整体信息量
//!   "The amount of information generated by the whole system
//!    that cannot be reduced to its parts"
//!
//! 我们的实践近似:
//!   Φ_resonance = 共振加权协方差 / 总能量 - 1/N
//!
//! 即: 状态向量在 E8 共振图上的对齐程度
//!   - Φ → 0: 维度独立运行 (零集成)
//!   - Φ → 1: 全系统共振 (最大集成)
//!
//! 参考: Tononi, G. (2004). "An information integration theory of consciousness"
//!       Chalmers, D. (2023). "Could a large language model be conscious?"

use serde::{Deserialize, Serialize};
use crate::neotrix::nt_world_e8::E8WorldModel;

// ============================================================
// 常量
// ============================================================

/// 共振宽度 σ — 维度间耦合范围
pub const PHI_RESONANCE_SIGMA: f64 = 0.15;

/// 最小 Φ 阈值 — 低于此值认为无集成
pub const PHI_MIN_THRESHOLD: f64 = 0.01;

/// Φ 历史窗口 (趋势分析)
pub const PHI_HISTORY_WINDOW: usize = 20;

// ============================================================
// Φ 报告
// ============================================================

/// IIT Φ 分析报告
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhiReport {
    /// 当前集成信息量 Φ
    pub phi: f64,
    /// 原始 Φ (未归一化)
    pub phi_raw: f64,
    /// 共振总强度 ΣR[i,j]
    pub total_resonance: f64,
    /// 状态能量 ||x||²
    pub state_energy: f64,
    /// 维度数 (有效集成维数)
    pub effective_dims: usize,
    /// 最大共振对 (最集成的维度对)
    pub max_resonance_pair: (usize, usize),
    /// Φ 趋势 (正 = 集成度增加)
    pub phi_trend: f64,
    /// 是否达到意识黄金标准 (Φ > 0.33)
    pub is_conscious_like: bool,
}

// ============================================================
// IIT Φ 计算器
// ============================================================

/// IIT Φ 计算器 — 量化 E8 64 卦空间的集成信息
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IITPhiCalculator {
    /// 共振宽度 σ
    pub sigma: f64,
    /// Φ 历史
    pub phi_history: Vec<f64>,
}

impl Default for IITPhiCalculator {
    fn default() -> Self {
        Self::new()
    }
}

impl IITPhiCalculator {
    pub fn new() -> Self {
        Self {
            sigma: PHI_RESONANCE_SIGMA,
            phi_history: Vec::with_capacity(PHI_HISTORY_WINDOW),
        }
    }

    /// 计算共振矩阵 R[i][j] = exp(-(x_i - x_j)² / σ²)
    /// 维度间耦合强度
    pub fn resonance_matrix(&self, state: &[f64]) -> Vec<Vec<f64>> {
        let n = state.len().min(64);
        let mut r = vec![vec![0.0; n]; n];
        for i in 0..n {
            for j in 0..n {
                let diff = state[i] - state[j];
                r[i][j] = (-diff * diff / (self.sigma * self.sigma)).exp();
            }
        }
        r
    }

    /// 计算集成信息 Φ:
    ///   Φ = (Σ_i,j R[i][j]·x_i·x_j) / (Σ_i x_i²) - 1/N
    ///
    /// 核心思想: 维度间共振强度 × 激活水平,
    /// 减去独立基线的 1/N 修正项
    pub fn compute_phi(&self, state: &[f64]) -> PhiReport {
        let n = state.len().min(64);
        let state_energy: f64 = state.iter().map(|v| v * v).sum();
        if state_energy < 1e-12 {
            return PhiReport {
                phi: 0.0, phi_raw: 0.0, total_resonance: 0.0,
                state_energy: 0.0, effective_dims: 0,
                max_resonance_pair: (0, 0), phi_trend: 0.0,
                is_conscious_like: false,
            };
        }

        let r = self.resonance_matrix(state);

        // Σ R[i][j]·x_i·x_j
        let mut weighted_sum = 0.0;
        let mut total_resonance = 0.0;
        let mut max_val = 0.0;
        let mut max_pair = (0usize, 0usize);

        for i in 0..n {
            for j in 0..n {
                let rv = r[i][j] * state[i] * state[j];
                weighted_sum += rv;
                total_resonance += r[i][j];
                if i != j && rv.abs() > max_val {
                    max_val = rv.abs();
                    max_pair = (i, j);
                }
            }
        }

        // 有效集成维数: 状态中显著贡献的维度
        let effective_dims = state.iter()
            .filter(|&&v| v.abs() > 0.05)
            .count()
            .max(1);

        // Φ_raw = 共振加权协方差 / 总能量
        let phi_raw = weighted_sum / state_energy;

        // Φ = Φ_raw - 1/N (独立基线修正)
        let phi = (phi_raw - 1.0 / n as f64).clamp(0.0, 1.0);

        // Φ 趋势
        let phi_trend = self.compute_trend(phi);

        let is_conscious_like = phi > 0.33;

        PhiReport {
            phi,
            phi_raw,
            total_resonance,
            state_energy,
            effective_dims,
            max_resonance_pair: max_pair,
            phi_trend,
            is_conscious_like,
        }
    }

    /// 从 E8WorldModel 直接计算 Φ
    pub fn compute_from_e8(&self, e8: &E8WorldModel) -> PhiReport {
        self.compute_phi(&e8.current_state.vector)
    }

    /// 计算 Φ 趋势 (基于历史)
    fn compute_trend(&self, current_phi: f64) -> f64 {
        if self.phi_history.len() < 5 { return 0.0; }
        let n = self.phi_history.len();
        let recent_avg: f64 = self.phi_history[n - 5..].iter().sum::<f64>() / 5.0;
        current_phi - recent_avg
    }

    /// 记录 Φ 值到历史
    pub fn record(&mut self, phi: f64) {
        self.phi_history.push(phi);
        if self.phi_history.len() > PHI_HISTORY_WINDOW {
            self.phi_history.remove(0);
        }
    }

    /// 完整周期: 计算 + 记录 + 报告
    pub fn analyze_e8(&mut self, e8: &E8WorldModel) -> PhiReport {
        let report = self.compute_from_e8(e8);
        self.record(report.phi);
        report
    }

    /// 计算子系统 Φ (分割测试)
    /// 将 N 维状态分为 k 个子系统, 计算每个子系统的内部 Φ
    pub fn subsystem_analysis(&self, state: &[f64], k: usize) -> Vec<(usize, usize, f64)> {
        let n = state.len().min(64);
        if k == 0 || k > n { return vec![]; }

        let chunk_size = n / k;
        let mut results = Vec::new();

        for group in 0..k {
            let start = group * chunk_size;
            let end = if group == k - 1 { n } else { (group + 1) * chunk_size };
            let sub_state: Vec<f64> = state[start..end].to_vec();
            let report = self.compute_phi(&sub_state);
            results.push((start, end, report.phi));
        }

        results
    }

    /// 配置共振宽度
    pub fn with_sigma(mut self, sigma: f64) -> Self {
        self.sigma = sigma;
        self
    }
}

// ============================================================
// 测试
// ============================================================
#[cfg(test)]
mod tests {
    use super::*;

    fn uniform_state() -> Vec<f64> {
        vec![0.5; 64]
    }

    fn sparse_state() -> Vec<f64> {
        let mut v = vec![0.0; 64];
        v[0] = 1.0;
        v[1] = 0.8;
        v[2] = 0.6;
        v
    }

    fn random_state() -> Vec<f64> {
        (0..64).map(|_| rand::random::<f64>() * 2.0 - 1.0).collect()
    }

    #[test]
    fn test_resonance_matrix_dimensions() {
        let calc = IITPhiCalculator::new();
        let r = calc.resonance_matrix(&vec![0.5; 64]);
        assert_eq!(r.len(), 64);
        assert_eq!(r[0].len(), 64);
    }

    #[test]
    fn test_resonance_matrix_self_is_one() {
        let calc = IITPhiCalculator::new();
        let r = calc.resonance_matrix(&vec![0.5; 64]);
        for i in 0..64 {
            assert!((r[i][i] - 1.0).abs() < 1e-10, "Self-resonance must be 1");
        }
    }

    #[test]
    fn test_uniform_state_phi() {
        let calc = IITPhiCalculator::new();
        let report = calc.compute_phi(&uniform_state());
        // Uniform state: all dimensions equally active → moderate integration
        assert!(report.phi >= 0.0);
        assert!(report.phi <= 1.0);
        assert_eq!(report.effective_dims, 64);
    }

    #[test]
    fn test_sparse_state_low_phi() {
        let calc = IITPhiCalculator::new();
        let report = calc.compute_phi(&sparse_state());
        // Only 3 active dims → low integration (mostly isolated)
        assert!(report.phi >= 0.0);
    }

    #[test]
    fn test_random_state_finite() {
        let calc = IITPhiCalculator::new();
        let report = calc.compute_phi(&random_state());
        assert!(report.phi.is_finite());
        assert!(report.state_energy > 0.0);
    }

    #[test]
    fn test_zero_state_zero_phi() {
        let calc = IITPhiCalculator::new();
        let report = calc.compute_phi(&vec![0.0; 64]);
        assert!((report.phi - 0.0).abs() < 1e-10);
        assert!((report.state_energy - 0.0).abs() < 1e-10);
    }

    #[test]
    fn test_phi_increases_with_coherence() {
        let calc = IITPhiCalculator::new();
        // Coherent: all dimensions equal → resonance everywhere
        let coherent = calc.compute_phi(&vec![1.0; 64]);
        // Incoherent: dimensions randomly distributed
        let incoherent = calc.compute_phi(&random_state());
        // Coherent state should have higher Φ
        assert!(coherent.phi >= incoherent.phi - 0.1,
            "Coherent state should have comparable or higher Φ");
    }

    #[test]
    fn test_subsystem_analysis() {
        let calc = IITPhiCalculator::new();
        let results = calc.subsystem_analysis(&uniform_state(), 4);
        assert_eq!(results.len(), 4);
        for (start, end, phi) in &results {
            assert!(phi.is_finite());
            assert!(end > start);
        }
    }

    #[test]
    fn test_history_tracking() {
        let mut calc = IITPhiCalculator::new();
        calc.record(0.3);
        calc.record(0.4);
        calc.record(0.5);
        assert_eq!(calc.phi_history.len(), 3);
    }

    #[test]
    fn test_from_nt_world_e8() {
        let mut calc = IITPhiCalculator::new();
        let e8 = E8WorldModel::new();
        let report = calc.analyze_e8(&e8);
        assert!(report.phi >= 0.0);
        assert!(report.phi <= 1.0);
    }

    #[test]
    fn test_sigma_configuration() {
        let calc = IITPhiCalculator::with_sigma(IITPhiCalculator::new(), 0.5);
        assert!((calc.sigma - 0.5).abs() < 1e-10);
    }

    #[test]
    fn test_conscious_like_threshold() {
        let calc = IITPhiCalculator::new();
        // Very strong coherence → high Φ
        let state: Vec<f64> = (0..64).map(|i| ((i as f64) * 0.5).sin()).collect();
        let report = calc.compute_phi(&state);
        // Just check it's a valid result
        assert!(report.phi >= 0.0);
        assert!(report.phi <= 1.0);
    }

    #[test]
    fn test_max_resonance_pair_valid() {
        let calc = IITPhiCalculator::new();
        let report = calc.compute_phi(&uniform_state());
        let (_i, _j) = report.max_resonance_pair;
        // Just ensure it doesn't panic
    }
}
